/* miniz_export.h — normally generated by miniz's CMake. We compile only miniz_tinfl.c
   (the streaming DEFLATE inflater) straight into the firmware, with default linkage. */
#ifndef MINIZ_EXPORT_H
#define MINIZ_EXPORT_H
#define MINIZ_EXPORT
#define MINIZ_NO_EXPORT
#endif
