/* Generated by Nim Compiler v2.2.4 */
#define NIM_INTBITS 32
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct tyObject_ValueObj__GvkVL3gYndVcF1SEP1HhDQ tyObject_ValueObj__GvkVL3gYndVcF1SEP1HhDQ;
typedef struct tySequence__FZ9ca77725E4Q3UZTxnRAkA tySequence__FZ9ca77725E4Q3UZTxnRAkA;
typedef struct tySequence__FZ9ca77725E4Q3UZTxnRAkA_Content tySequence__FZ9ca77725E4Q3UZTxnRAkA_Content;
typedef struct {
N_NIMCALL_PTR(NI, ClP_0) (tyObject_ValueObj__GvkVL3gYndVcF1SEP1HhDQ* x_p0, tyObject_ValueObj__GvkVL3gYndVcF1SEP1HhDQ* y_p1, void* ClE_0);
void* ClE_0;
} tyProc__HAD2Ya7te3SHBZwzz9ceSqw;
typedef NU8 tyEnum_SortOrder__rCH0Bt6YiI3lFS9bIgXxPQw;
struct tySequence__FZ9ca77725E4Q3UZTxnRAkA {
  NI len; tySequence__FZ9ca77725E4Q3UZTxnRAkA_Content* p;
};
typedef N_CLOSURE_PTR(NI, TM__JdC9c6SaUkvO1XjYuWP1JWQ_2) (tyObject_ValueObj__GvkVL3gYndVcF1SEP1HhDQ* x_p0, tyObject_ValueObj__GvkVL3gYndVcF1SEP1HhDQ* y_p1);
typedef N_CLOSURE_PTR(NI, TM__JdC9c6SaUkvO1XjYuWP1JWQ_3) (tyObject_ValueObj__GvkVL3gYndVcF1SEP1HhDQ* x_p0, tyObject_ValueObj__GvkVL3gYndVcF1SEP1HhDQ* y_p1);
struct tySequence__FZ9ca77725E4Q3UZTxnRAkA_Content { NI cap; tyObject_ValueObj__GvkVL3gYndVcF1SEP1HhDQ* data[SEQ_DECL_SIZE]; };
N_LIB_PRIVATE N_NIMCALL(tySequence__FZ9ca77725E4Q3UZTxnRAkA, newSeq__OOZsrcZcakesparkZvalue_u304)(NI len_p0);
N_LIB_PRIVATE N_NIMCALL(void, mergeAlt__OOZsrcZcakesparkZvm_u15712)(tyObject_ValueObj__GvkVL3gYndVcF1SEP1HhDQ** a_p0, NI a_p0Len_0, tyObject_ValueObj__GvkVL3gYndVcF1SEP1HhDQ** b_p1, NI b_p1Len_0, NI lo_p2, NI m_p3, NI hi_p4, tyProc__HAD2Ya7te3SHBZwzz9ceSqw cmp_p5, tyEnum_SortOrder__rCH0Bt6YiI3lFS9bIgXxPQw order_p6);
static N_INLINE(NI, star___pureZalgorithm_u8)(NI x_p0, tyEnum_SortOrder__rCH0Bt6YiI3lFS9bIgXxPQw order_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___OOZsrcZcakesparkZvalue_u159)(tyObject_ValueObj__GvkVL3gYndVcF1SEP1HhDQ** dest_p0, tyObject_ValueObj__GvkVL3gYndVcF1SEP1HhDQ* src_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___OOZsrcZcakesparkZvalue_u147)(tyObject_ValueObj__GvkVL3gYndVcF1SEP1HhDQ** dest_p0);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZsrcZcakesparkZvalue_u86)(tySequence__FZ9ca77725E4Q3UZTxnRAkA dest_p0);
extern NIM_BOOL nimInErrorMode__system_u3521;
N_LIB_PRIVATE N_NIMCALL(void, fill__pureZstrutils_u1563)(NI* a_p0, NI a_p0Len_0, NI value_p1) {
	NI xX60gensym161__1;
	xX60gensym161__1 = ((NI)0);
	{
		while (1) {
			if (!(xX60gensym161__1 <= (a_p0Len_0-1))) goto LA2;
			a_p0[xX60gensym161__1] = value_p1;
			xX60gensym161__1 += ((NI)1);
		} LA2: ;
	}
}
static N_INLINE(NI, star___pureZalgorithm_u8)(NI x_p0, tyEnum_SortOrder__rCH0Bt6YiI3lFS9bIgXxPQw order_p1) {
	NI result;
	NI y_1;
	y_1 = (NI)(order_p1 - ((NI)1));
	result = (NI)((NI)(x_p0 ^ y_1) - y_1);
	return result;
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u3521);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, mergeAlt__OOZsrcZcakesparkZvm_u15712)(tyObject_ValueObj__GvkVL3gYndVcF1SEP1HhDQ** a_p0, NI a_p0Len_0, tyObject_ValueObj__GvkVL3gYndVcF1SEP1HhDQ** b_p1, NI b_p1Len_0, NI lo_p2, NI m_p3, NI hi_p4, tyProc__HAD2Ya7te3SHBZwzz9ceSqw cmp_p5, tyEnum_SortOrder__rCH0Bt6YiI3lFS9bIgXxPQw order_p6) {
	NI j_1;
	NI bb_1;
	NI i_1;
	NI k_1;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	{
		NI T3_;
		NI T4_;
		T3_ = (NI)0;
		T3_ = cmp_p5.ClE_0? cmp_p5.ClP_0(a_p0[m_p3], a_p0[(NI)(m_p3 + ((NI)1))], cmp_p5.ClE_0):((TM__JdC9c6SaUkvO1XjYuWP1JWQ_2)(cmp_p5.ClP_0))(a_p0[m_p3], a_p0[(NI)(m_p3 + ((NI)1))]);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		T4_ = (NI)0;
		T4_ = star___pureZalgorithm_u8(T3_, order_p6);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (!(T4_ <= ((NI)0))) goto LA5_;
		goto BeforeRet_;
	}
LA5_: ;
	j_1 = lo_p2;
	bb_1 = ((NI)0);
	{
		while (1) {
			tyObject_ValueObj__GvkVL3gYndVcF1SEP1HhDQ* T9_;
			if (!(j_1 <= m_p3)) goto LA8;
			T9_ = NIM_NIL;
			T9_ = a_p0[j_1];
			eqwasMoved___OOZsrcZcakesparkZvalue_u147((&a_p0[j_1]));
			eqsink___OOZsrcZcakesparkZvalue_u159(&b_p1[bb_1], T9_);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			bb_1 += ((NI)1);
			j_1 += ((NI)1);
		} LA8: ;
	}
	i_1 = ((NI)0);
	k_1 = lo_p2;
	{
		while (1) {
			NIM_BOOL T12_;
			T12_ = (NIM_BOOL)0;
			T12_ = (k_1 < j_1);
			if (!(T12_)) goto LA13_;
			T12_ = (j_1 <= hi_p4);
LA13_: ;
			if (!T12_) goto LA11;
			{
				NI T16_;
				NI T17_;
				tyObject_ValueObj__GvkVL3gYndVcF1SEP1HhDQ* T20_;
				T16_ = (NI)0;
				T16_ = cmp_p5.ClE_0? cmp_p5.ClP_0(b_p1[i_1], a_p0[j_1], cmp_p5.ClE_0):((TM__JdC9c6SaUkvO1XjYuWP1JWQ_3)(cmp_p5.ClP_0))(b_p1[i_1], a_p0[j_1]);
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				T17_ = (NI)0;
				T17_ = star___pureZalgorithm_u8(T16_, order_p6);
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				if (!(T17_ <= ((NI)0))) goto LA18_;
				T20_ = NIM_NIL;
				T20_ = b_p1[i_1];
				eqwasMoved___OOZsrcZcakesparkZvalue_u147((&b_p1[i_1]));
				eqsink___OOZsrcZcakesparkZvalue_u159(&a_p0[k_1], T20_);
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				i_1 += ((NI)1);
			}
			goto LA14_;
LA18_: ;
			{
				tyObject_ValueObj__GvkVL3gYndVcF1SEP1HhDQ* T22_;
				T22_ = NIM_NIL;
				T22_ = a_p0[j_1];
				eqwasMoved___OOZsrcZcakesparkZvalue_u147((&a_p0[j_1]));
				eqsink___OOZsrcZcakesparkZvalue_u159(&a_p0[k_1], T22_);
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				j_1 += ((NI)1);
			}
LA14_: ;
			k_1 += ((NI)1);
		} LA11: ;
	}
	{
		while (1) {
			tyObject_ValueObj__GvkVL3gYndVcF1SEP1HhDQ* T25_;
			if (!(k_1 < j_1)) goto LA24;
			T25_ = NIM_NIL;
			T25_ = b_p1[i_1];
			eqwasMoved___OOZsrcZcakesparkZvalue_u147((&b_p1[i_1]));
			eqsink___OOZsrcZcakesparkZvalue_u159(&a_p0[k_1], T25_);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			k_1 += ((NI)1);
			i_1 += ((NI)1);
		} LA24: ;
	}
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, sort__OOZsrcZcakesparkZvm_u15676)(tyObject_ValueObj__GvkVL3gYndVcF1SEP1HhDQ** a_p0, NI a_p0Len_0, tyProc__HAD2Ya7te3SHBZwzz9ceSqw cmp_p1, tyEnum_SortOrder__rCH0Bt6YiI3lFS9bIgXxPQw order_p2) {
	tySequence__FZ9ca77725E4Q3UZTxnRAkA b_1;
	NI n_1;
	NI s_1;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	b_1.len = 0; b_1.p = NIM_NIL;
	n_1 = a_p0Len_0;
	b_1 = newSeq__OOZsrcZcakesparkZvalue_u304(((NI)(n_1 / ((NI)2))));
	s_1 = ((NI)1);
	{
		while (1) {
			NI m_1;
			if (!(s_1 < n_1)) goto LA2;
			m_1 = (NI)((NI)(n_1 - ((NI)1)) - s_1);
			{
				while (1) {
					if (!(((NI)0) <= m_1)) goto LA4;
					mergeAlt__OOZsrcZcakesparkZvm_u15712(a_p0, a_p0Len_0, ((b_1).p) ? (b_1.p->data) : NIM_NIL, b_1.len, (((NI)((NI)(m_1 - s_1) + ((NI)1)) >= ((NI)0)) ? (NI)((NI)(m_1 - s_1) + ((NI)1)) : ((NI)0)), m_1, (NI)(m_1 + s_1), cmp_p1, order_p2);
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
					m_1 -= (NI)(s_1 * ((NI)2));
				} LA4: ;
			}
			s_1 = (NI)(s_1 * ((NI)2));
		} LA2: ;
	}
	eqdestroy___OOZsrcZcakesparkZvalue_u86(b_1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
