/* Generated by Nim Compiler v2.2.4 */
#define NIM_INTBITS 32
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct tyObject_HashSet__KXssDFT9bBM7Oo9a5pyfD0dQ tyObject_HashSet__KXssDFT9bBM7Oo9a5pyfD0dQ;
typedef struct tySequence__4eRCaZmrYLLw2k30GPTiMw tySequence__4eRCaZmrYLLw2k30GPTiMw;
typedef struct tySequence__4eRCaZmrYLLw2k30GPTiMw_Content tySequence__4eRCaZmrYLLw2k30GPTiMw_Content;
typedef struct tyTuple__QeWl6B6ffS4pU6WWrtcrDw tyTuple__QeWl6B6ffS4pU6WWrtcrDw;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_HashSet__uRDPJjNr9aUE7hkP9bBkE4iw tyObject_HashSet__uRDPJjNr9aUE7hkP9bBkE4iw;
typedef struct tySequence__quaCA0ePcBRCWYW74nGaBg tySequence__quaCA0ePcBRCWYW74nGaBg;
typedef struct tySequence__quaCA0ePcBRCWYW74nGaBg_Content tySequence__quaCA0ePcBRCWYW74nGaBg_Content;
typedef struct tyTuple__ZohvDPoCSAbtu9bkFpQg1yQ tyTuple__ZohvDPoCSAbtu9bkFpQg1yQ;
struct tySequence__4eRCaZmrYLLw2k30GPTiMw {
  NI len; tySequence__4eRCaZmrYLLw2k30GPTiMw_Content* p;
};
struct tyObject_HashSet__KXssDFT9bBM7Oo9a5pyfD0dQ {
	tySequence__4eRCaZmrYLLw2k30GPTiMw data;
	NI counter;
};
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
struct tyTuple__QeWl6B6ffS4pU6WWrtcrDw {
	NI Field0;
	NimStringV2 Field1;
};
struct tySequence__quaCA0ePcBRCWYW74nGaBg {
  NI len; tySequence__quaCA0ePcBRCWYW74nGaBg_Content* p;
};
struct tyObject_HashSet__uRDPJjNr9aUE7hkP9bBkE4iw {
	tySequence__quaCA0ePcBRCWYW74nGaBg data;
	NI counter;
};
struct tyTuple__ZohvDPoCSAbtu9bkFpQg1yQ {
	NI Field0;
	void* Field1;
};
struct tySequence__4eRCaZmrYLLw2k30GPTiMw_Content { NI cap; tyTuple__QeWl6B6ffS4pU6WWrtcrDw data[SEQ_DECL_SIZE]; };
struct tySequence__quaCA0ePcBRCWYW74nGaBg_Content { NI cap; tyTuple__ZohvDPoCSAbtu9bkFpQg1yQ data[SEQ_DECL_SIZE]; };
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1);
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(void, init__OOZsrcZcakesparkZcompiler_u2508)(tyObject_HashSet__KXssDFT9bBM7Oo9a5pyfD0dQ* s_p0, NI initialSize_p1);
static N_INLINE(NI, slotsNeeded__pureZcollectionsZsets_u50)(NI count_p0);
N_LIB_PRIVATE N_NIMCALL(NI, nextPowerOfTwo__pureZmath_u245)(NI x_p0);
N_LIB_PRIVATE N_NIMCALL(void, newSeq__OOZsrcZcakesparkZcompiler_u2524)(tySequence__4eRCaZmrYLLw2k30GPTiMw* s_p0, NI len_p1);
N_LIB_PRIVATE N_NOCONV(void, dealloc)(void* p_p0);
static N_INLINE(NI, rawGet__OOZsrcZcakesparkZcompiler_u2765)(tyObject_HashSet__KXssDFT9bBM7Oo9a5pyfD0dQ t_p0, NimStringV2 key_p1, NI* hc_p2);
N_LIB_PRIVATE N_NIMCALL(NI, hash__pureZhashes_u598)(NimStringV2 x_p0);
static N_INLINE(NIM_BOOL, isFilled__pureZcollectionsZsets_u39)(NI hcode_p0);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringV2 a_p0, NimStringV2 b_p1);
static N_INLINE(NIM_BOOL, equalMem__system_u1739)(void* a_p0, void* b_p1, NI size_p2);
static N_INLINE(int, nimCmpMem)(void* a_p0, void* b_p1, NI size_p2);
static N_INLINE(NI, nextTry__pureZcollectionsZsets_u42)(NI h_p0, NI maxHash_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZsrcZcakesparkZcompiler_u2641)(tySequence__4eRCaZmrYLLw2k30GPTiMw dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, alignedDealloc)(void* p_p0, NI align_p1);
static N_INLINE(NIM_BOOL, mustRehash__OOZsrcZcakesparkZcompiler_u3122)(tyObject_HashSet__KXssDFT9bBM7Oo9a5pyfD0dQ t_p0);
N_LIB_PRIVATE N_NIMCALL(void, enlarge__OOZsrcZcakesparkZcompiler_u3302)(tyObject_HashSet__KXssDFT9bBM7Oo9a5pyfD0dQ* s_p0);
static N_INLINE(NI, rawGetKnownHC__OOZsrcZcakesparkZcompiler_u3537)(tyObject_HashSet__KXssDFT9bBM7Oo9a5pyfD0dQ t_p0, NimStringV2 key_p1, NI hc_p2);
N_LIB_PRIVATE N_NIMCALL(void, rawInsert__OOZsrcZcakesparkZcompiler_u3875)(tyObject_HashSet__KXssDFT9bBM7Oo9a5pyfD0dQ* s_p0, tySequence__4eRCaZmrYLLw2k30GPTiMw* data_p1, NimStringV2 key_p2, NI hc_p3, NI h_p4);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___system_u2610)(NimStringV2* dest_p0, NimStringV2 src_p1);
N_LIB_PRIVATE N_NIMCALL(void, init__OOZsrcZcakesparkZvm_u7484)(tyObject_HashSet__uRDPJjNr9aUE7hkP9bBkE4iw* s_p0, NI initialSize_p1);
N_LIB_PRIVATE N_NIMCALL(void, newSeq__OOZsrcZcakesparkZvm_u6447)(tySequence__quaCA0ePcBRCWYW74nGaBg* s_p0, NI len_p1);
static N_INLINE(NI, rawGet__OOZsrcZcakesparkZvm_u6014)(tyObject_HashSet__uRDPJjNr9aUE7hkP9bBkE4iw t_p0, void* key_p1, NI* hc_p2);
static N_INLINE(NI, hash__pureZhashes_u127)(void* x_p0);
static N_INLINE(NI, hash__pureZhashes_u131)(NI x_p0);
static N_INLINE(NI, hashWangYi1__pureZhashes_u139)(NU64 x_p0);
static N_INLINE(NU64, hiXorLo__pureZhashes_u80)(NU64 a_p0, NU64 b_p1);
static N_INLINE(NU64, hiXorLoFallback64__pureZhashes_u36)(NU64 a_p0, NU64 b_p1);
static N_INLINE(NIM_BOOL, mustRehash__OOZsrcZcakesparkZvm_u6474)(tyObject_HashSet__uRDPJjNr9aUE7hkP9bBkE4iw t_p0);
N_LIB_PRIVATE N_NIMCALL(void, enlarge__OOZsrcZcakesparkZvm_u6654)(tyObject_HashSet__uRDPJjNr9aUE7hkP9bBkE4iw* s_p0);
static N_INLINE(NI, rawGetKnownHC__OOZsrcZcakesparkZvm_u6889)(tyObject_HashSet__uRDPJjNr9aUE7hkP9bBkE4iw t_p0, void* key_p1, NI hc_p2);
N_LIB_PRIVATE N_NIMCALL(void, rawInsert__OOZsrcZcakesparkZvm_u7227)(tyObject_HashSet__uRDPJjNr9aUE7hkP9bBkE4iw* s_p0, tySequence__quaCA0ePcBRCWYW74nGaBg* data_p1, void* key_p2, NI hc_p3, NI h_p4);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZsrcZcakesparkZvm_u6263)(tySequence__quaCA0ePcBRCWYW74nGaBg dest_p0);
extern NIM_BOOL nimInErrorMode__system_u3521;
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a_p0, v_p1, ((size_t) (size_p2)));
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u3521);
	return result;
}
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimSetMem__systemZmemory_u7(p_p0, ((int)0), size_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
static N_INLINE(NI, slotsNeeded__pureZcollectionsZsets_u50)(NI count_p0) {
	NI result;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NI)0;
	result = nextPowerOfTwo__pureZmath_u245((NI)((NI)((NI)(count_p0 / ((NI)2)) + count_p0) + ((NI)4)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZsrcZcakesparkZcompiler_u2602)(tyTuple__QeWl6B6ffS4pU6WWrtcrDw* dest_p0) {
	if ((*dest_p0).Field1.p && !((*dest_p0).Field1.p->cap & NIM_STRLIT_FLAG)) {
 dealloc((*dest_p0).Field1.p);
}
}
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___OOZsrcZcakesparkZcompiler_u2599)(tyTuple__QeWl6B6ffS4pU6WWrtcrDw* dest_p0) {
	(*dest_p0).Field0 = 0;
	(*dest_p0).Field1.len = 0; (*dest_p0).Field1.p = NIM_NIL;
}
N_LIB_PRIVATE N_NIMCALL(void, init__OOZsrcZcakesparkZcompiler_u2508)(tyObject_HashSet__KXssDFT9bBM7Oo9a5pyfD0dQ* s_p0, NI initialSize_p1) {
	NI correctSizeX60gensym23__1;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	correctSizeX60gensym23__1 = slotsNeeded__pureZcollectionsZsets_u50((initialSize_p1));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	(*s_p0).counter = ((NI)0);
	newSeq__OOZsrcZcakesparkZcompiler_u2524((&(*s_p0).data), (correctSizeX60gensym23__1));
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_HashSet__KXssDFT9bBM7Oo9a5pyfD0dQ, initHashSet__OOZsrcZcakesparkZcompiler_u2494)(NI initialSize_p0) {
	tyObject_HashSet__KXssDFT9bBM7Oo9a5pyfD0dQ result;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)(&result), sizeof(tyObject_HashSet__KXssDFT9bBM7Oo9a5pyfD0dQ));
	init__OOZsrcZcakesparkZcompiler_u2508((&result), initialSize_p0);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(NIM_BOOL, isFilled__pureZcollectionsZsets_u39)(NI hcode_p0) {
	NIM_BOOL result;
	result = !((hcode_p0 == ((NI)0)));
	return result;
}
static N_INLINE(int, nimCmpMem)(void* a_p0, void* b_p1, NI size_p2) {
	int result;
	result = memcmp(a_p0, b_p1, ((size_t) (size_p2)));
	return result;
}
static N_INLINE(NIM_BOOL, equalMem__system_u1739)(void* a_p0, void* b_p1, NI size_p2) {
	NIM_BOOL result;
	int T1_;
	T1_ = (int)0;
	T1_ = nimCmpMem(a_p0, b_p1, size_p2);
	result = (T1_ == ((NI32)0));
	return result;
}
static N_INLINE(NIM_BOOL, eqStrings)(NimStringV2 a_p0, NimStringV2 b_p1) {
	NIM_BOOL result;
	NI alen_1;
	NI blen_1;
{	result = NIM_FALSE;
	alen_1 = a_p0.len;
	blen_1 = b_p1.len;
	{
		if (!(alen_1 == blen_1)) goto LA3_;
		{
			if (!(alen_1 == ((NI)0))) goto LA7_;
			result = NIM_TRUE;
			goto BeforeRet_;
		}
LA7_: ;
		result = equalMem__system_u1739(((void*) ((&a_p0.p->data[((NI)0)]))), ((void*) ((&b_p1.p->data[((NI)0)]))), (alen_1));
		goto BeforeRet_;
	}
LA3_: ;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(NI, nextTry__pureZcollectionsZsets_u42)(NI h_p0, NI maxHash_p1) {
	NI result;
	result = (NI)((NI)(h_p0 + ((NI)1)) & maxHash_p1);
	return result;
}
static N_INLINE(NI, rawGet__OOZsrcZcakesparkZcompiler_u2765)(tyObject_HashSet__KXssDFT9bBM7Oo9a5pyfD0dQ t_p0, NimStringV2 key_p1, NI* hc_p2) {
	NI result;
	NI T1_;
	NI h_1;
	NI T11_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NI)0;
	T1_ = (NI)0;
	T1_ = hash__pureZhashes_u598(key_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	(*hc_p2) = T1_;
	{
		if (!((*hc_p2) == ((NI)0))) goto LA4_;
		(*hc_p2) = ((NI)314159265);
	}
LA4_: ;
	{
		NI T8_;
		T8_ = t_p0.data.len;
		if (!(T8_ == ((NI)0))) goto LA9_;
		result = ((NI)-1);
		goto BeforeRet_;
	}
LA9_: ;
	T11_ = (t_p0.data.len-1);
	h_1 = (NI)((*hc_p2) & T11_);
	{
		while (1) {
			NIM_BOOL T14_;
			NI T21_;
			T14_ = (NIM_BOOL)0;
			T14_ = isFilled__pureZcollectionsZsets_u39(t_p0.data.p->data[h_1].Field0);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			if (!T14_) goto LA13;
			{
				NIM_BOOL T17_;
				T17_ = (NIM_BOOL)0;
				T17_ = (t_p0.data.p->data[h_1].Field0 == (*hc_p2));
				if (!(T17_)) goto LA18_;
				T17_ = eqStrings(t_p0.data.p->data[h_1].Field1, key_p1);
LA18_: ;
				if (!T17_) goto LA19_;
				result = h_1;
				goto BeforeRet_;
			}
LA19_: ;
			T21_ = (t_p0.data.len-1);
			h_1 = nextTry__pureZcollectionsZsets_u42(h_1, T21_);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		} LA13: ;
	}
	result = (NI)(((NI)-1) - h_1);
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, contains__OOZsrcZcakesparkZcompiler_u2752)(tyObject_HashSet__KXssDFT9bBM7Oo9a5pyfD0dQ s_p0, NimStringV2 key_p1) {
	NIM_BOOL result;
	NI hc_1;
	NI index_1;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NIM_BOOL)0;
	hc_1 = (NI)0;
	index_1 = rawGet__OOZsrcZcakesparkZcompiler_u2765(s_p0, key_p1, (&hc_1));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	result = (((NI)0) <= index_1);
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZsrcZcakesparkZcompiler_u2641)(tySequence__4eRCaZmrYLLw2k30GPTiMw dest_p0) {
	NI colontmp_;
	colontmp_ = ((NI)0);
	{
		while (1) {
			NI T3_;
			T3_ = dest_p0.len;
			if (!(colontmp_ < T3_)) goto LA2;
			if (dest_p0.p->data[colontmp_].Field1.p && !(dest_p0.p->data[colontmp_].Field1.p->cap & NIM_STRLIT_FLAG)) {
 dealloc(dest_p0.p->data[colontmp_].Field1.p);
}
			colontmp_ += ((NI)1);
		} LA2: ;
	}
	if (dest_p0.p && !(dest_p0.p->cap & NIM_STRLIT_FLAG)) {
 alignedDealloc(dest_p0.p, NIM_ALIGNOF(tyTuple__QeWl6B6ffS4pU6WWrtcrDw));
}
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZsrcZcakesparkZcompiler_u2678)(tyObject_HashSet__KXssDFT9bBM7Oo9a5pyfD0dQ* dest_p0) {
	eqdestroy___OOZsrcZcakesparkZcompiler_u2641((*dest_p0).data);
}
static N_INLINE(NIM_BOOL, mustRehash__OOZsrcZcakesparkZcompiler_u3122)(tyObject_HashSet__KXssDFT9bBM7Oo9a5pyfD0dQ t_p0) {
	NIM_BOOL result;
	NIM_BOOL T1_;
	NI T2_;
	NI T4_;
	T1_ = (NIM_BOOL)0;
	T2_ = t_p0.data.len;
	T1_ = (T2_ < (NI)(t_p0.counter + (NI)(t_p0.counter / ((NI)2))));
	if (T1_) goto LA3_;
	T4_ = t_p0.data.len;
	T1_ = ((NI)(T4_ - t_p0.counter) < ((NI)4));
LA3_: ;
	result = T1_;
	return result;
}
static N_INLINE(NI, rawGetKnownHC__OOZsrcZcakesparkZcompiler_u3537)(tyObject_HashSet__KXssDFT9bBM7Oo9a5pyfD0dQ t_p0, NimStringV2 key_p1, NI hc_p2) {
	NI result;
	NI h_1;
	NI T6_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NI)0;
	{
		NI T3_;
		T3_ = t_p0.data.len;
		if (!(T3_ == ((NI)0))) goto LA4_;
		result = ((NI)-1);
		goto BeforeRet_;
	}
LA4_: ;
	T6_ = (t_p0.data.len-1);
	h_1 = (NI)(hc_p2 & T6_);
	{
		while (1) {
			NIM_BOOL T9_;
			NI T16_;
			T9_ = (NIM_BOOL)0;
			T9_ = isFilled__pureZcollectionsZsets_u39(t_p0.data.p->data[h_1].Field0);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			if (!T9_) goto LA8;
			{
				NIM_BOOL T12_;
				T12_ = (NIM_BOOL)0;
				T12_ = (t_p0.data.p->data[h_1].Field0 == hc_p2);
				if (!(T12_)) goto LA13_;
				T12_ = eqStrings(t_p0.data.p->data[h_1].Field1, key_p1);
LA13_: ;
				if (!T12_) goto LA14_;
				result = h_1;
				goto BeforeRet_;
			}
LA14_: ;
			T16_ = (t_p0.data.len-1);
			h_1 = nextTry__pureZcollectionsZsets_u42(h_1, T16_);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		} LA8: ;
	}
	result = (NI)(((NI)-1) - h_1);
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, rawInsert__OOZsrcZcakesparkZcompiler_u3875)(tyObject_HashSet__KXssDFT9bBM7Oo9a5pyfD0dQ* s_p0, tySequence__4eRCaZmrYLLw2k30GPTiMw* data_p1, NimStringV2 key_p2, NI hc_p3, NI h_p4) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	{
		NI T3_;
		NI correctSizeX60gensym35__1;
		T3_ = (*data_p1).len;
		if (!(T3_ == ((NI)0))) goto LA4_;
		correctSizeX60gensym35__1 = slotsNeeded__pureZcollectionsZsets_u50(((NI)64));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		(*s_p0).counter = ((NI)0);
		newSeq__OOZsrcZcakesparkZcompiler_u2524((&(*s_p0).data), (correctSizeX60gensym35__1));
	}
LA4_: ;
	eqcopy___system_u2610((&(*data_p1).p->data[h_p4].Field1), key_p2);
	(*data_p1).p->data[h_p4].Field0 = hc_p3;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, enlarge__OOZsrcZcakesparkZcompiler_u3302)(tyObject_HashSet__KXssDFT9bBM7Oo9a5pyfD0dQ* s_p0) {
	tySequence__4eRCaZmrYLLw2k30GPTiMw n_1;
	NI T1_;
	tySequence__4eRCaZmrYLLw2k30GPTiMw T2_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	n_1.len = 0; n_1.p = NIM_NIL;
	T1_ = (*s_p0).data.len;
	newSeq__OOZsrcZcakesparkZcompiler_u2524((&n_1), ((NI)(T1_ * ((NI)2))));
	T2_.len = 0; T2_.p = NIM_NIL;
	T2_ = (*s_p0).data;
	(*s_p0).data = n_1;
	n_1 = T2_;
	{
		NI i_1;
		NI colontmp_;
		NI T4_;
		NI res_1;
		i_1 = (NI)0;
		colontmp_ = (NI)0;
		T4_ = (n_1.len-1);
		colontmp_ = T4_;
		res_1 = ((NI)0);
		{
			while (1) {
				if (!(res_1 <= colontmp_)) goto LA6;
				i_1 = ((NI) (res_1));
				{
					NIM_BOOL T9_;
					NI j_1;
					NI T12_;
					tyObject_HashSet__KXssDFT9bBM7Oo9a5pyfD0dQ* T13_;
					T9_ = (NIM_BOOL)0;
					T9_ = isFilled__pureZcollectionsZsets_u39(n_1.p->data[i_1].Field0);
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
					if (!T9_) goto LA10_;
					T12_ = (NI)0;
					T12_ = rawGetKnownHC__OOZsrcZcakesparkZcompiler_u3537((*s_p0), n_1.p->data[i_1].Field1, n_1.p->data[i_1].Field0);
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
					j_1 = (NI)(((NI)-1) - T12_);
					T13_ = (tyObject_HashSet__KXssDFT9bBM7Oo9a5pyfD0dQ*)0;
					T13_ = s_p0;
					rawInsert__OOZsrcZcakesparkZcompiler_u3875(T13_, (&(*s_p0).data), n_1.p->data[i_1].Field1, n_1.p->data[i_1].Field0, j_1);
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				}
LA10_: ;
				res_1 += ((NI)1);
			} LA6: ;
		}
	}
	eqdestroy___OOZsrcZcakesparkZcompiler_u2641(n_1);
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, incl__OOZsrcZcakesparkZcompiler_u3033)(tyObject_HashSet__KXssDFT9bBM7Oo9a5pyfD0dQ* s_p0, NimStringV2 key_p1) {
	NI hc_1;
	NI index_1;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	{
		NI T3_;
		NI correctSizeX60gensym28__1;
		T3_ = (*s_p0).data.len;
		if (!(T3_ == ((NI)0))) goto LA4_;
		correctSizeX60gensym28__1 = slotsNeeded__pureZcollectionsZsets_u50(((NI)64));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		(*s_p0).counter = ((NI)0);
		newSeq__OOZsrcZcakesparkZcompiler_u2524((&(*s_p0).data), (correctSizeX60gensym28__1));
	}
LA4_: ;
	hc_1 = (NI)0;
	index_1 = rawGet__OOZsrcZcakesparkZcompiler_u2765((*s_p0), key_p1, (&hc_1));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	{
		tyObject_HashSet__KXssDFT9bBM7Oo9a5pyfD0dQ* T15_;
		if (!(index_1 < ((NI)0))) goto LA8_;
		{
			NIM_BOOL T12_;
			T12_ = (NIM_BOOL)0;
			T12_ = mustRehash__OOZsrcZcakesparkZcompiler_u3122((*s_p0));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			if (!T12_) goto LA13_;
			enlarge__OOZsrcZcakesparkZcompiler_u3302(s_p0);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			index_1 = rawGetKnownHC__OOZsrcZcakesparkZcompiler_u3537((*s_p0), key_p1, hc_1);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		}
LA13_: ;
		T15_ = (tyObject_HashSet__KXssDFT9bBM7Oo9a5pyfD0dQ*)0;
		T15_ = s_p0;
		rawInsert__OOZsrcZcakesparkZcompiler_u3875(T15_, (&(*s_p0).data), key_p1, hc_1, (NI)(((NI)-1) - index_1));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		(*s_p0).counter += ((NI)1);
	}
LA8_: ;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, init__OOZsrcZcakesparkZvm_u7484)(tyObject_HashSet__uRDPJjNr9aUE7hkP9bBkE4iw* s_p0, NI initialSize_p1) {
	NI correctSizeX60gensym109__1;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	correctSizeX60gensym109__1 = slotsNeeded__pureZcollectionsZsets_u50((initialSize_p1));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	(*s_p0).counter = ((NI)0);
	newSeq__OOZsrcZcakesparkZvm_u6447((&(*s_p0).data), (correctSizeX60gensym109__1));
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_HashSet__uRDPJjNr9aUE7hkP9bBkE4iw, initHashSet__OOZsrcZcakesparkZvm_u7470)(NI initialSize_p0) {
	tyObject_HashSet__uRDPJjNr9aUE7hkP9bBkE4iw result;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)(&result), sizeof(tyObject_HashSet__uRDPJjNr9aUE7hkP9bBkE4iw));
	init__OOZsrcZcakesparkZvm_u7484((&result), initialSize_p0);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(NU64, hiXorLoFallback64__pureZhashes_u36)(NU64 a_p0, NU64 b_p1) {
	NU64 result;
	NU64 colontmpD_;
	NU64 colontmpD__2;
	NU64 colontmpD__3;
	NU64 colontmpD__4;
	NU64 aH_1;
	NU64 aL_1;
	NU64 bH_1;
	NU64 bL_1;
	NU64 rHH_1;
	NU64 rHL_1;
	NU64 rLH_1;
	NU64 rLL_1;
	NU64 t_1;
	NU64 c_1;
	NU64 lo_1;
	NU64 T6_;
	NU64 hi_1;
{	colontmpD_ = (NU64)0;
	colontmpD__2 = (NU64)0;
	colontmpD__3 = (NU64)0;
	colontmpD__4 = (NU64)0;
	aH_1 = (NU64)((NU64)(a_p0) >> (NU64)(((NI)32)));
	aL_1 = (NU64)(a_p0 & 4294967295ULL);
	bH_1 = (NU64)((NU64)(b_p1) >> (NU64)(((NI)32)));
	bL_1 = (NU64)(b_p1 & 4294967295ULL);
	rHH_1 = (NU64)((NU64)(aH_1) * (NU64)(bH_1));
	rHL_1 = (NU64)((NU64)(aH_1) * (NU64)(bL_1));
	rLH_1 = (NU64)((NU64)(aL_1) * (NU64)(bH_1));
	rLL_1 = (NU64)((NU64)(aL_1) * (NU64)(bL_1));
	t_1 = (NU64)((NU64)(rLL_1) + (NU64)((NU64)((NU64)(rHL_1) << (NU64)(((NI)32)))));
	{
		if (!((NU64)(t_1) < (NU64)(rLL_1))) goto LA3_;
		colontmpD_ = 1ULL;
		c_1 = colontmpD_;
	}
	goto LA1_;
LA3_: ;
	{
		colontmpD__2 = 0ULL;
		c_1 = colontmpD__2;
	}
LA1_: ;
	lo_1 = (NU64)((NU64)(t_1) + (NU64)((NU64)((NU64)(rLH_1) << (NU64)(((NI)32)))));
	T6_ = (NU64)0;
	{
		if (!((NU64)(lo_1) < (NU64)(t_1))) goto LA9_;
		colontmpD__3 = 1ULL;
		T6_ = colontmpD__3;
	}
	goto LA7_;
LA9_: ;
	{
		colontmpD__4 = 0ULL;
		T6_ = colontmpD__4;
	}
LA7_: ;
	c_1 += T6_;
	hi_1 = (NU64)((NU64)((NU64)((NU64)((NU64)((NU64)(rHH_1) + (NU64)((NU64)((NU64)(rHL_1) >> (NU64)(((NI)32)))))) + (NU64)((NU64)((NU64)(rLH_1) >> (NU64)(((NI)32)))))) + (NU64)(c_1));
	result = (NU64)(hi_1 ^ lo_1);
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(NU64, hiXorLo__pureZhashes_u80)(NU64 a_p0, NU64 b_p1) {
	NU64 result;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NU64)0;
	result = hiXorLoFallback64__pureZhashes_u36(a_p0, b_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(NI, hashWangYi1__pureZhashes_u139)(NU64 x_p0) {
	NI result;
	NU64 T1_;
	NU64 T2_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NI)0;
	T1_ = (NU64)0;
	T1_ = hiXorLo__pureZhashes_u80(11562461410679940143ULL, (NU64)(x_p0 ^ 16646288086500911323ULL));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	T2_ = (NU64)0;
	T2_ = hiXorLo__pureZhashes_u80(T1_, 16952864883938283885ULL);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	result = ((NI) (T2_));
	}BeforeRet_: ;
	return result;
}
static N_INLINE(NI, hash__pureZhashes_u131)(NI x_p0) {
	NI result;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NI)0;
	result = hashWangYi1__pureZhashes_u139(((NU64) (x_p0)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(NI, hash__pureZhashes_u127)(void* x_p0) {
	NI result;
	NI y_1;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NI)0;
	y_1 = ((NI) (ptrdiff_t) (x_p0));
	result = hash__pureZhashes_u131(y_1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(NI, rawGet__OOZsrcZcakesparkZvm_u6014)(tyObject_HashSet__uRDPJjNr9aUE7hkP9bBkE4iw t_p0, void* key_p1, NI* hc_p2) {
	NI result;
	NI T1_;
	NI h_1;
	NI T11_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NI)0;
	T1_ = (NI)0;
	T1_ = hash__pureZhashes_u127(key_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	(*hc_p2) = T1_;
	{
		if (!((*hc_p2) == ((NI)0))) goto LA4_;
		(*hc_p2) = ((NI)314159265);
	}
LA4_: ;
	{
		NI T8_;
		T8_ = t_p0.data.len;
		if (!(T8_ == ((NI)0))) goto LA9_;
		result = ((NI)-1);
		goto BeforeRet_;
	}
LA9_: ;
	T11_ = (t_p0.data.len-1);
	h_1 = (NI)((*hc_p2) & T11_);
	{
		while (1) {
			NIM_BOOL T14_;
			NI T21_;
			T14_ = (NIM_BOOL)0;
			T14_ = isFilled__pureZcollectionsZsets_u39(t_p0.data.p->data[h_1].Field0);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			if (!T14_) goto LA13;
			{
				NIM_BOOL T17_;
				T17_ = (NIM_BOOL)0;
				T17_ = (t_p0.data.p->data[h_1].Field0 == (*hc_p2));
				if (!(T17_)) goto LA18_;
				T17_ = (t_p0.data.p->data[h_1].Field1 == key_p1);
LA18_: ;
				if (!T17_) goto LA19_;
				result = h_1;
				goto BeforeRet_;
			}
LA19_: ;
			T21_ = (t_p0.data.len-1);
			h_1 = nextTry__pureZcollectionsZsets_u42(h_1, T21_);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		} LA13: ;
	}
	result = (NI)(((NI)-1) - h_1);
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, contains__OOZsrcZcakesparkZvm_u6001)(tyObject_HashSet__uRDPJjNr9aUE7hkP9bBkE4iw s_p0, void* key_p1) {
	NIM_BOOL result;
	NI hc_1;
	NI index_1;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NIM_BOOL)0;
	hc_1 = (NI)0;
	index_1 = rawGet__OOZsrcZcakesparkZvm_u6014(s_p0, key_p1, (&hc_1));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	result = (((NI)0) <= index_1);
	}BeforeRet_: ;
	return result;
}
static N_INLINE(NIM_BOOL, mustRehash__OOZsrcZcakesparkZvm_u6474)(tyObject_HashSet__uRDPJjNr9aUE7hkP9bBkE4iw t_p0) {
	NIM_BOOL result;
	NIM_BOOL T1_;
	NI T2_;
	NI T4_;
	T1_ = (NIM_BOOL)0;
	T2_ = t_p0.data.len;
	T1_ = (T2_ < (NI)(t_p0.counter + (NI)(t_p0.counter / ((NI)2))));
	if (T1_) goto LA3_;
	T4_ = t_p0.data.len;
	T1_ = ((NI)(T4_ - t_p0.counter) < ((NI)4));
LA3_: ;
	result = T1_;
	return result;
}
static N_INLINE(NI, rawGetKnownHC__OOZsrcZcakesparkZvm_u6889)(tyObject_HashSet__uRDPJjNr9aUE7hkP9bBkE4iw t_p0, void* key_p1, NI hc_p2) {
	NI result;
	NI h_1;
	NI T6_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NI)0;
	{
		NI T3_;
		T3_ = t_p0.data.len;
		if (!(T3_ == ((NI)0))) goto LA4_;
		result = ((NI)-1);
		goto BeforeRet_;
	}
LA4_: ;
	T6_ = (t_p0.data.len-1);
	h_1 = (NI)(hc_p2 & T6_);
	{
		while (1) {
			NIM_BOOL T9_;
			NI T16_;
			T9_ = (NIM_BOOL)0;
			T9_ = isFilled__pureZcollectionsZsets_u39(t_p0.data.p->data[h_1].Field0);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			if (!T9_) goto LA8;
			{
				NIM_BOOL T12_;
				T12_ = (NIM_BOOL)0;
				T12_ = (t_p0.data.p->data[h_1].Field0 == hc_p2);
				if (!(T12_)) goto LA13_;
				T12_ = (t_p0.data.p->data[h_1].Field1 == key_p1);
LA13_: ;
				if (!T12_) goto LA14_;
				result = h_1;
				goto BeforeRet_;
			}
LA14_: ;
			T16_ = (t_p0.data.len-1);
			h_1 = nextTry__pureZcollectionsZsets_u42(h_1, T16_);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		} LA8: ;
	}
	result = (NI)(((NI)-1) - h_1);
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, rawInsert__OOZsrcZcakesparkZvm_u7227)(tyObject_HashSet__uRDPJjNr9aUE7hkP9bBkE4iw* s_p0, tySequence__quaCA0ePcBRCWYW74nGaBg* data_p1, void* key_p2, NI hc_p3, NI h_p4) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	{
		NI T3_;
		NI correctSizeX60gensym108__1;
		T3_ = (*data_p1).len;
		if (!(T3_ == ((NI)0))) goto LA4_;
		correctSizeX60gensym108__1 = slotsNeeded__pureZcollectionsZsets_u50(((NI)64));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		(*s_p0).counter = ((NI)0);
		newSeq__OOZsrcZcakesparkZvm_u6447((&(*s_p0).data), (correctSizeX60gensym108__1));
	}
LA4_: ;
	(*data_p1).p->data[h_p4].Field1 = key_p2;
	(*data_p1).p->data[h_p4].Field0 = hc_p3;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZsrcZcakesparkZvm_u6263)(tySequence__quaCA0ePcBRCWYW74nGaBg dest_p0) {
	if (dest_p0.p && !(dest_p0.p->cap & NIM_STRLIT_FLAG)) {
 alignedDealloc(dest_p0.p, NIM_ALIGNOF(tyTuple__ZohvDPoCSAbtu9bkFpQg1yQ));
}
}
N_LIB_PRIVATE N_NIMCALL(void, enlarge__OOZsrcZcakesparkZvm_u6654)(tyObject_HashSet__uRDPJjNr9aUE7hkP9bBkE4iw* s_p0) {
	tySequence__quaCA0ePcBRCWYW74nGaBg n_1;
	NI T1_;
	tySequence__quaCA0ePcBRCWYW74nGaBg T2_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	n_1.len = 0; n_1.p = NIM_NIL;
	T1_ = (*s_p0).data.len;
	newSeq__OOZsrcZcakesparkZvm_u6447((&n_1), ((NI)(T1_ * ((NI)2))));
	T2_.len = 0; T2_.p = NIM_NIL;
	T2_ = (*s_p0).data;
	(*s_p0).data = n_1;
	n_1 = T2_;
	{
		NI i_1;
		NI colontmp_;
		NI T4_;
		NI res_1;
		i_1 = (NI)0;
		colontmp_ = (NI)0;
		T4_ = (n_1.len-1);
		colontmp_ = T4_;
		res_1 = ((NI)0);
		{
			while (1) {
				if (!(res_1 <= colontmp_)) goto LA6;
				i_1 = ((NI) (res_1));
				{
					NIM_BOOL T9_;
					NI j_1;
					NI T12_;
					tyObject_HashSet__uRDPJjNr9aUE7hkP9bBkE4iw* T13_;
					T9_ = (NIM_BOOL)0;
					T9_ = isFilled__pureZcollectionsZsets_u39(n_1.p->data[i_1].Field0);
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
					if (!T9_) goto LA10_;
					T12_ = (NI)0;
					T12_ = rawGetKnownHC__OOZsrcZcakesparkZvm_u6889((*s_p0), n_1.p->data[i_1].Field1, n_1.p->data[i_1].Field0);
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
					j_1 = (NI)(((NI)-1) - T12_);
					T13_ = (tyObject_HashSet__uRDPJjNr9aUE7hkP9bBkE4iw*)0;
					T13_ = s_p0;
					rawInsert__OOZsrcZcakesparkZvm_u7227(T13_, (&(*s_p0).data), n_1.p->data[i_1].Field1, n_1.p->data[i_1].Field0, j_1);
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				}
LA10_: ;
				res_1 += ((NI)1);
			} LA6: ;
		}
	}
	eqdestroy___OOZsrcZcakesparkZvm_u6263(n_1);
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, incl__OOZsrcZcakesparkZvm_u6377)(tyObject_HashSet__uRDPJjNr9aUE7hkP9bBkE4iw* s_p0, void* key_p1) {
	NI hc_1;
	NI index_1;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	{
		NI T3_;
		NI correctSizeX60gensym101__1;
		T3_ = (*s_p0).data.len;
		if (!(T3_ == ((NI)0))) goto LA4_;
		correctSizeX60gensym101__1 = slotsNeeded__pureZcollectionsZsets_u50(((NI)64));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		(*s_p0).counter = ((NI)0);
		newSeq__OOZsrcZcakesparkZvm_u6447((&(*s_p0).data), (correctSizeX60gensym101__1));
	}
LA4_: ;
	hc_1 = (NI)0;
	index_1 = rawGet__OOZsrcZcakesparkZvm_u6014((*s_p0), key_p1, (&hc_1));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	{
		tyObject_HashSet__uRDPJjNr9aUE7hkP9bBkE4iw* T15_;
		if (!(index_1 < ((NI)0))) goto LA8_;
		{
			NIM_BOOL T12_;
			T12_ = (NIM_BOOL)0;
			T12_ = mustRehash__OOZsrcZcakesparkZvm_u6474((*s_p0));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			if (!T12_) goto LA13_;
			enlarge__OOZsrcZcakesparkZvm_u6654(s_p0);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			index_1 = rawGetKnownHC__OOZsrcZcakesparkZvm_u6889((*s_p0), key_p1, hc_1);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		}
LA13_: ;
		T15_ = (tyObject_HashSet__uRDPJjNr9aUE7hkP9bBkE4iw*)0;
		T15_ = s_p0;
		rawInsert__OOZsrcZcakesparkZvm_u7227(T15_, (&(*s_p0).data), key_p1, hc_1, (NI)(((NI)-1) - index_1));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		(*s_p0).counter += ((NI)1);
	}
LA8_: ;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZsrcZcakesparkZvm_u7507)(tyObject_HashSet__uRDPJjNr9aUE7hkP9bBkE4iw* dest_p0) {
	eqdestroy___OOZsrcZcakesparkZvm_u6263((*dest_p0).data);
}
