/* Generated by Nim Compiler v2.2.4 */
#define NIM_INTBITS 32
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_CompiledProgram__rw4x9birAJsXbFMKqoyp47w tyObject_CompiledProgram__rw4x9birAJsXbFMKqoyp47w;
typedef struct tySequence__tjkxNOQY9cAdAh85u9cULN9cg tySequence__tjkxNOQY9cAdAh85u9cULN9cg;
typedef struct tySequence__tjkxNOQY9cAdAh85u9cULN9cg_Content tySequence__tjkxNOQY9cAdAh85u9cULN9cg_Content;
typedef struct tySequence__QSd3I0juamqA6Vj3d6tVAw tySequence__QSd3I0juamqA6Vj3d6tVAw;
typedef struct tySequence__QSd3I0juamqA6Vj3d6tVAw_Content tySequence__QSd3I0juamqA6Vj3d6tVAw_Content;
typedef struct tySequence__VzYciN2QHKRysZohdHS9bgw tySequence__VzYciN2QHKRysZohdHS9bgw;
typedef struct tySequence__VzYciN2QHKRysZohdHS9bgw_Content tySequence__VzYciN2QHKRysZohdHS9bgw_Content;
typedef struct tyObject_Parser__iOukjnlUf9c9a0vyKIU4XynQ tyObject_Parser__iOukjnlUf9c9a0vyKIU4XynQ;
typedef struct tyObject_Program__7LL60BpG6odUxCMYHCaVhw tyObject_Program__7LL60BpG6odUxCMYHCaVhw;
typedef struct tySequence__tO9ahoJNmPfPIpzora9aH4ww tySequence__tO9ahoJNmPfPIpzora9aH4ww;
typedef struct tySequence__tO9ahoJNmPfPIpzora9aH4ww_Content tySequence__tO9ahoJNmPfPIpzora9aH4ww_Content;
typedef struct tyObject_Instruction__XTstQEb9co2NNRaKJBBih9ag tyObject_Instruction__XTstQEb9co2NNRaKJBBih9ag;
typedef struct tySequence__WsDlUegMKP5qbZfDE7UOgg tySequence__WsDlUegMKP5qbZfDE7UOgg;
typedef struct tySequence__WsDlUegMKP5qbZfDE7UOgg_Content tySequence__WsDlUegMKP5qbZfDE7UOgg_Content;
typedef struct tyObject_Condition__pS6iJoNrp0lYt3mVF9cXsPQ tyObject_Condition__pS6iJoNrp0lYt3mVF9cXsPQ;
typedef struct tyObject_Arg__E9boIsLlAjypGlVaV0b9crIA tyObject_Arg__E9boIsLlAjypGlVaV0b9crIA;
typedef struct tySequence__blakBku9aKYZtnss5hJNT1Q tySequence__blakBku9aKYZtnss5hJNT1Q;
typedef struct tySequence__blakBku9aKYZtnss5hJNT1Q_Content tySequence__blakBku9aKYZtnss5hJNT1Q_Content;
typedef struct tySequence__B5XQ2QsS79aU7kZkd2Wo9ckQ tySequence__B5XQ2QsS79aU7kZkd2Wo9ckQ;
typedef struct tySequence__B5XQ2QsS79aU7kZkd2Wo9ckQ_Content tySequence__B5XQ2QsS79aU7kZkd2Wo9ckQ_Content;
typedef struct tyTuple__C9b9afwUTvJA9cIgAGy6KA9bmA tyTuple__C9b9afwUTvJA9cIgAGy6KA9bmA;
typedef struct tyObject_Token__XMUvAnG8QGMP6D5ftbHFhw tyObject_Token__XMUvAnG8QGMP6D5ftbHFhw;
typedef struct tyObject_AstNodeObj__HBgFPT0e3KpAWJqAorX4Qg tyObject_AstNodeObj__HBgFPT0e3KpAWJqAorX4Qg;
typedef struct tyObject_ResolvedArg__N9brVylJks69a9bZnI4zt9bmYQ tyObject_ResolvedArg__N9brVylJks69a9bZnI4zt9bmYQ;
typedef struct tyObject_StringPart__HKwvF6B260acLKHOHlpVRQ tyObject_StringPart__HKwvF6B260acLKHOHlpVRQ;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
struct tySequence__tjkxNOQY9cAdAh85u9cULN9cg {
  NI len; tySequence__tjkxNOQY9cAdAh85u9cULN9cg_Content* p;
};
struct tySequence__QSd3I0juamqA6Vj3d6tVAw {
  NI len; tySequence__QSd3I0juamqA6Vj3d6tVAw_Content* p;
};
struct tyObject_CompiledProgram__rw4x9birAJsXbFMKqoyp47w {
	tySequence__tjkxNOQY9cAdAh85u9cULN9cg instructions;
	tySequence__QSd3I0juamqA6Vj3d6tVAw blocks;
	NIM_BOOL hasError;
	NimStringV2 errorMsg;
};
struct tySequence__VzYciN2QHKRysZohdHS9bgw {
  NI len; tySequence__VzYciN2QHKRysZohdHS9bgw_Content* p;
};
struct tyObject_Parser__iOukjnlUf9c9a0vyKIU4XynQ {
	tySequence__VzYciN2QHKRysZohdHS9bgw tokens;
	NI pos;
	NIM_BOOL hasError;
	NimStringV2 errorMsg;
	NI errorLine;
	NI errorCol;
};
struct tySequence__tO9ahoJNmPfPIpzora9aH4ww {
  NI len; tySequence__tO9ahoJNmPfPIpzora9aH4ww_Content* p;
};
struct tyObject_Program__7LL60BpG6odUxCMYHCaVhw {
	tySequence__tO9ahoJNmPfPIpzora9aH4ww statements;
	tySequence__tO9ahoJNmPfPIpzora9aH4ww blockDefs;
};
typedef NU8 tyEnum_InstrKind__rQo514xDUpHi9bK2iBT5E9bw;
struct tySequence__WsDlUegMKP5qbZfDE7UOgg {
  NI len; tySequence__WsDlUegMKP5qbZfDE7UOgg_Content* p;
};
typedef NU8 tyEnum_ArgKind__cRc9crps0ZqW7m703wzDXLQ;
struct tySequence__blakBku9aKYZtnss5hJNT1Q {
  NI len; tySequence__blakBku9aKYZtnss5hJNT1Q_Content* p;
};
struct tySequence__B5XQ2QsS79aU7kZkd2Wo9ckQ {
  NI len; tySequence__B5XQ2QsS79aU7kZkd2Wo9ckQ_Content* p;
};
struct tyObject_Arg__E9boIsLlAjypGlVaV0b9crIA {
	NI line;
	NI col;
	tyEnum_ArgKind__cRc9crps0ZqW7m703wzDXLQ kind;
union{
	struct {
	NI32 intVal;
} _kind_1;
	struct {
	NF floatVal;
} _kind_2;
	struct {
	tySequence__blakBku9aKYZtnss5hJNT1Q strParts;
} _kind_3;
	struct {
	NimStringV2 identName;
} _kind_4;
	struct {
	tySequence__B5XQ2QsS79aU7kZkd2Wo9ckQ arrayElems;
} _kind_5;
};
};
typedef NU8 tyEnum_TokenType__KSIs0B9bnT5A3drOf5JgESQ;
struct tyObject_Condition__pS6iJoNrp0lYt3mVF9cXsPQ {
	tyObject_Arg__E9boIsLlAjypGlVaV0b9crIA left;
	tyEnum_TokenType__KSIs0B9bnT5A3drOf5JgESQ op;
	tyObject_Arg__E9boIsLlAjypGlVaV0b9crIA right;
};
struct tyObject_Instruction__XTstQEb9co2NNRaKJBBih9ag {
	tyEnum_InstrKind__rQo514xDUpHi9bK2iBT5E9bw kind;
	NI line;
	NI col;
	NimStringV2 funcName;
	NIM_BOOL isMethod;
	NimStringV2 peripheral;
	NimStringV2 methodName;
	tySequence__WsDlUegMKP5qbZfDE7UOgg args;
	NimStringV2 destVar;
	NimStringV2 destPeripheral;
	NimStringV2 destProperty;
	NIM_BOOL hasDest;
	tyObject_Condition__pS6iJoNrp0lYt3mVF9cXsPQ condition;
	NI jumpTarget;
	NI loopEndIp;
	NimStringV2 countName;
	NI32 countVal;
	NimStringV2 arrayName;
	tySequence__WsDlUegMKP5qbZfDE7UOgg arrayLit;
	NimStringV2 itemVar;
	NimStringV2 blockName;
};
struct tySequence__tjkxNOQY9cAdAh85u9cULN9cg_Content { NI cap; tyObject_Instruction__XTstQEb9co2NNRaKJBBih9ag data[SEQ_DECL_SIZE]; };
struct tyTuple__C9b9afwUTvJA9cIgAGy6KA9bmA {
	NimStringV2 Field0;
	tySequence__tjkxNOQY9cAdAh85u9cULN9cg Field1;
};
struct tySequence__QSd3I0juamqA6Vj3d6tVAw_Content { NI cap; tyTuple__C9b9afwUTvJA9cIgAGy6KA9bmA data[SEQ_DECL_SIZE]; };
struct tyObject_Token__XMUvAnG8QGMP6D5ftbHFhw {
	tyEnum_TokenType__KSIs0B9bnT5A3drOf5JgESQ typ;
	NimStringV2 lexeme;
	NI line;
	NI col;
	NI32 intVal;
	NF floatVal;
	tySequence__blakBku9aKYZtnss5hJNT1Q strParts;
};
struct tySequence__VzYciN2QHKRysZohdHS9bgw_Content { NI cap; tyObject_Token__XMUvAnG8QGMP6D5ftbHFhw data[SEQ_DECL_SIZE]; };
struct tySequence__tO9ahoJNmPfPIpzora9aH4ww_Content { NI cap; tyObject_AstNodeObj__HBgFPT0e3KpAWJqAorX4Qg* data[SEQ_DECL_SIZE]; };
typedef NU8 tyEnum_ResolvedArgKind__rOyDWs6RUOZGhPFyds3edw;
struct tyObject_ResolvedArg__N9brVylJks69a9bZnI4zt9bmYQ {
	tyEnum_ResolvedArgKind__rOyDWs6RUOZGhPFyds3edw kind;
union{
	struct {
	NI32 intVal;
} _kind_1;
	struct {
	NF floatVal;
} _kind_2;
	struct {
	tySequence__blakBku9aKYZtnss5hJNT1Q strParts;
} _kind_3;
	struct {
	NimStringV2 varName;
} _kind_4;
	struct {
	tySequence__WsDlUegMKP5qbZfDE7UOgg elements;
} _kind_5;
};
};
struct tySequence__WsDlUegMKP5qbZfDE7UOgg_Content { NI cap; tyObject_ResolvedArg__N9brVylJks69a9bZnI4zt9bmYQ data[SEQ_DECL_SIZE]; };
struct tyObject_StringPart__HKwvF6B260acLKHOHlpVRQ {
	NIM_BOOL isInterp;
union{
	struct {
	NimStringV2 lit;
} _isInterp_1;
	struct {
	NimStringV2 varName;
} _isInterp_2;
};
};
struct tySequence__blakBku9aKYZtnss5hJNT1Q_Content { NI cap; tyObject_StringPart__HKwvF6B260acLKHOHlpVRQ data[SEQ_DECL_SIZE]; };
struct tySequence__B5XQ2QsS79aU7kZkd2Wo9ckQ_Content { NI cap; tyObject_Arg__E9boIsLlAjypGlVaV0b9crIA data[SEQ_DECL_SIZE]; };
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1);
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(tySequence__VzYciN2QHKRysZohdHS9bgw, tokenize__OOZsrcZcakesparkZlexer_u2170)(NimStringV2 source_p0);
N_LIB_PRIVATE N_NIMCALL(void, newParser__OOZsrcZcakesparkZparser_u85)(tySequence__VzYciN2QHKRysZohdHS9bgw tokens_p0, tyObject_Parser__iOukjnlUf9c9a0vyKIU4XynQ* Result);
N_LIB_PRIVATE N_NIMCALL(tyObject_Program__7LL60BpG6odUxCMYHCaVhw, parse__OOZsrcZcakesparkZparser_u1401)(tyObject_Parser__iOukjnlUf9c9a0vyKIU4XynQ* p_p0);
N_LIB_PRIVATE N_NIMCALL(void, compile__OOZsrcZcakesparkZcompiler_u2478)(tyObject_Program__7LL60BpG6odUxCMYHCaVhw program_p0, tyObject_CompiledProgram__rw4x9birAJsXbFMKqoyp47w* Result);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZsrcZcakesparkZparser_u1407)(tyObject_Program__7LL60BpG6odUxCMYHCaVhw* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZsrcZcakesparkZparser_u207)(tyObject_Parser__iOukjnlUf9c9a0vyKIU4XynQ* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZsrcZcakesparkZparser_u91)(tySequence__VzYciN2QHKRysZohdHS9bgw dest_p0);
extern NIM_BOOL nimInErrorMode__system_u3521;
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a_p0, v_p1, ((size_t) (size_p2)));
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u3521);
	return result;
}
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimSetMem__systemZmemory_u7(p_p0, ((int)0), size_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, compileSource__OOZsrcZcakesparkZcakespark_u6)(NimStringV2 source_p0, tyObject_CompiledProgram__rw4x9birAJsXbFMKqoyp47w* Result) {
	tySequence__VzYciN2QHKRysZohdHS9bgw tokens_1;
	tyObject_Parser__iOukjnlUf9c9a0vyKIU4XynQ parser_1;
	tyObject_Program__7LL60BpG6odUxCMYHCaVhw program_1;
NIM_BOOL oldNimErrFin1_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)Result, sizeof(tyObject_CompiledProgram__rw4x9birAJsXbFMKqoyp47w));
	tokens_1.len = 0; tokens_1.p = NIM_NIL;
	nimZeroMem((void*)(&parser_1), sizeof(tyObject_Parser__iOukjnlUf9c9a0vyKIU4XynQ));
	nimZeroMem((void*)(&program_1), sizeof(tyObject_Program__7LL60BpG6odUxCMYHCaVhw));
	tokens_1 = tokenize__OOZsrcZcakesparkZlexer_u2170(source_p0);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	newParser__OOZsrcZcakesparkZparser_u85(tokens_1, (&parser_1));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	program_1 = parse__OOZsrcZcakesparkZparser_u1401((&parser_1));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	compile__OOZsrcZcakesparkZcompiler_u2478(program_1, Result);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	{
		LA1_:;
	}
	{
		oldNimErrFin1_ = *nimErr_; *nimErr_ = NIM_FALSE;
		eqdestroy___OOZsrcZcakesparkZparser_u1407((&program_1));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		eqdestroy___OOZsrcZcakesparkZparser_u207((&parser_1));
		eqdestroy___OOZsrcZcakesparkZparser_u91(tokens_1);
		*nimErr_ = oldNimErrFin1_;
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
