/* Generated by Nim Compiler v2.2.4 */
#define NIM_INTBITS 32
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_ValueError__mQsiQ1j8tnHjEYMpj2vv8Q tyObject_ValueError__mQsiQ1j8tnHjEYMpj2vv8Q;
typedef struct tyObject_CatchableError__9ab9cPq83jNmwEkPYefdrBpg tyObject_CatchableError__9ab9cPq83jNmwEkPYefdrBpg;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct TNimTypeV2 TNimTypeV2;
typedef struct tySequence__lQ1UsDGK2GVVm9bDjc3VrPQ tySequence__lQ1UsDGK2GVVm9bDjc3VrPQ;
typedef struct tySequence__lQ1UsDGK2GVVm9bDjc3VrPQ_Content tySequence__lQ1UsDGK2GVVm9bDjc3VrPQ_Content;
typedef struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ tySequence__sM4lkSb7zS6F7OVMvW9cffQ;
typedef struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content;
typedef struct tyObject_StackTraceEntry__Ys9cmA3ckZAVfrZgZt9axXEw tyObject_StackTraceEntry__Ys9cmA3ckZAVfrZgZt9axXEw;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
struct TNimTypeV2 {
	void* destructor;
	NI size;
	NI16 align;
	NI16 depth;
	NU32* display;
	void* traceImpl;
	void* typeInfoV1;
	NI flags;
	void* vTable[SEQ_DECL_SIZE];
};
struct RootObj {
	TNimTypeV2* m_type;
};
struct tySequence__lQ1UsDGK2GVVm9bDjc3VrPQ {
  NI len; tySequence__lQ1UsDGK2GVVm9bDjc3VrPQ_Content* p;
};
struct Exception {
	RootObj Sup;
	Exception* parent;
	NCSTRING name;
	NimStringV2 message;
	tySequence__lQ1UsDGK2GVVm9bDjc3VrPQ trace;
	Exception* up;
};
struct tyObject_CatchableError__9ab9cPq83jNmwEkPYefdrBpg {
	Exception Sup;
};
struct tyObject_ValueError__mQsiQ1j8tnHjEYMpj2vv8Q {
	tyObject_CatchableError__9ab9cPq83jNmwEkPYefdrBpg Sup;
};
typedef NI tyArray__9cc9aPiDa8VaWjVcFLabEDZQ[256];
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ {
  NI len; tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content* p;
};
typedef NU8 tySet_tyChar__nmiMWKVIe46vacnhAFrQvw[32];
typedef NU8 tyEnum_InstrKind__rQo514xDUpHi9bK2iBT5E9bw;
struct tyObject_StackTraceEntry__Ys9cmA3ckZAVfrZgZt9axXEw {
	NCSTRING procname;
	NI line;
	NCSTRING filename;
};
struct tySequence__lQ1UsDGK2GVVm9bDjc3VrPQ_Content { NI cap; tyObject_StackTraceEntry__Ys9cmA3ckZAVfrZgZt9axXEw data[SEQ_DECL_SIZE]; };
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content { NI cap; NimStringV2 data[SEQ_DECL_SIZE]; };
N_NIMCALL(NimStringV2, rawNewString)(NI cap_p0);
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1);
static N_INLINE(void, copyMem__system_u1731)(void* dest_p0, void* source_p1, NI size_p2);
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(void, prepareAdd)(NimStringV2* s_p0, NI addLen_p1);
N_LIB_PRIVATE N_NIMCALL(NI, parseFloat__pureZparseutils_u985)(NimStringV2 s_p0, NF* number_p1, NI start_p2);
N_LIB_PRIVATE N_NIMCALL(void*, nimNewObj)(NI size_p0, NI alignment_p1);
N_LIB_PRIVATE N_NIMCALL(void, raiseExceptionEx)(Exception* e_p0, NCSTRING ename_p1, NCSTRING procname_p2, NCSTRING filename_p3, NI line_p4);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(NI, parseBiggestInt__pureZparseutils_u955)(NimStringV2 s_p0, NI64* number_p1, NI start_p2);
N_LIB_PRIVATE N_NIMCALL(NI, nsuFindChar)(NimStringV2 s_p0, NIM_CHAR sub_p1, NI start_p2, NI last_p3);
static N_INLINE(NI, minuspercent___system_u813)(NI x_p0, NI y_p1);
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringV2 s_p0);
N_LIB_PRIVATE N_NIMCALL(NI, nsuFindStrA)(tyArray__9cc9aPiDa8VaWjVcFLabEDZQ a_p0, NimStringV2 s_p1, NimStringV2 sub_p2, NI start_p3, NI last_p4);
N_LIB_PRIVATE N_NIMCALL(void, nsuInitNewSkipTable)(NimStringV2 sub_p0, tyArray__9cc9aPiDa8VaWjVcFLabEDZQ Result);
N_LIB_PRIVATE N_NIMCALL(void, nsuInitSkipTable)(NI* a_p0, NimStringV2 sub_p1);
N_LIB_PRIVATE N_NIMCALL(void, fill__pureZstrutils_u1563)(NI* a_p0, NI a_p0Len_0, NI value_p1);
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1);
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(void*, newSeqPayload)(NI cap_p0, NI elemSize_p1, NI elemAlign_p2);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, substrEq__pureZstrutils_u255)(NimStringV2 s_p0, NI pos_p1, NimStringV2 substr_p2);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___system_u2616)(NimStringV2* dest_p0, NimStringV2 src_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, substr__system_u6073)(NimStringV2 s_p0, NI first_p1, NI last_p2);
N_LIB_PRIVATE N_NIMCALL(void, add__stdZenumutils_u70)(tySequence__sM4lkSb7zS6F7OVMvW9cffQ* x_p0, NimStringV2 y_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___system_u2607)(NimStringV2* dest_p0);
N_LIB_PRIVATE N_NOCONV(void, dealloc)(void* p_p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, toHexImpl__pureZstrutils_u773)(NU64 x_p0, NI len_p1, NIM_BOOL handleNegative_p2);
N_NIMCALL(NimStringV2, mnewString)(NI len_p0);
static N_INLINE(void, nimPrepareStrMutationV2)(NimStringV2* s_p0);
N_LIB_PRIVATE N_NIMCALL(void, nimPrepareStrMutationImpl__system_u2373)(NimStringV2* s_p0);
N_LIB_PRIVATE N_NIMCALL(NI, nsuFindCharSet)(NimStringV2 s_p0, tySet_tyChar__nmiMWKVIe46vacnhAFrQvw chars_p1, NI start_p2, NI last_p3);
N_LIB_PRIVATE N_NIMCALL(void, nsuAddf)(NimStringV2* s_p0, NimStringV2 formatstr_p1, NimStringV2* a_p2, NI a_p2Len_0);
N_LIB_PRIVATE N_NOINLINE(void, invalidFormatString__pureZstrutils_u2496)(NimStringV2 formatstr_p0);
static N_INLINE(void, nimAddCharV1)(NimStringV2* s_p0, NIM_CHAR c_p1);
N_LIB_PRIVATE N_NIMCALL(NI, findNormalized__pureZstrutils_u2483)(NimStringV2 x_p0, NimStringV2* inArray_p1, NI inArray_p1Len_0);
N_LIB_PRIVATE N_NIMCALL(NI, nsuCmpIgnoreStyle)(NimStringV2 a_p0, NimStringV2 b_p1);
static N_INLINE(NIM_CHAR, toLowerAscii__stdZprivateZstrimpl_u1)(NIM_CHAR c_p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nimIdentNormalize__pureZstrutils_u122)(NimStringV2 s_p0);
N_LIB_PRIVATE N_NIMCALL(void, setLengthStrV2)(NimStringV2* s_p0, NI newLen_p1);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringV2 a_p0, NimStringV2 b_p1);
static N_INLINE(NIM_BOOL, equalMem__system_u1739)(void* a_p0, void* b_p1, NI size_p2);
static N_INLINE(int, nimCmpMem)(void* a_p0, void* b_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(NI, hashString)(NimStringV2 s_p0);
static const struct {
  NI cap; NIM_CHAR data[0+1];
} TM__JGc9b9bh2D3nTdUR7TGyq8aA_2 = { 0 | NIM_STRLIT_FLAG, "" };
static const NimStringV2 TM__JGc9b9bh2D3nTdUR7TGyq8aA_3 = {0, (NimStrPayload*)&TM__JGc9b9bh2D3nTdUR7TGyq8aA_2};
extern TNimTypeV2 NTIv2__mQsiQ1j8tnHjEYMpj2vv8Q_;
static const struct {
  NI cap; NIM_CHAR data[15+1];
} TM__JGc9b9bh2D3nTdUR7TGyq8aA_4 = { 15 | NIM_STRLIT_FLAG, "invalid float: " };
static const NimStringV2 TM__JGc9b9bh2D3nTdUR7TGyq8aA_5 = {15, (NimStrPayload*)&TM__JGc9b9bh2D3nTdUR7TGyq8aA_4};
static const struct {
  NI cap; NIM_CHAR data[17+1];
} TM__JGc9b9bh2D3nTdUR7TGyq8aA_6 = { 17 | NIM_STRLIT_FLAG, "invalid integer: " };
static const NimStringV2 TM__JGc9b9bh2D3nTdUR7TGyq8aA_7 = {17, (NimStrPayload*)&TM__JGc9b9bh2D3nTdUR7TGyq8aA_6};
static const struct {
  NI cap; NIM_CHAR data[16+1];
} TM__JGc9b9bh2D3nTdUR7TGyq8aA_8 = { 16 | NIM_STRLIT_FLAG, "0123456789ABCDEF" };
static const NimStringV2 TM__JGc9b9bh2D3nTdUR7TGyq8aA_9 = {16, (NimStrPayload*)&TM__JGc9b9bh2D3nTdUR7TGyq8aA_8};
static const struct {
  NI cap; NIM_CHAR data[23+1];
} TM__JGc9b9bh2D3nTdUR7TGyq8aA_10 = { 23 | NIM_STRLIT_FLAG, "invalid format string: " };
static const NimStringV2 TM__JGc9b9bh2D3nTdUR7TGyq8aA_11 = {23, (NimStrPayload*)&TM__JGc9b9bh2D3nTdUR7TGyq8aA_10};
static const struct {
  NI cap; NIM_CHAR data[7+1];
} TM__JGc9b9bh2D3nTdUR7TGyq8aA_12 = { 7 | NIM_STRLIT_FLAG, "inkcall" };
static const NimStringV2 TM__JGc9b9bh2D3nTdUR7TGyq8aA_13 = {7, (NimStrPayload*)&TM__JGc9b9bh2D3nTdUR7TGyq8aA_12};
static const struct {
  NI cap; NIM_CHAR data[5+1];
} TM__JGc9b9bh2D3nTdUR7TGyq8aA_14 = { 5 | NIM_STRLIT_FLAG, "inkif" };
static const NimStringV2 TM__JGc9b9bh2D3nTdUR7TGyq8aA_15 = {5, (NimStrPayload*)&TM__JGc9b9bh2D3nTdUR7TGyq8aA_14};
static const struct {
  NI cap; NIM_CHAR data[7+1];
} TM__JGc9b9bh2D3nTdUR7TGyq8aA_16 = { 7 | NIM_STRLIT_FLAG, "inkelse" };
static const NimStringV2 TM__JGc9b9bh2D3nTdUR7TGyq8aA_17 = {7, (NimStrPayload*)&TM__JGc9b9bh2D3nTdUR7TGyq8aA_16};
static const struct {
  NI cap; NIM_CHAR data[6+1];
} TM__JGc9b9bh2D3nTdUR7TGyq8aA_18 = { 6 | NIM_STRLIT_FLAG, "inkend" };
static const NimStringV2 TM__JGc9b9bh2D3nTdUR7TGyq8aA_19 = {6, (NimStrPayload*)&TM__JGc9b9bh2D3nTdUR7TGyq8aA_18};
static const struct {
  NI cap; NIM_CHAR data[8+1];
} TM__JGc9b9bh2D3nTdUR7TGyq8aA_20 = { 8 | NIM_STRLIT_FLAG, "inkwhile" };
static const NimStringV2 TM__JGc9b9bh2D3nTdUR7TGyq8aA_21 = {8, (NimStrPayload*)&TM__JGc9b9bh2D3nTdUR7TGyq8aA_20};
static const struct {
  NI cap; NIM_CHAR data[11+1];
} TM__JGc9b9bh2D3nTdUR7TGyq8aA_22 = { 11 | NIM_STRLIT_FLAG, "inkendwhile" };
static const NimStringV2 TM__JGc9b9bh2D3nTdUR7TGyq8aA_23 = {11, (NimStrPayload*)&TM__JGc9b9bh2D3nTdUR7TGyq8aA_22};
static const struct {
  NI cap; NIM_CHAR data[7+1];
} TM__JGc9b9bh2D3nTdUR7TGyq8aA_24 = { 7 | NIM_STRLIT_FLAG, "inkloop" };
static const NimStringV2 TM__JGc9b9bh2D3nTdUR7TGyq8aA_25 = {7, (NimStrPayload*)&TM__JGc9b9bh2D3nTdUR7TGyq8aA_24};
static const struct {
  NI cap; NIM_CHAR data[10+1];
} TM__JGc9b9bh2D3nTdUR7TGyq8aA_26 = { 10 | NIM_STRLIT_FLAG, "inkendloop" };
static const NimStringV2 TM__JGc9b9bh2D3nTdUR7TGyq8aA_27 = {10, (NimStrPayload*)&TM__JGc9b9bh2D3nTdUR7TGyq8aA_26};
static const struct {
  NI cap; NIM_CHAR data[7+1];
} TM__JGc9b9bh2D3nTdUR7TGyq8aA_28 = { 7 | NIM_STRLIT_FLAG, "inkeach" };
static const NimStringV2 TM__JGc9b9bh2D3nTdUR7TGyq8aA_29 = {7, (NimStrPayload*)&TM__JGc9b9bh2D3nTdUR7TGyq8aA_28};
static const struct {
  NI cap; NIM_CHAR data[10+1];
} TM__JGc9b9bh2D3nTdUR7TGyq8aA_30 = { 10 | NIM_STRLIT_FLAG, "inkendeach" };
static const NimStringV2 TM__JGc9b9bh2D3nTdUR7TGyq8aA_31 = {10, (NimStrPayload*)&TM__JGc9b9bh2D3nTdUR7TGyq8aA_30};
static const struct {
  NI cap; NIM_CHAR data[12+1];
} TM__JGc9b9bh2D3nTdUR7TGyq8aA_32 = { 12 | NIM_STRLIT_FLAG, "inkcallblock" };
static const NimStringV2 TM__JGc9b9bh2D3nTdUR7TGyq8aA_33 = {12, (NimStrPayload*)&TM__JGc9b9bh2D3nTdUR7TGyq8aA_32};
static const struct {
  NI cap; NIM_CHAR data[9+1];
} TM__JGc9b9bh2D3nTdUR7TGyq8aA_34 = { 9 | NIM_STRLIT_FLAG, "inkreturn" };
static const NimStringV2 TM__JGc9b9bh2D3nTdUR7TGyq8aA_35 = {9, (NimStrPayload*)&TM__JGc9b9bh2D3nTdUR7TGyq8aA_34};
static const struct {
  NI cap; NIM_CHAR data[8+1];
} TM__JGc9b9bh2D3nTdUR7TGyq8aA_36 = { 8 | NIM_STRLIT_FLAG, "inkbreak" };
static const NimStringV2 TM__JGc9b9bh2D3nTdUR7TGyq8aA_37 = {8, (NimStrPayload*)&TM__JGc9b9bh2D3nTdUR7TGyq8aA_36};
static const struct {
  NI cap; NIM_CHAR data[11+1];
} TM__JGc9b9bh2D3nTdUR7TGyq8aA_38 = { 11 | NIM_STRLIT_FLAG, "inkcontinue" };
static const NimStringV2 TM__JGc9b9bh2D3nTdUR7TGyq8aA_39 = {11, (NimStrPayload*)&TM__JGc9b9bh2D3nTdUR7TGyq8aA_38};
static const struct {
  NI cap; NIM_CHAR data[12+1];
} TM__JGc9b9bh2D3nTdUR7TGyq8aA_40 = { 12 | NIM_STRLIT_FLAG, "inkscopepush" };
static const NimStringV2 TM__JGc9b9bh2D3nTdUR7TGyq8aA_41 = {12, (NimStrPayload*)&TM__JGc9b9bh2D3nTdUR7TGyq8aA_40};
static const struct {
  NI cap; NIM_CHAR data[11+1];
} TM__JGc9b9bh2D3nTdUR7TGyq8aA_42 = { 11 | NIM_STRLIT_FLAG, "inkscopepop" };
static const NimStringV2 TM__JGc9b9bh2D3nTdUR7TGyq8aA_43 = {11, (NimStrPayload*)&TM__JGc9b9bh2D3nTdUR7TGyq8aA_42};
static const struct {
  NI cap; NIM_CHAR data[11+1];
} TM__JGc9b9bh2D3nTdUR7TGyq8aA_44 = { 11 | NIM_STRLIT_FLAG, "inkpropread" };
static const NimStringV2 TM__JGc9b9bh2D3nTdUR7TGyq8aA_45 = {11, (NimStrPayload*)&TM__JGc9b9bh2D3nTdUR7TGyq8aA_44};
static const struct {
  NI cap; NIM_CHAR data[20+1];
} TM__JGc9b9bh2D3nTdUR7TGyq8aA_46 = { 20 | NIM_STRLIT_FLAG, "Invalid enum value: " };
static const NimStringV2 TM__JGc9b9bh2D3nTdUR7TGyq8aA_47 = {20, (NimStrPayload*)&TM__JGc9b9bh2D3nTdUR7TGyq8aA_46};
extern NIM_BOOL nimInErrorMode__system_u3521;
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, nsuEndsWith)(NimStringV2 s_p0, NimStringV2 suffix_p1) {
	NIM_BOOL result;
	NI suffixLenX60gensym142__1;
	NI sLenX60gensym142__1;
	NI iX60gensym142__1;
	NI jX60gensym142__1;
{	result = NIM_FALSE;
	suffixLenX60gensym142__1 = suffix_p1.len;
	sLenX60gensym142__1 = s_p0.len;
	iX60gensym142__1 = ((NI)0);
	jX60gensym142__1 = (NI)(sLenX60gensym142__1 - suffixLenX60gensym142__1);
	{
		while (1) {
			NIM_BOOL T3_;
			T3_ = (NIM_BOOL)0;
			T3_ = (((NI)0) <= (NI)(iX60gensym142__1 + jX60gensym142__1));
			if (!(T3_)) goto LA4_;
			T3_ = ((NI)(iX60gensym142__1 + jX60gensym142__1) < sLenX60gensym142__1);
LA4_: ;
			if (!T3_) goto LA2;
			{
				if (!!(((NU8)(s_p0.p->data[(NI)(iX60gensym142__1 + jX60gensym142__1)]) == (NU8)(suffix_p1.p->data[iX60gensym142__1])))) goto LA7_;
				result = NIM_FALSE;
				goto BeforeRet_;
			}
LA7_: ;
			iX60gensym142__1 += ((NI)1);
		} LA2: ;
	}
	{
		if (!(suffixLenX60gensym142__1 <= iX60gensym142__1)) goto LA11_;
		result = NIM_TRUE;
		goto BeforeRet_;
	}
LA11_: ;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest_p0, source_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, copyMem__system_u1731)(void* dest_p0, void* source_p1, NI size_p2) {
	nimCopyMem(dest_p0, source_p1, size_p2);
}
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1) {
	{
		if (!(((NI)0) < src_p1.len)) goto LA3_;
		copyMem__system_u1731(((void*) ((&(*(*dest_p0).p).data[(*dest_p0).len]))), ((void*) ((&(*src_p1.p).data[((NI)0)]))), (src_p1.len));
		(*dest_p0).len += src_p1.len;
		(*(*dest_p0).p).data[(*dest_p0).len] = 0;
	}
LA3_: ;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nsuJoinSep)(NimStringV2* a_p0, NI a_p0Len_0, NimStringV2 sep_p1) {
	NimStringV2 result;
	result.len = 0; result.p = NIM_NIL;
	{
		NI L_1;
		if (!(((NI)0) < a_p0Len_0)) goto LA3_;
		L_1 = (NI)(sep_p1.len * (NI)(a_p0Len_0 - ((NI)1)));
		{
			NI i_1;
			NI colontmp_;
			NI res_1;
			i_1 = (NI)0;
			colontmp_ = (NI)0;
			colontmp_ = (a_p0Len_0-1);
			res_1 = ((NI)0);
			{
				while (1) {
					if (!(res_1 <= colontmp_)) goto LA7;
					i_1 = ((NI) (res_1));
					L_1 += a_p0[i_1].len;
					res_1 += ((NI)1);
				} LA7: ;
			}
		}
		result = rawNewString((L_1));
		prepareAdd((&result), a_p0[((NI)0)].len + 0);
appendString((&result), a_p0[((NI)0)]);
		{
			NI i_2;
			NI colontmp__2;
			NI res_2;
			i_2 = (NI)0;
			colontmp__2 = (NI)0;
			colontmp__2 = (a_p0Len_0-1);
			res_2 = ((NI)1);
			{
				while (1) {
					if (!(res_2 <= colontmp__2)) goto LA10;
					i_2 = ((NI) (res_2));
					prepareAdd((&result), sep_p1.len + 0);
appendString((&result), sep_p1);
					prepareAdd((&result), a_p0[i_2].len + 0);
appendString((&result), a_p0[i_2]);
					res_2 += ((NI)1);
				} LA10: ;
			}
		}
	}
	goto LA1_;
LA3_: ;
	{
		result = TM__JGc9b9bh2D3nTdUR7TGyq8aA_3;
	}
LA1_: ;
	return result;
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u3521);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NF, nsuParseFloat)(NimStringV2 s_p0) {
	NF result;
	NI L_1;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = 0.0;
	L_1 = parseFloat__pureZparseutils_u985(s_p0, (&result), ((NI)0));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	{
		NIM_BOOL T3_;
		tyObject_ValueError__mQsiQ1j8tnHjEYMpj2vv8Q* T7_;
		NimStringV2 T8_;
		T3_ = (NIM_BOOL)0;
		T3_ = !((L_1 == s_p0.len));
		if (T3_) goto LA4_;
		T3_ = (L_1 == ((NI)0));
LA4_: ;
		if (!T3_) goto LA5_;
		T7_ = NIM_NIL;
		T7_ = (tyObject_ValueError__mQsiQ1j8tnHjEYMpj2vv8Q*) nimNewObj(sizeof(tyObject_ValueError__mQsiQ1j8tnHjEYMpj2vv8Q), NIM_ALIGNOF(tyObject_ValueError__mQsiQ1j8tnHjEYMpj2vv8Q));
		(*T7_).Sup.Sup.Sup.m_type = (&NTIv2__mQsiQ1j8tnHjEYMpj2vv8Q_);
		(*T7_).Sup.Sup.name = "ValueError";
		T8_.len = 0; T8_.p = NIM_NIL;
		T8_ = rawNewString(s_p0.len + 15);
appendString((&T8_), TM__JGc9b9bh2D3nTdUR7TGyq8aA_5);
appendString((&T8_), s_p0);
		(*T7_).Sup.Sup.message = T8_;
		(*T7_).Sup.Sup.parent = ((Exception*) NIM_NIL);
		raiseExceptionEx((Exception*)T7_, "ValueError", "parseFloat", "strutils.nim", 1201);
goto BeforeRet_;
	}
LA5_: ;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI64, nsuParseBiggestInt)(NimStringV2 s_p0) {
	NI64 result;
	NI L_1;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = IL64(0);
	L_1 = parseBiggestInt__pureZparseutils_u955(s_p0, (&result), ((NI)0));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	{
		NIM_BOOL T3_;
		tyObject_ValueError__mQsiQ1j8tnHjEYMpj2vv8Q* T7_;
		NimStringV2 T8_;
		T3_ = (NIM_BOOL)0;
		T3_ = !((L_1 == s_p0.len));
		if (T3_) goto LA4_;
		T3_ = (L_1 == ((NI)0));
LA4_: ;
		if (!T3_) goto LA5_;
		T7_ = NIM_NIL;
		T7_ = (tyObject_ValueError__mQsiQ1j8tnHjEYMpj2vv8Q*) nimNewObj(sizeof(tyObject_ValueError__mQsiQ1j8tnHjEYMpj2vv8Q), NIM_ALIGNOF(tyObject_ValueError__mQsiQ1j8tnHjEYMpj2vv8Q));
		(*T7_).Sup.Sup.Sup.m_type = (&NTIv2__mQsiQ1j8tnHjEYMpj2vv8Q_);
		(*T7_).Sup.Sup.name = "ValueError";
		T8_.len = 0; T8_.p = NIM_NIL;
		T8_ = rawNewString(s_p0.len + 17);
appendString((&T8_), TM__JGc9b9bh2D3nTdUR7TGyq8aA_7);
appendString((&T8_), s_p0);
		(*T7_).Sup.Sup.message = T8_;
		(*T7_).Sup.Sup.parent = ((Exception*) NIM_NIL);
		raiseExceptionEx((Exception*)T7_, "ValueError", "parseBiggestInt", "strutils.nim", 1169);
goto BeforeRet_;
	}
LA5_: ;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(NI, minuspercent___system_u813)(NI x_p0, NI y_p1) {
	NI result;
	result = ((NI) ((NU)((NU32)(((NU) (x_p0))) - (NU32)(((NU) (y_p1))))));
	return result;
}
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringV2 s_p0) {
	NCSTRING result;
	{
		if (!(s_p0.len == ((NI)0))) goto LA3_;
		result = "";
	}
	goto LA1_;
LA3_: ;
	{
		result = ((NCSTRING) ((*s_p0.p).data));
	}
LA1_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, nsuFindChar)(NimStringV2 s_p0, NIM_CHAR sub_p1, NI start_p2, NI last_p3) {
	NI result;
	NI colontmpD_;
	NI colontmpD__2;
	NI last_2;
	NI length_1;
{	colontmpD_ = (NI)0;
	colontmpD__2 = (NI)0;
	result = ((NI)-1);
	{
		if (!(last_p3 < ((NI)0))) goto LA3_;
		colontmpD_ = (s_p0.len-1);
		last_2 = colontmpD_;
	}
	goto LA1_;
LA3_: ;
	{
		colontmpD__2 = last_p3;
		last_2 = colontmpD__2;
	}
LA1_: ;
	length_1 = (NI)((NI)(last_2 - start_p2) + ((NI)1));
	{
		void* found_1;
		if (!(((NI)0) < length_1)) goto LA8_;
		found_1 = memchr(((void*) ((&s_p0.p->data[start_p2]))), ((int) (((NU8)(sub_p1)))), ((size_t) (length_1)));
		{
			if (!!((found_1 == 0))) goto LA12_;
			result = minuspercent___system_u813(((NI) (ptrdiff_t) (found_1)), ((NI) (nimToCStringConv(s_p0))));
			goto BeforeRet_;
		}
LA12_: ;
	}
LA8_: ;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, nsuFindStrA)(tyArray__9cc9aPiDa8VaWjVcFLabEDZQ a_p0, NimStringV2 s_p1, NimStringV2 sub_p2, NI start_p3, NI last_p4) {
	NI result;
	NI colontmpD_;
	NI colontmpD__2;
	NI last_2;
	NI subLast_1;
	NI skip_1;
{	colontmpD_ = (NI)0;
	colontmpD__2 = (NI)0;
	{
		if (!(last_p4 < ((NI)0))) goto LA3_;
		colontmpD_ = (s_p1.len-1);
		last_2 = colontmpD_;
	}
	goto LA1_;
LA3_: ;
	{
		colontmpD__2 = last_p4;
		last_2 = colontmpD__2;
	}
LA1_: ;
	subLast_1 = (NI)(sub_p2.len - ((NI)1));
	{
		if (!(subLast_1 == ((NI)-1))) goto LA8_;
		result = start_p3;
		goto BeforeRet_;
	}
LA8_: ;
	result = ((NI)-1);
	skip_1 = start_p3;
	{
		while (1) {
			NI i_1;
			if (!(subLast_1 <= (NI)(last_2 - skip_1))) goto LA11;
			i_1 = subLast_1;
			{
				while (1) {
					if (!((NU8)(s_p1.p->data[(NI)(skip_1 + i_1)]) == (NU8)(sub_p2.p->data[i_1]))) goto LA13;
					{
						if (!(i_1 == ((NI)0))) goto LA16_;
						result = skip_1;
						goto BeforeRet_;
					}
LA16_: ;
					i_1 -= ((NI)1);
				} LA13: ;
			}
			skip_1 += a_p0[(((NU8)(s_p1.p->data[(NI)(skip_1 + subLast_1)])))- 0];
		} LA11: ;
	}
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, nsuInitSkipTable)(NI* a_p0, NimStringV2 sub_p1) {
	NI m_1;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	m_1 = sub_p1.len;
	fill__pureZstrutils_u1563(a_p0, 256, m_1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	{
		NI i_1;
		NI colontmp_;
		NI i_2;
		i_1 = (NI)0;
		colontmp_ = (NI)0;
		colontmp_ = (NI)(m_1 - ((NI)1));
		i_2 = ((NI)0);
		{
			while (1) {
				if (!(i_2 < colontmp_)) goto LA3;
				i_1 = i_2;
				a_p0[(((NU8)(sub_p1.p->data[i_1])))- 0] = (NI)((NI)(m_1 - ((NI)1)) - i_1);
				i_2 += ((NI)1);
			} LA3: ;
		}
	}
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, nsuInitNewSkipTable)(NimStringV2 sub_p0, tyArray__9cc9aPiDa8VaWjVcFLabEDZQ Result) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nsuInitSkipTable(Result, sub_p0);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a_p0, v_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimSetMem__systemZmemory_u7(p_p0, ((int)0), size_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(NI, nsuFindStr)(NimStringV2 s_p0, NimStringV2 sub_p1, NI start_p2, NI last_p3) {
	NI result;
	tyArray__9cc9aPiDa8VaWjVcFLabEDZQ T9_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NI)0;
	{
		if (!((NI)(s_p0.len - start_p2) < sub_p1.len)) goto LA3_;
		result = ((NI)-1);
		goto BeforeRet_;
	}
LA3_: ;
	{
		if (!(sub_p1.len == ((NI)1))) goto LA7_;
		result = nsuFindChar(s_p0, sub_p1.p->data[((NI)0)], start_p2, last_p3);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		goto BeforeRet_;
	}
LA7_: ;
	nimZeroMem((void*)T9_, sizeof(tyArray__9cc9aPiDa8VaWjVcFLabEDZQ));
	nsuInitNewSkipTable(sub_p1, T9_);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	result = nsuFindStrA(T9_, s_p0, sub_p1, start_p2, last_p3);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, substrEq__pureZstrutils_u255)(NimStringV2 s_p0, NI pos_p1, NimStringV2 substr_p2) {
	NIM_BOOL result;
	NIM_BOOL colontmpD_;
	NIM_BOOL colontmpD__2;
	NI length_1;
	colontmpD_ = (NIM_BOOL)0;
	colontmpD__2 = (NIM_BOOL)0;
	length_1 = substr_p2.len;
	{
		NI i_1;
		if (!(((NI)0) < length_1)) goto LA3_;
		i_1 = ((NI)0);
		{
			while (1) {
				NIM_BOOL T7_;
				NIM_BOOL T8_;
				T7_ = (NIM_BOOL)0;
				T8_ = (NIM_BOOL)0;
				T8_ = (i_1 < length_1);
				if (!(T8_)) goto LA9_;
				T8_ = ((NI)(pos_p1 + i_1) < s_p0.len);
LA9_: ;
				T7_ = T8_;
				if (!(T7_)) goto LA10_;
				T7_ = ((NU8)(s_p0.p->data[(NI)(pos_p1 + i_1)]) == (NU8)(substr_p2.p->data[i_1]));
LA10_: ;
				if (!T7_) goto LA6;
				i_1 += ((NI)1);
			} LA6: ;
		}
		colontmpD_ = (i_1 == length_1);
		result = colontmpD_;
	}
	goto LA1_;
LA3_: ;
	{
		colontmpD__2 = NIM_FALSE;
		result = colontmpD__2;
	}
LA1_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tySequence__sM4lkSb7zS6F7OVMvW9cffQ, nsuSplitString)(NimStringV2 s_p0, NimStringV2 sep_p1, NI maxsplit_p2) {
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ result;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = (tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content*) newSeqPayload(0, sizeof(NimStringV2), NIM_ALIGNOF(NimStringV2));
	{
		NimStringV2 xX60gensym69__1;
		NI colontmpD_;
		NI colontmpD__2;
		NI sepLen_1;
		NI lastX60gensym41__1;
		NI splitsX60gensym41__1;
		xX60gensym69__1.len = 0; xX60gensym69__1.p = NIM_NIL;
		colontmpD_ = (NI)0;
		colontmpD__2 = (NI)0;
		{
			if (!(sep_p1.len == ((NI)0))) goto LA5_;
			colontmpD_ = ((NI)1);
			sepLen_1 = colontmpD_;
		}
		goto LA3_;
LA5_: ;
		{
			colontmpD__2 = sep_p1.len;
			sepLen_1 = colontmpD__2;
		}
LA3_: ;
		lastX60gensym41__1 = ((NI)0);
		splitsX60gensym41__1 = maxsplit_p2;
		{
			while (1) {
				NI firstX60gensym41__1;
				NimStringV2 T19_;
				NimStringV2 blitTmp_1;
				if (!(lastX60gensym41__1 <= s_p0.len)) goto LA9;
				firstX60gensym41__1 = lastX60gensym41__1;
				{
					while (1) {
						NIM_BOOL T12_;
						NIM_BOOL T14_;
						T12_ = (NIM_BOOL)0;
						T12_ = (lastX60gensym41__1 < s_p0.len);
						if (!(T12_)) goto LA13_;
						T14_ = (NIM_BOOL)0;
						T14_ = substrEq__pureZstrutils_u255(s_p0, lastX60gensym41__1, sep_p1);
						if (NIM_UNLIKELY(*nimErr_)) goto LA2_;
						T12_ = !(T14_);
LA13_: ;
						if (!T12_) goto LA11;
						lastX60gensym41__1 += ((NI)1);
					} LA11: ;
				}
				{
					if (!(splitsX60gensym41__1 == ((NI)0))) goto LA17_;
					lastX60gensym41__1 = s_p0.len;
				}
LA17_: ;
				T19_.len = 0; T19_.p = NIM_NIL;
				T19_ = substr__system_u6073(s_p0, firstX60gensym41__1, (NI)(lastX60gensym41__1 - ((NI)1)));
				eqsink___system_u2616((&xX60gensym69__1), T19_);
				blitTmp_1 = xX60gensym69__1;
				eqwasMoved___system_u2607((&xX60gensym69__1));
				add__stdZenumutils_u70((&result), blitTmp_1);
				{
					if (!(splitsX60gensym41__1 == ((NI)0))) goto LA22_;
					goto LA8;
				}
LA22_: ;
				splitsX60gensym41__1 -= ((NI)1);
				lastX60gensym41__1 += sepLen_1;
			} LA9: ;
		} LA8: ;
		{
			LA2_:;
		}
		{
			if (xX60gensym69__1.p && !(xX60gensym69__1.p->cap & NIM_STRLIT_FLAG)) {
 dealloc(xX60gensym69__1.p);
}
		}
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	}BeforeRet_: ;
	return result;
}
static N_INLINE(void, nimPrepareStrMutationV2)(NimStringV2* s_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = !(((*s_p0).p == ((NimStrPayload*) NIM_NIL)));
		if (!(T3_)) goto LA4_;
		T3_ = ((NI)((*(*s_p0).p).cap & ((NI)1073741824)) == ((NI)1073741824));
LA4_: ;
		if (!T3_) goto LA5_;
		nimPrepareStrMutationImpl__system_u2373(s_p0);
	}
LA5_: ;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, toHexImpl__pureZstrutils_u773)(NU64 x_p0, NI len_p1, NIM_BOOL handleNegative_p2) {
	NimStringV2 result;
	NU64 n_1;
	n_1 = x_p0;
	result = mnewString(len_p1);
	{
		NI j_1;
		NI colontmp_;
		NI res_1;
		j_1 = (NI)0;
		colontmp_ = (NI)0;
		colontmp_ = (NI)(len_p1 - ((NI)1));
		res_1 = colontmp_;
		{
			while (1) {
				if (!(((NI)0) <= res_1)) goto LA3;
				j_1 = ((NI) (res_1));
				nimPrepareStrMutationV2((&result));
				result.p->data[j_1] = TM__JGc9b9bh2D3nTdUR7TGyq8aA_9.p->data[((NI) ((NU64)(n_1 & 15ULL)))];
				n_1 = (NU64)((NU64)(n_1) >> (NU64)(((NI)4)));
				{
					NIM_BOOL T6_;
					T6_ = (NIM_BOOL)0;
					T6_ = (n_1 == 0ULL);
					if (!(T6_)) goto LA7_;
					T6_ = handleNegative_p2;
LA7_: ;
					if (!T6_) goto LA8_;
					n_1 = 18446744073709551615ULL;
				}
LA8_: ;
				res_1 -= ((NI)1);
			} LA3: ;
		}
	}
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, toHex__pureZstrutils_u2082)(NI x_p0, NI len_p1) {
	NimStringV2 result;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	result = toHexImpl__pureZstrutils_u773(((NU64) (((NI64) (x_p0)))), len_p1, (x_p0 < ((NI)0)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, nsuFindCharSet)(NimStringV2 s_p0, tySet_tyChar__nmiMWKVIe46vacnhAFrQvw chars_p1, NI start_p2, NI last_p3) {
	NI result;
	NI colontmpD_;
	NI colontmpD__2;
	NI last_2;
{	colontmpD_ = (NI)0;
	colontmpD__2 = (NI)0;
	result = ((NI)-1);
	{
		if (!(last_p3 < ((NI)0))) goto LA3_;
		colontmpD_ = (s_p0.len-1);
		last_2 = colontmpD_;
	}
	goto LA1_;
LA3_: ;
	{
		colontmpD__2 = last_p3;
		last_2 = colontmpD__2;
	}
LA1_: ;
	{
		NI i_1;
		NI colontmp_;
		NI res_1;
		i_1 = (NI)0;
		colontmp_ = (NI)0;
		colontmp_ = start_p2;
		res_1 = colontmp_;
		{
			while (1) {
				if (!(res_1 <= last_2)) goto LA8;
				i_1 = ((NI) (res_1));
				{
					if (!((chars_p1[(NU)((((NU8)(s_p0.p->data[i_1]))))>>3] &(1U<<((NU)((((NU8)(s_p0.p->data[i_1]))))&7U)))!=0)) goto LA11_;
					result = i_1;
					goto BeforeRet_;
				}
LA11_: ;
				res_1 += ((NI)1);
			} LA8: ;
		}
	}
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, contains__pureZstrutils_u1820)(NimStringV2 s_p0, tySet_tyChar__nmiMWKVIe46vacnhAFrQvw chars_p1) {
	NIM_BOOL result;
	NI T1_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NIM_BOOL)0;
	T1_ = (NI)0;
	T1_ = nsuFindCharSet(s_p0, chars_p1, ((NI)0), ((NI)-1));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	result = (((NI)0) <= T1_);
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NOINLINE(void, invalidFormatString__pureZstrutils_u2496)(NimStringV2 formatstr_p0) {
	tyObject_ValueError__mQsiQ1j8tnHjEYMpj2vv8Q* T1_;
	NimStringV2 T2_;
{	T1_ = NIM_NIL;
	T1_ = (tyObject_ValueError__mQsiQ1j8tnHjEYMpj2vv8Q*) nimNewObj(sizeof(tyObject_ValueError__mQsiQ1j8tnHjEYMpj2vv8Q), NIM_ALIGNOF(tyObject_ValueError__mQsiQ1j8tnHjEYMpj2vv8Q));
	(*T1_).Sup.Sup.Sup.m_type = (&NTIv2__mQsiQ1j8tnHjEYMpj2vv8Q_);
	(*T1_).Sup.Sup.name = "ValueError";
	T2_.len = 0; T2_.p = NIM_NIL;
	T2_ = rawNewString(formatstr_p0.len + 23);
appendString((&T2_), TM__JGc9b9bh2D3nTdUR7TGyq8aA_11);
appendString((&T2_), formatstr_p0);
	(*T1_).Sup.Sup.message = T2_;
	(*T1_).Sup.Sup.parent = ((Exception*) NIM_NIL);
	raiseExceptionEx((Exception*)T1_, "ValueError", "invalidFormatString", "strutils.nim", 2830);
goto BeforeRet_;
	}BeforeRet_: ;
}
static N_INLINE(void, nimAddCharV1)(NimStringV2* s_p0, NIM_CHAR c_p1) {
	prepareAdd(s_p0, ((NI)1));
	(*(*s_p0).p).data[(*s_p0).len] = c_p1;
	(*s_p0).len += ((NI)1);
	(*(*s_p0).p).data[(*s_p0).len] = 0;
}
static N_INLINE(NIM_CHAR, toLowerAscii__stdZprivateZstrimpl_u1)(NIM_CHAR c_p0) {
	NIM_CHAR result;
	result = (NIM_CHAR)0;
	{
		if (!(((NU8)(c_p0)) >= ((NU8)(65)) && ((NU8)(c_p0)) <= ((NU8)(90)))) goto LA3_;
		result = ((NIM_CHAR) (((NI)(((NU8)(c_p0)) + ((NI)32)))));
	}
	goto LA1_;
LA3_: ;
	{
		result = c_p0;
	}
LA1_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, nsuCmpIgnoreStyle)(NimStringV2 a_p0, NimStringV2 b_p1) {
	NI result;
	NI aLenX60gensym24__1;
	NI bLenX60gensym24__1;
	NI iX60gensym24__1;
	NI jX60gensym24__1;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NI)0;
	aLenX60gensym24__1 = a_p0.len;
	bLenX60gensym24__1 = b_p1.len;
	iX60gensym24__1 = ((NI)0);
	jX60gensym24__1 = ((NI)0);
	{
		while (1) {
			NIM_CHAR colontmpD_;
			NIM_CHAR colontmpD__2;
			NIM_CHAR colontmpD__3;
			NIM_CHAR colontmpD__4;
			NIM_CHAR aaX60gensym24__1;
			NIM_CHAR bbX60gensym24__1;
			colontmpD_ = (NIM_CHAR)0;
			colontmpD__2 = (NIM_CHAR)0;
			colontmpD__3 = (NIM_CHAR)0;
			colontmpD__4 = (NIM_CHAR)0;
			{
				while (1) {
					NIM_BOOL T5_;
					T5_ = (NIM_BOOL)0;
					T5_ = (iX60gensym24__1 < aLenX60gensym24__1);
					if (!(T5_)) goto LA6_;
					T5_ = ((NU8)(a_p0.p->data[iX60gensym24__1]) == (NU8)(95));
LA6_: ;
					if (!T5_) goto LA4;
					iX60gensym24__1 += ((NI)1);
				} LA4: ;
			}
			{
				while (1) {
					NIM_BOOL T9_;
					T9_ = (NIM_BOOL)0;
					T9_ = (jX60gensym24__1 < bLenX60gensym24__1);
					if (!(T9_)) goto LA10_;
					T9_ = ((NU8)(b_p1.p->data[jX60gensym24__1]) == (NU8)(95));
LA10_: ;
					if (!T9_) goto LA8;
					jX60gensym24__1 += ((NI)1);
				} LA8: ;
			}
			{
				if (!(iX60gensym24__1 < aLenX60gensym24__1)) goto LA13_;
				colontmpD_ = toLowerAscii__stdZprivateZstrimpl_u1(a_p0.p->data[iX60gensym24__1]);
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				aaX60gensym24__1 = colontmpD_;
			}
			goto LA11_;
LA13_: ;
			{
				colontmpD__2 = 0;
				aaX60gensym24__1 = colontmpD__2;
			}
LA11_: ;
			{
				if (!(jX60gensym24__1 < bLenX60gensym24__1)) goto LA18_;
				colontmpD__3 = toLowerAscii__stdZprivateZstrimpl_u1(b_p1.p->data[jX60gensym24__1]);
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				bbX60gensym24__1 = colontmpD__3;
			}
			goto LA16_;
LA18_: ;
			{
				colontmpD__4 = 0;
				bbX60gensym24__1 = colontmpD__4;
			}
LA16_: ;
			result = (NI)(((NU8)(aaX60gensym24__1)) - ((NU8)(bbX60gensym24__1)));
			{
				if (!!((result == ((NI)0)))) goto LA23_;
				goto BeforeRet_;
			}
LA23_: ;
			{
				if (!(aLenX60gensym24__1 <= iX60gensym24__1)) goto LA27_;
				{
					if (!(bLenX60gensym24__1 <= jX60gensym24__1)) goto LA31_;
					result = ((NI)0);
					goto BeforeRet_;
				}
LA31_: ;
				result = ((NI)-1);
				goto BeforeRet_;
			}
			goto LA25_;
LA27_: ;
			{
				if (!(bLenX60gensym24__1 <= jX60gensym24__1)) goto LA34_;
				result = ((NI)1);
				goto BeforeRet_;
			}
			goto LA25_;
LA34_: ;
LA25_: ;
			iX60gensym24__1 += ((NI)1);
			jX60gensym24__1 += ((NI)1);
		}
	}
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, findNormalized__pureZstrutils_u2483)(NimStringV2 x_p0, NimStringV2* inArray_p1, NI inArray_p1Len_0) {
	NI result;
	NI i_1;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	i_1 = ((NI)0);
	{
		while (1) {
			if (!(i_1 < (inArray_p1Len_0-1))) goto LA2;
			{
				NI T5_;
				T5_ = (NI)0;
				T5_ = nsuCmpIgnoreStyle(x_p0, inArray_p1[i_1]);
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				if (!(T5_ == ((NI)0))) goto LA6_;
				result = i_1;
				goto BeforeRet_;
			}
LA6_: ;
			i_1 += ((NI)2);
		} LA2: ;
	}
	result = ((NI)-1);
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, nsuAddf)(NimStringV2* s_p0, NimStringV2 formatstr_p1, NimStringV2* a_p2, NI a_p2Len_0) {
	NI i_1;
	NI num_1;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	i_1 = ((NI)0);
	num_1 = ((NI)0);
	{
		while (1) {
			if (!(i_1 < formatstr_p1.len)) goto LA2;
			{
				NIM_BOOL T5_;
				T5_ = (NIM_BOOL)0;
				T5_ = ((NU8)(formatstr_p1.p->data[i_1]) == (NU8)(36));
				if (!(T5_)) goto LA6_;
				T5_ = ((NI)(i_1 + ((NI)1)) < formatstr_p1.len);
LA6_: ;
				if (!T5_) goto LA7_;
				switch (((NU8)(formatstr_p1.p->data[(NI)(i_1 + ((NI)1))]))) {
				case 35:
				{
					{
						if (!((a_p2Len_0-1) < num_1)) goto LA12_;
						invalidFormatString__pureZstrutils_u2496(formatstr_p1);
						if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
					}
LA12_: ;
					prepareAdd((&(*s_p0)), a_p2[num_1].len + 0);
appendString((&(*s_p0)), a_p2[num_1]);
					i_1 += ((NI)2);
					num_1 += ((NI)1);
				}
				break;
				case 36:
				{
					nimAddCharV1((&(*s_p0)), 36);
					i_1 += ((NI)2);
				}
				break;
				case 49 ... 57:
				case 45:
				{
					NI colontmpD_;
					NI colontmpD__2;
					NI j_1;
					NIM_BOOL negative_1;
					NI idx_1;
					colontmpD_ = (NI)0;
					colontmpD__2 = (NI)0;
					j_1 = ((NI)0);
					i_1 += ((NI)1);
					negative_1 = ((NU8)(formatstr_p1.p->data[i_1]) == (NU8)(45));
					{
						if (!negative_1) goto LA18_;
						i_1 += ((NI)1);
					}
LA18_: ;
					{
						while (1) {
							NIM_BOOL T22_;
							T22_ = (NIM_BOOL)0;
							T22_ = (i_1 < formatstr_p1.len);
							if (!(T22_)) goto LA23_;
							T22_ = (((NU8)(formatstr_p1.p->data[i_1])) >= ((NU8)(48)) && ((NU8)(formatstr_p1.p->data[i_1])) <= ((NU8)(57)));
LA23_: ;
							if (!T22_) goto LA21;
							j_1 = (NI)((NI)((NI)(j_1 * ((NI)10)) + ((NU8)(formatstr_p1.p->data[i_1]))) - ((NI)48));
							i_1 += ((NI)1);
						} LA21: ;
					}
					{
						if (!!(negative_1)) goto LA26_;
						colontmpD_ = (NI)(j_1 - ((NI)1));
						idx_1 = colontmpD_;
					}
					goto LA24_;
LA26_: ;
					{
						colontmpD__2 = (NI)(a_p2Len_0 - j_1);
						idx_1 = colontmpD__2;
					}
LA24_: ;
					{
						NIM_BOOL T31_;
						T31_ = (NIM_BOOL)0;
						T31_ = (idx_1 < ((NI)0));
						if (T31_) goto LA32_;
						T31_ = ((a_p2Len_0-1) < idx_1);
LA32_: ;
						if (!T31_) goto LA33_;
						invalidFormatString__pureZstrutils_u2496(formatstr_p1);
						if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
					}
LA33_: ;
					prepareAdd((&(*s_p0)), a_p2[idx_1].len + 0);
appendString((&(*s_p0)), a_p2[idx_1]);
				}
				break;
				case 123:
				{
					NI j_2;
					NI k_1;
					NIM_BOOL negative_2;
					NI isNumber_1;
					j_2 = (NI)(i_1 + ((NI)2));
					k_1 = ((NI)0);
					negative_2 = ((NU8)(formatstr_p1.p->data[j_2]) == (NU8)(45));
					{
						if (!negative_2) goto LA38_;
						j_2 += ((NI)1);
					}
LA38_: ;
					isNumber_1 = ((NI)0);
					{
						while (1) {
							NIM_BOOL T42_;
							T42_ = (NIM_BOOL)0;
							T42_ = (j_2 < formatstr_p1.len);
							if (!(T42_)) goto LA43_;
							T42_ = !((((NU8)(formatstr_p1.p->data[j_2])) == ((NU8)(0)) || ((NU8)(formatstr_p1.p->data[j_2])) == ((NU8)(125))));
LA43_: ;
							if (!T42_) goto LA41;
							{
								if (!(((NU8)(formatstr_p1.p->data[j_2])) >= ((NU8)(48)) && ((NU8)(formatstr_p1.p->data[j_2])) <= ((NU8)(57)))) goto LA46_;
								k_1 = (NI)((NI)((NI)(k_1 * ((NI)10)) + ((NU8)(formatstr_p1.p->data[j_2]))) - ((NI)48));
								{
									if (!(isNumber_1 == ((NI)0))) goto LA50_;
									isNumber_1 = ((NI)1);
								}
LA50_: ;
							}
							goto LA44_;
LA46_: ;
							{
								isNumber_1 = ((NI)-1);
							}
LA44_: ;
							j_2 += ((NI)1);
						} LA41: ;
					}
					{
						NI colontmpD__3;
						NI colontmpD__4;
						NI idx_2;
						if (!(isNumber_1 == ((NI)1))) goto LA55_;
						colontmpD__3 = (NI)0;
						colontmpD__4 = (NI)0;
						{
							if (!!(negative_2)) goto LA59_;
							colontmpD__3 = (NI)(k_1 - ((NI)1));
							idx_2 = colontmpD__3;
						}
						goto LA57_;
LA59_: ;
						{
							colontmpD__4 = (NI)(a_p2Len_0 - k_1);
							idx_2 = colontmpD__4;
						}
LA57_: ;
						{
							NIM_BOOL T64_;
							T64_ = (NIM_BOOL)0;
							T64_ = (idx_2 < ((NI)0));
							if (T64_) goto LA65_;
							T64_ = ((a_p2Len_0-1) < idx_2);
LA65_: ;
							if (!T64_) goto LA66_;
							invalidFormatString__pureZstrutils_u2496(formatstr_p1);
							if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
						}
LA66_: ;
						prepareAdd((&(*s_p0)), a_p2[idx_2].len + 0);
appendString((&(*s_p0)), a_p2[idx_2]);
					}
					goto LA53_;
LA55_: ;
					{
						NimStringV2 colontmpD__5;
						NI x_1;
						colontmpD__5.len = 0; colontmpD__5.p = NIM_NIL;
						colontmpD__5 = substr__system_u6073(formatstr_p1, (NI)(i_1 + ((NI)2)), (NI)(j_2 - ((NI)1)));
						x_1 = findNormalized__pureZstrutils_u2483(colontmpD__5, a_p2, a_p2Len_0);
						if (NIM_UNLIKELY(*nimErr_)) goto LA69_;
						{
							NIM_BOOL T72_;
							T72_ = (NIM_BOOL)0;
							T72_ = (((NI)0) <= x_1);
							if (!(T72_)) goto LA73_;
							T72_ = (x_1 < (a_p2Len_0-1));
LA73_: ;
							if (!T72_) goto LA74_;
							prepareAdd((&(*s_p0)), a_p2[(NI)(x_1 + ((NI)1))].len + 0);
appendString((&(*s_p0)), a_p2[(NI)(x_1 + ((NI)1))]);
						}
						goto LA70_;
LA74_: ;
						{
							invalidFormatString__pureZstrutils_u2496(formatstr_p1);
							if (NIM_UNLIKELY(*nimErr_)) goto LA69_;
						}
LA70_: ;
						{
							LA69_:;
						}
						{
							if (colontmpD__5.p && !(colontmpD__5.p->cap & NIM_STRLIT_FLAG)) {
 dealloc(colontmpD__5.p);
}
						}
						if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
					}
LA53_: ;
					i_1 = (NI)(j_2 + ((NI)1));
				}
				break;
				case 97 ... 122:
				case 65 ... 90:
				case 128 ... 255:
				case 95:
				{
					NimStringV2 colontmpD__6;
					NI j_3;
					NI x_2;
					colontmpD__6.len = 0; colontmpD__6.p = NIM_NIL;
					j_3 = (NI)(i_1 + ((NI)1));
					{
						while (1) {
							NIM_BOOL T83_;
							T83_ = (NIM_BOOL)0;
							T83_ = (j_3 < formatstr_p1.len);
							if (!(T83_)) goto LA84_;
							T83_ = (((NU8)(formatstr_p1.p->data[j_3])) >= ((NU8)(97)) && ((NU8)(formatstr_p1.p->data[j_3])) <= ((NU8)(122)) || ((NU8)(formatstr_p1.p->data[j_3])) >= ((NU8)(65)) && ((NU8)(formatstr_p1.p->data[j_3])) <= ((NU8)(90)) || ((NU8)(formatstr_p1.p->data[j_3])) >= ((NU8)(48)) && ((NU8)(formatstr_p1.p->data[j_3])) <= ((NU8)(57)) || ((NU8)(formatstr_p1.p->data[j_3])) >= ((NU8)(128)) && ((NU8)(formatstr_p1.p->data[j_3])) <= ((NU8)(255)) || ((NU8)(formatstr_p1.p->data[j_3])) == ((NU8)(95)));
LA84_: ;
							if (!T83_) goto LA82;
							j_3 += ((NI)1);
						} LA82: ;
					}
					colontmpD__6 = substr__system_u6073(formatstr_p1, (NI)(i_1 + ((NI)1)), (NI)(j_3 - ((NI)1)));
					x_2 = findNormalized__pureZstrutils_u2483(colontmpD__6, a_p2, a_p2Len_0);
					if (NIM_UNLIKELY(*nimErr_)) goto LA80_;
					{
						NIM_BOOL T87_;
						T87_ = (NIM_BOOL)0;
						T87_ = (((NI)0) <= x_2);
						if (!(T87_)) goto LA88_;
						T87_ = (x_2 < (a_p2Len_0-1));
LA88_: ;
						if (!T87_) goto LA89_;
						prepareAdd((&(*s_p0)), a_p2[(NI)(x_2 + ((NI)1))].len + 0);
appendString((&(*s_p0)), a_p2[(NI)(x_2 + ((NI)1))]);
					}
					goto LA85_;
LA89_: ;
					{
						invalidFormatString__pureZstrutils_u2496(formatstr_p1);
						if (NIM_UNLIKELY(*nimErr_)) goto LA80_;
					}
LA85_: ;
					i_1 = j_3;
					{
						LA80_:;
					}
					{
						if (colontmpD__6.p && !(colontmpD__6.p->cap & NIM_STRLIT_FLAG)) {
 dealloc(colontmpD__6.p);
}
					}
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				}
				break;
				default:
				{
					invalidFormatString__pureZstrutils_u2496(formatstr_p1);
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				}
				break;
				}
			}
			goto LA3_;
LA7_: ;
			{
				nimAddCharV1((&(*s_p0)), formatstr_p1.p->data[i_1]);
				i_1 += ((NI)1);
			}
LA3_: ;
		} LA2: ;
	}
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nsuFormatOpenArray)(NimStringV2 formatstr_p0, NimStringV2* a_p1, NI a_p1Len_0) {
	NimStringV2 result;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	result = rawNewString(((NI)(formatstr_p0.len + (NI)((NU32)(a_p1Len_0) << (NU32)(((NI)4))))));
	nsuAddf((&result), formatstr_p0, a_p1, a_p1Len_0);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nimIdentNormalize__pureZstrutils_u122)(NimStringV2 s_p0) {
	NimStringV2 result;
	NI j_1;
{	result.len = 0; result.p = NIM_NIL;
	result = mnewString((s_p0.len));
	{
		if (!(s_p0.len == ((NI)0))) goto LA3_;
		goto BeforeRet_;
	}
LA3_: ;
	nimPrepareStrMutationV2((&result));
	result.p->data[((NI)0)] = s_p0.p->data[((NI)0)];
	j_1 = ((NI)1);
	{
		NI i_1;
		NI colontmp_;
		NI res_1;
		i_1 = (NI)0;
		colontmp_ = (NI)0;
		colontmp_ = (NI)(s_p0.len - ((NI)1));
		res_1 = ((NI)1);
		{
			while (1) {
				if (!(res_1 <= colontmp_)) goto LA7;
				i_1 = ((NI) (res_1));
				{
					if (!(((NU8)(s_p0.p->data[i_1])) >= ((NU8)(65)) && ((NU8)(s_p0.p->data[i_1])) <= ((NU8)(90)))) goto LA10_;
					nimPrepareStrMutationV2((&result));
					result.p->data[j_1] = ((NIM_CHAR) (((NI)(((NU8)(s_p0.p->data[i_1])) + ((NI)32)))));
					j_1 += ((NI)1);
				}
				goto LA8_;
LA10_: ;
				{
					if (!!(((NU8)(s_p0.p->data[i_1]) == (NU8)(95)))) goto LA13_;
					nimPrepareStrMutationV2((&result));
					result.p->data[j_1] = s_p0.p->data[i_1];
					j_1 += ((NI)1);
				}
				goto LA8_;
LA13_: ;
LA8_: ;
				res_1 += ((NI)1);
			} LA7: ;
		}
	}
	{
		if (!!((j_1 == s_p0.len))) goto LA17_;
		setLengthStrV2((&result), (j_1));
	}
LA17_: ;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(int, nimCmpMem)(void* a_p0, void* b_p1, NI size_p2) {
	int result;
	result = memcmp(a_p0, b_p1, ((size_t) (size_p2)));
	return result;
}
static N_INLINE(NIM_BOOL, equalMem__system_u1739)(void* a_p0, void* b_p1, NI size_p2) {
	NIM_BOOL result;
	int T1_;
	T1_ = (int)0;
	T1_ = nimCmpMem(a_p0, b_p1, size_p2);
	result = (T1_ == ((NI32)0));
	return result;
}
static N_INLINE(NIM_BOOL, eqStrings)(NimStringV2 a_p0, NimStringV2 b_p1) {
	NIM_BOOL result;
	NI alen_1;
	NI blen_1;
{	result = NIM_FALSE;
	alen_1 = a_p0.len;
	blen_1 = b_p1.len;
	{
		if (!(alen_1 == blen_1)) goto LA3_;
		{
			if (!(alen_1 == ((NI)0))) goto LA7_;
			result = NIM_TRUE;
			goto BeforeRet_;
		}
LA7_: ;
		result = equalMem__system_u1739(((void*) ((&a_p0.p->data[((NI)0)]))), ((void*) ((&b_p1.p->data[((NI)0)]))), (alen_1));
		goto BeforeRet_;
	}
LA3_: ;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyEnum_InstrKind__rQo514xDUpHi9bK2iBT5E9bw, parseEnum__OOZsrcZcakesparkZvm_u8481)(NimStringV2 s_p0) {
	tyEnum_InstrKind__rQo514xDUpHi9bK2iBT5E9bw result;
	NimStringV2 colontmpD_;
	tyEnum_InstrKind__rQo514xDUpHi9bK2iBT5E9bw colontmpD__2;
	tyEnum_InstrKind__rQo514xDUpHi9bK2iBT5E9bw colontmpD__3;
	tyEnum_InstrKind__rQo514xDUpHi9bK2iBT5E9bw colontmpD__4;
	tyEnum_InstrKind__rQo514xDUpHi9bK2iBT5E9bw colontmpD__5;
	tyEnum_InstrKind__rQo514xDUpHi9bK2iBT5E9bw colontmpD__6;
	tyEnum_InstrKind__rQo514xDUpHi9bK2iBT5E9bw colontmpD__7;
	tyEnum_InstrKind__rQo514xDUpHi9bK2iBT5E9bw colontmpD__8;
	tyEnum_InstrKind__rQo514xDUpHi9bK2iBT5E9bw colontmpD__9;
	tyEnum_InstrKind__rQo514xDUpHi9bK2iBT5E9bw colontmpD__10;
	tyEnum_InstrKind__rQo514xDUpHi9bK2iBT5E9bw colontmpD__11;
	tyEnum_InstrKind__rQo514xDUpHi9bK2iBT5E9bw colontmpD__12;
	tyEnum_InstrKind__rQo514xDUpHi9bK2iBT5E9bw colontmpD__13;
	tyEnum_InstrKind__rQo514xDUpHi9bK2iBT5E9bw colontmpD__14;
	tyEnum_InstrKind__rQo514xDUpHi9bK2iBT5E9bw colontmpD__15;
	tyEnum_InstrKind__rQo514xDUpHi9bK2iBT5E9bw colontmpD__16;
	tyEnum_InstrKind__rQo514xDUpHi9bK2iBT5E9bw colontmpD__17;
	tyEnum_InstrKind__rQo514xDUpHi9bK2iBT5E9bw colontmpD__18;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (tyEnum_InstrKind__rQo514xDUpHi9bK2iBT5E9bw)0;
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	colontmpD__2 = (tyEnum_InstrKind__rQo514xDUpHi9bK2iBT5E9bw)0;
	colontmpD__3 = (tyEnum_InstrKind__rQo514xDUpHi9bK2iBT5E9bw)0;
	colontmpD__4 = (tyEnum_InstrKind__rQo514xDUpHi9bK2iBT5E9bw)0;
	colontmpD__5 = (tyEnum_InstrKind__rQo514xDUpHi9bK2iBT5E9bw)0;
	colontmpD__6 = (tyEnum_InstrKind__rQo514xDUpHi9bK2iBT5E9bw)0;
	colontmpD__7 = (tyEnum_InstrKind__rQo514xDUpHi9bK2iBT5E9bw)0;
	colontmpD__8 = (tyEnum_InstrKind__rQo514xDUpHi9bK2iBT5E9bw)0;
	colontmpD__9 = (tyEnum_InstrKind__rQo514xDUpHi9bK2iBT5E9bw)0;
	colontmpD__10 = (tyEnum_InstrKind__rQo514xDUpHi9bK2iBT5E9bw)0;
	colontmpD__11 = (tyEnum_InstrKind__rQo514xDUpHi9bK2iBT5E9bw)0;
	colontmpD__12 = (tyEnum_InstrKind__rQo514xDUpHi9bK2iBT5E9bw)0;
	colontmpD__13 = (tyEnum_InstrKind__rQo514xDUpHi9bK2iBT5E9bw)0;
	colontmpD__14 = (tyEnum_InstrKind__rQo514xDUpHi9bK2iBT5E9bw)0;
	colontmpD__15 = (tyEnum_InstrKind__rQo514xDUpHi9bK2iBT5E9bw)0;
	colontmpD__16 = (tyEnum_InstrKind__rQo514xDUpHi9bK2iBT5E9bw)0;
	colontmpD__17 = (tyEnum_InstrKind__rQo514xDUpHi9bK2iBT5E9bw)0;
	colontmpD__18 = (tyEnum_InstrKind__rQo514xDUpHi9bK2iBT5E9bw)0;
	colontmpD_ = nimIdentNormalize__pureZstrutils_u122(s_p0);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	switch (hashString(colontmpD_) & 31) {
	case 0: 
if (eqStrings(colontmpD_, TM__JGc9b9bh2D3nTdUR7TGyq8aA_17)) goto LA4_;
break;
	case 3: 
if (eqStrings(colontmpD_, TM__JGc9b9bh2D3nTdUR7TGyq8aA_13)) goto LA2_;
break;
	case 10: 
if (eqStrings(colontmpD_, TM__JGc9b9bh2D3nTdUR7TGyq8aA_15)) goto LA3_;
break;
	case 11: 
if (eqStrings(colontmpD_, TM__JGc9b9bh2D3nTdUR7TGyq8aA_25)) goto LA8_;
if (eqStrings(colontmpD_, TM__JGc9b9bh2D3nTdUR7TGyq8aA_43)) goto LA17_;
break;
	case 14: 
if (eqStrings(colontmpD_, TM__JGc9b9bh2D3nTdUR7TGyq8aA_39)) goto LA15_;
break;
	case 17: 
if (eqStrings(colontmpD_, TM__JGc9b9bh2D3nTdUR7TGyq8aA_19)) goto LA5_;
break;
	case 18: 
if (eqStrings(colontmpD_, TM__JGc9b9bh2D3nTdUR7TGyq8aA_41)) goto LA16_;
break;
	case 22: 
if (eqStrings(colontmpD_, TM__JGc9b9bh2D3nTdUR7TGyq8aA_45)) goto LA18_;
break;
	case 23: 
if (eqStrings(colontmpD_, TM__JGc9b9bh2D3nTdUR7TGyq8aA_35)) goto LA13_;
break;
	case 24: 
if (eqStrings(colontmpD_, TM__JGc9b9bh2D3nTdUR7TGyq8aA_21)) goto LA6_;
if (eqStrings(colontmpD_, TM__JGc9b9bh2D3nTdUR7TGyq8aA_23)) goto LA7_;
if (eqStrings(colontmpD_, TM__JGc9b9bh2D3nTdUR7TGyq8aA_33)) goto LA12_;
break;
	case 26: 
if (eqStrings(colontmpD_, TM__JGc9b9bh2D3nTdUR7TGyq8aA_27)) goto LA9_;
break;
	case 29: 
if (eqStrings(colontmpD_, TM__JGc9b9bh2D3nTdUR7TGyq8aA_29)) goto LA10_;
if (eqStrings(colontmpD_, TM__JGc9b9bh2D3nTdUR7TGyq8aA_31)) goto LA11_;
if (eqStrings(colontmpD_, TM__JGc9b9bh2D3nTdUR7TGyq8aA_37)) goto LA14_;
break;
	}
	goto LA19_;
	LA2_: ;
	{
		colontmpD__2 = ((tyEnum_InstrKind__rQo514xDUpHi9bK2iBT5E9bw)0);
		result = colontmpD__2;
	}
	goto LA20_;
	LA3_: ;
	{
		colontmpD__3 = ((tyEnum_InstrKind__rQo514xDUpHi9bK2iBT5E9bw)1);
		result = colontmpD__3;
	}
	goto LA20_;
	LA4_: ;
	{
		colontmpD__4 = ((tyEnum_InstrKind__rQo514xDUpHi9bK2iBT5E9bw)2);
		result = colontmpD__4;
	}
	goto LA20_;
	LA5_: ;
	{
		colontmpD__5 = ((tyEnum_InstrKind__rQo514xDUpHi9bK2iBT5E9bw)3);
		result = colontmpD__5;
	}
	goto LA20_;
	LA6_: ;
	{
		colontmpD__6 = ((tyEnum_InstrKind__rQo514xDUpHi9bK2iBT5E9bw)4);
		result = colontmpD__6;
	}
	goto LA20_;
	LA7_: ;
	{
		colontmpD__7 = ((tyEnum_InstrKind__rQo514xDUpHi9bK2iBT5E9bw)5);
		result = colontmpD__7;
	}
	goto LA20_;
	LA8_: ;
	{
		colontmpD__8 = ((tyEnum_InstrKind__rQo514xDUpHi9bK2iBT5E9bw)6);
		result = colontmpD__8;
	}
	goto LA20_;
	LA9_: ;
	{
		colontmpD__9 = ((tyEnum_InstrKind__rQo514xDUpHi9bK2iBT5E9bw)7);
		result = colontmpD__9;
	}
	goto LA20_;
	LA10_: ;
	{
		colontmpD__10 = ((tyEnum_InstrKind__rQo514xDUpHi9bK2iBT5E9bw)8);
		result = colontmpD__10;
	}
	goto LA20_;
	LA11_: ;
	{
		colontmpD__11 = ((tyEnum_InstrKind__rQo514xDUpHi9bK2iBT5E9bw)9);
		result = colontmpD__11;
	}
	goto LA20_;
	LA12_: ;
	{
		colontmpD__12 = ((tyEnum_InstrKind__rQo514xDUpHi9bK2iBT5E9bw)10);
		result = colontmpD__12;
	}
	goto LA20_;
	LA13_: ;
	{
		colontmpD__13 = ((tyEnum_InstrKind__rQo514xDUpHi9bK2iBT5E9bw)11);
		result = colontmpD__13;
	}
	goto LA20_;
	LA14_: ;
	{
		colontmpD__14 = ((tyEnum_InstrKind__rQo514xDUpHi9bK2iBT5E9bw)12);
		result = colontmpD__14;
	}
	goto LA20_;
	LA15_: ;
	{
		colontmpD__15 = ((tyEnum_InstrKind__rQo514xDUpHi9bK2iBT5E9bw)13);
		result = colontmpD__15;
	}
	goto LA20_;
	LA16_: ;
	{
		colontmpD__16 = ((tyEnum_InstrKind__rQo514xDUpHi9bK2iBT5E9bw)14);
		result = colontmpD__16;
	}
	goto LA20_;
	LA17_: ;
	{
		colontmpD__17 = ((tyEnum_InstrKind__rQo514xDUpHi9bK2iBT5E9bw)15);
		result = colontmpD__17;
	}
	goto LA20_;
	LA18_: ;
	{
		colontmpD__18 = ((tyEnum_InstrKind__rQo514xDUpHi9bK2iBT5E9bw)16);
		result = colontmpD__18;
	}
	goto LA20_;
	LA19_: ;
	{
		tyObject_ValueError__mQsiQ1j8tnHjEYMpj2vv8Q* T39_;
		NimStringV2 T40_;
		T39_ = NIM_NIL;
		T39_ = (tyObject_ValueError__mQsiQ1j8tnHjEYMpj2vv8Q*) nimNewObj(sizeof(tyObject_ValueError__mQsiQ1j8tnHjEYMpj2vv8Q), NIM_ALIGNOF(tyObject_ValueError__mQsiQ1j8tnHjEYMpj2vv8Q));
		(*T39_).Sup.Sup.Sup.m_type = (&NTIv2__mQsiQ1j8tnHjEYMpj2vv8Q_);
		(*T39_).Sup.Sup.name = "ValueError";
		T40_.len = 0; T40_.p = NIM_NIL;
		T40_ = rawNewString(s_p0.len + 20);
appendString((&T40_), TM__JGc9b9bh2D3nTdUR7TGyq8aA_47);
appendString((&T40_), s_p0);
		(*T39_).Sup.Sup.message = T40_;
		(*T39_).Sup.Sup.parent = ((Exception*) NIM_NIL);
		raiseExceptionEx((Exception*)T39_, "ValueError", "parseEnum", "enumutils.nim", 77);
goto LA1_;
	}
LA20_: ;
	{
		LA1_:;
	}
	{
		if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 dealloc(colontmpD_.p);
}
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
