/* Generated by Nim Compiler v2.2.4 */
#define NIM_INTBITS 32
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct tyObject_StreamObj__r1XfanY7DoimMbYEDg3nww tyObject_StreamObj__r1XfanY7DoimMbYEDg3nww;
typedef struct tyObject_RefHeader__ZRImJ0JOtQAFc4hlgAu5tA tyObject_RefHeader__ZRImJ0JOtQAFc4hlgAu5tA;
typedef struct RootObj RootObj;
typedef struct TNimTypeV2 TNimTypeV2;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_HSlice__OAVEPXFBgbTm1jVNAuKEpw tyObject_HSlice__OAVEPXFBgbTm1jVNAuKEpw;
typedef struct tyObject_StringStreamObj__Pvdcjy1h9bpZgErN5j9aQ8kg tyObject_StringStreamObj__Pvdcjy1h9bpZgErN5j9aQ8kg;
struct tyObject_RefHeader__ZRImJ0JOtQAFc4hlgAu5tA {
	NI rc;
};
struct TNimTypeV2 {
	void* destructor;
	NI size;
	NI16 align;
	NI16 depth;
	NU32* display;
	void* traceImpl;
	void* typeInfoV1;
	NI flags;
	void* vTable[SEQ_DECL_SIZE];
};
struct RootObj {
	TNimTypeV2* m_type;
};
typedef N_NIMCALL_PTR(void, tyProc__Z0BGe1CQqBBdRybSatYpHw) (tyObject_StreamObj__r1XfanY7DoimMbYEDg3nww* s_p0);
typedef N_NIMCALL_PTR(NIM_BOOL, tyProc__89aG1kw2dG4NN8Qo3wE1EfQ) (tyObject_StreamObj__r1XfanY7DoimMbYEDg3nww* s_p0);
typedef N_NIMCALL_PTR(void, tyProc__79btBbP7mmY49bkBkdL9aNcMw) (tyObject_StreamObj__r1XfanY7DoimMbYEDg3nww* s_p0, NI pos_p1);
typedef N_NIMCALL_PTR(NI, tyProc__xhBjlkggT2vfymS38f7RNQ) (tyObject_StreamObj__r1XfanY7DoimMbYEDg3nww* s_p0);
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
typedef N_NIMCALL_PTR(NI, tyProc__KX6bdurwETtk5lOHJL7HmA) (tyObject_StreamObj__r1XfanY7DoimMbYEDg3nww* s_p0, NimStringV2* buffer_p1, tyObject_HSlice__OAVEPXFBgbTm1jVNAuKEpw slice_p2);
typedef N_NIMCALL_PTR(NIM_BOOL, tyProc__K7ZcPe9agH2LiEIBEJuXBFA) (tyObject_StreamObj__r1XfanY7DoimMbYEDg3nww* s_p0, NimStringV2* line_p1);
typedef N_NIMCALL_PTR(NI, tyProc__nJyGO2VoE5B0hQ59aBVXYeQ) (tyObject_StreamObj__r1XfanY7DoimMbYEDg3nww* s_p0, void* buffer_p1, NI bufLen_p2);
typedef N_NIMCALL_PTR(void, tyProc__oJJrIOLVAgIyvDzlWXQnXA) (tyObject_StreamObj__r1XfanY7DoimMbYEDg3nww* s_p0, void* buffer_p1, NI bufLen_p2);
struct tyObject_StreamObj__r1XfanY7DoimMbYEDg3nww {
	RootObj Sup;
	tyProc__Z0BGe1CQqBBdRybSatYpHw closeImpl;
	tyProc__89aG1kw2dG4NN8Qo3wE1EfQ atEndImpl;
	tyProc__79btBbP7mmY49bkBkdL9aNcMw setPositionImpl;
	tyProc__xhBjlkggT2vfymS38f7RNQ getPositionImpl;
	tyProc__KX6bdurwETtk5lOHJL7HmA readDataStrImpl;
	tyProc__K7ZcPe9agH2LiEIBEJuXBFA readLineImpl;
	tyProc__nJyGO2VoE5B0hQ59aBVXYeQ readDataImpl;
	tyProc__nJyGO2VoE5B0hQ59aBVXYeQ peekDataImpl;
	tyProc__oJJrIOLVAgIyvDzlWXQnXA writeDataImpl;
	tyProc__Z0BGe1CQqBBdRybSatYpHw flushImpl;
};
struct tyObject_HSlice__OAVEPXFBgbTm1jVNAuKEpw {
	NI a;
	NI b;
};
struct tyObject_StringStreamObj__Pvdcjy1h9bpZgErN5j9aQ8kg {
	tyObject_StreamObj__r1XfanY7DoimMbYEDg3nww Sup;
	NimStringV2 data;
	NI pos;
};
static N_INLINE(void, nimIncRef)(void* p_p0);
static N_INLINE(NI, minuspercent___system_u813)(NI x_p0, NI y_p1);
static N_INLINE(NIM_BOOL, nimDecRefIsLast)(void* p_p0);
N_LIB_PRIVATE N_NIMCALL(void, nimDestroyAndDispose)(void* p_p0);
static N_INLINE(void, prepareMutation__system_u2385)(NimStringV2* s_p0);
static N_INLINE(void, nimPrepareStrMutationV2)(NimStringV2* s_p0);
N_LIB_PRIVATE N_NIMCALL(void, nimPrepareStrMutationImpl__system_u2373)(NimStringV2* s_p0);
N_LIB_PRIVATE N_NIMCALL(NI, readData__pureZstreams_u78)(tyObject_StreamObj__r1XfanY7DoimMbYEDg3nww* s_p0, void* buffer_p1, NI bufLen_p2);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZstreams_u704)(tyObject_StringStreamObj__Pvdcjy1h9bpZgErN5j9aQ8kg* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void*, nimNewObj)(NI size_p0, NI alignment_p1);
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__pureZstreams_u1152)(void* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZstreams_u719)(tyObject_StringStreamObj__Pvdcjy1h9bpZgErN5j9aQ8kg* dest_p0);
N_LIB_PRIVATE N_NOCONV(void, dealloc)(void* p_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___system_u2616)(NimStringV2* dest_p0, NimStringV2 src_p1);
N_LIB_PRIVATE N_NIMCALL(void, ssClose__pureZstreams_u896)(tyObject_StreamObj__r1XfanY7DoimMbYEDg3nww* s_p0);
N_LIB_PRIVATE N_NIMCALL(tyObject_StreamObj__r1XfanY7DoimMbYEDg3nww*, eqdup___pureZstreams_u760)(tyObject_StreamObj__r1XfanY7DoimMbYEDg3nww* src_p0);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, ssAtEnd__pureZstreams_u697)(tyObject_StreamObj__r1XfanY7DoimMbYEDg3nww* s_p0);
N_LIB_PRIVATE N_NIMCALL(void, ssSetPosition__pureZstreams_u798)(tyObject_StreamObj__r1XfanY7DoimMbYEDg3nww* s_p0, NI pos_p1);
N_LIB_PRIVATE N_NIMCALL(NI, clamp__pureZstreams_u802)(NI x_p0, NI a_p1, NI b_p2);
N_LIB_PRIVATE N_NIMCALL(NI, ssGetPosition__pureZstreams_u808)(tyObject_StreamObj__r1XfanY7DoimMbYEDg3nww* s_p0);
N_LIB_PRIVATE N_NIMCALL(NI, ssReadDataStr__pureZstreams_u812)(tyObject_StreamObj__r1XfanY7DoimMbYEDg3nww* s_p0, NimStringV2* buffer_p1, tyObject_HSlice__OAVEPXFBgbTm1jVNAuKEpw slice_p2);
static N_INLINE(void, copyMem__system_u1731)(void* dest_p0, void* source_p1, NI size_p2);
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(NI, ssReadData__pureZstreams_u869)(tyObject_StreamObj__r1XfanY7DoimMbYEDg3nww* s_p0, void* buffer_p1, NI bufLen_p2);
N_LIB_PRIVATE N_NIMCALL(NI, ssPeekData__pureZstreams_u880)(tyObject_StreamObj__r1XfanY7DoimMbYEDg3nww* s_p0, void* buffer_p1, NI bufLen_p2);
N_LIB_PRIVATE N_NIMCALL(void, ssWriteData__pureZstreams_u886)(tyObject_StreamObj__r1XfanY7DoimMbYEDg3nww* s_p0, void* buffer_p1, NI bufLen_p2);
N_LIB_PRIVATE N_NIMCALL(void, setLengthStrV2)(NimStringV2* s_p0, NI newLen_p1);
N_LIB_PRIVATE TNimTypeV2 NTIv2__Pvdcjy1h9bpZgErN5j9aQ8kg_;
static const struct {
  NI cap; NIM_CHAR data[0+1];
} TM__Ue7tnBcsL67VCiRfvt8q0A_3 = { 0 | NIM_STRLIT_FLAG, "" };
static const NimStringV2 TM__Ue7tnBcsL67VCiRfvt8q0A_4 = {0, (NimStrPayload*)&TM__Ue7tnBcsL67VCiRfvt8q0A_3};
extern NIM_BOOL nimInErrorMode__system_u3521;
static NIM_CONST NU32 TM__Ue7tnBcsL67VCiRfvt8q0A_2[3] = {3701606400, 1440705024, 4150038272};
N_LIB_PRIVATE TNimTypeV2 NTIv2__Pvdcjy1h9bpZgErN5j9aQ8kg_ = {.destructor = (void*)rttiDestroy__pureZstreams_u1152, .size = sizeof(tyObject_StringStreamObj__Pvdcjy1h9bpZgErN5j9aQ8kg), .align = (NI16) NIM_ALIGNOF(tyObject_StringStreamObj__Pvdcjy1h9bpZgErN5j9aQ8kg), .depth = 2, .display = TM__Ue7tnBcsL67VCiRfvt8q0A_2, .traceImpl = (void*)NIM_NIL, .flags = 0};
static N_INLINE(NI, minuspercent___system_u813)(NI x_p0, NI y_p1) {
	NI result;
	result = ((NI) ((NU)((NU32)(((NU) (x_p0))) - (NU32)(((NU) (y_p1))))));
	return result;
}
static N_INLINE(void, nimIncRef)(void* p_p0) {
	NI T1_;
	T1_ = (NI)0;
	T1_ = minuspercent___system_u813(((NI) (ptrdiff_t) (p_p0)), ((NI)4));
	(*((tyObject_RefHeader__ZRImJ0JOtQAFc4hlgAu5tA*) (T1_))).rc += ((NI)8);
}
static N_INLINE(NIM_BOOL, nimDecRefIsLast)(void* p_p0) {
	NIM_BOOL result;
	result = NIM_FALSE;
	{
		tyObject_RefHeader__ZRImJ0JOtQAFc4hlgAu5tA* cell_1;
		NI T5_;
		if (!!((p_p0 == NIM_NIL))) goto LA3_;
		T5_ = (NI)0;
		T5_ = minuspercent___system_u813(((NI) (ptrdiff_t) (p_p0)), ((NI)4));
		cell_1 = ((tyObject_RefHeader__ZRImJ0JOtQAFc4hlgAu5tA*) (T5_));
		{
			if (!((NI)((NI32)((*cell_1).rc) >> (NU32)(((NI)3))) == ((NI)0))) goto LA8_;
			result = NIM_TRUE;
		}
		goto LA6_;
LA8_: ;
		{
			(*cell_1).rc -= ((NI)8);
		}
LA6_: ;
	}
LA3_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___pureZstreams_u757)(tyObject_StreamObj__r1XfanY7DoimMbYEDg3nww** dest_p0, tyObject_StreamObj__r1XfanY7DoimMbYEDg3nww* src_p1) {
	{
		if (!src_p1) goto LA3_;
		nimIncRef(src_p1);
	}
LA3_: ;
	{
		NIM_BOOL T7_;
		T7_ = (NIM_BOOL)0;
		T7_ = nimDecRefIsLast((*dest_p0));
		if (!T7_) goto LA8_;
		nimDestroyAndDispose((*dest_p0));
	}
LA8_: ;
	(*dest_p0) = src_p1;
}
static N_INLINE(void, nimPrepareStrMutationV2)(NimStringV2* s_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = !(((*s_p0).p == ((NimStrPayload*) NIM_NIL)));
		if (!(T3_)) goto LA4_;
		T3_ = ((NI)((*(*s_p0).p).cap & ((NI)1073741824)) == ((NI)1073741824));
LA4_: ;
		if (!T3_) goto LA5_;
		nimPrepareStrMutationImpl__system_u2373(s_p0);
	}
LA5_: ;
}
static N_INLINE(void, prepareMutation__system_u2385)(NimStringV2* s_p0) {
	NimStringV2* s_2;
	s_2 = s_p0;
	nimPrepareStrMutationV2(((NimStringV2*) (s_2)));
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u3521);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, readData__pureZstreams_u78)(tyObject_StreamObj__r1XfanY7DoimMbYEDg3nww* s_p0, void* buffer_p1, NI bufLen_p2) {
	NI result;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NI)0;
	result = (*s_p0).readDataImpl(s_p0, buffer_p1, bufLen_p2);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, readDataStr__pureZstreams_u84)(tyObject_StreamObj__r1XfanY7DoimMbYEDg3nww* s_p0, NimStringV2* buffer_p1, tyObject_HSlice__OAVEPXFBgbTm1jVNAuKEpw slice_p2) {
	NI result;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NI)0;
	{
		if (!!(((*s_p0).readDataStrImpl == NIM_NIL))) goto LA3_;
		result = (*s_p0).readDataStrImpl(s_p0, buffer_p1, slice_p2);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	goto LA1_;
LA3_: ;
	{
		prepareMutation__system_u2385(buffer_p1);
		result = readData__pureZstreams_u78(s_p0, ((void*) ((&(*buffer_p1).p->data[slice_p2.a]))), (NI)((NI)(slice_p2.b + ((NI)1)) - slice_p2.a));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA1_: ;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, close__pureZstreams_u57)(tyObject_StreamObj__r1XfanY7DoimMbYEDg3nww* s_p0) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = !((s_p0 == 0));
		if (!(T3_)) goto LA4_;
		T3_ = !(((*s_p0).closeImpl == 0));
LA4_: ;
		if (!T3_) goto LA5_;
		(*s_p0).closeImpl(s_p0);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA5_: ;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZstreams_u704)(tyObject_StringStreamObj__Pvdcjy1h9bpZgErN5j9aQ8kg* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLast(dest_p0);
		if (!T3_) goto LA4_;
		nimDestroyAndDispose(dest_p0);
	}
LA4_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZstreams_u719)(tyObject_StringStreamObj__Pvdcjy1h9bpZgErN5j9aQ8kg* dest_p0) {
	if ((*dest_p0).data.p && !((*dest_p0).data.p->cap & NIM_STRLIT_FLAG)) {
 dealloc((*dest_p0).data.p);
}
}
N_LIB_PRIVATE N_NIMCALL(void, rttiDestroy__pureZstreams_u1152)(void* dest_p0) {
	eqdestroy___pureZstreams_u719(((tyObject_StringStreamObj__Pvdcjy1h9bpZgErN5j9aQ8kg*) (dest_p0)));
}
N_LIB_PRIVATE N_NIMCALL(tyObject_StreamObj__r1XfanY7DoimMbYEDg3nww*, eqdup___pureZstreams_u760)(tyObject_StreamObj__r1XfanY7DoimMbYEDg3nww* src_p0) {
	tyObject_StreamObj__r1XfanY7DoimMbYEDg3nww* result;
	result = src_p0;
	{
		if (!src_p0) goto LA3_;
		nimIncRef(src_p0);
	}
LA3_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, ssClose__pureZstreams_u896)(tyObject_StreamObj__r1XfanY7DoimMbYEDg3nww* s_p0) {
	tyObject_StringStreamObj__Pvdcjy1h9bpZgErN5j9aQ8kg* s_2;
	tyObject_StreamObj__r1XfanY7DoimMbYEDg3nww* colontmpD_;
	s_2 = NIM_NIL;
	colontmpD_ = NIM_NIL;
	colontmpD_ = eqdup___pureZstreams_u760(s_p0);
	s_2 = (*((tyObject_StringStreamObj__Pvdcjy1h9bpZgErN5j9aQ8kg**) (&(colontmpD_))));
	eqsink___system_u2616((&(*s_2).data), TM__Ue7tnBcsL67VCiRfvt8q0A_4);
	eqdestroy___pureZstreams_u704(s_2);
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, ssAtEnd__pureZstreams_u697)(tyObject_StreamObj__r1XfanY7DoimMbYEDg3nww* s_p0) {
	NIM_BOOL result;
	tyObject_StringStreamObj__Pvdcjy1h9bpZgErN5j9aQ8kg* s_2;
{	s_2 = NIM_NIL;
	s_2 = ((tyObject_StringStreamObj__Pvdcjy1h9bpZgErN5j9aQ8kg*) (s_p0));
	result = ((*s_2).data.len <= (*s_2).pos);
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, ssSetPosition__pureZstreams_u798)(tyObject_StreamObj__r1XfanY7DoimMbYEDg3nww* s_p0, NI pos_p1) {
	tyObject_StringStreamObj__Pvdcjy1h9bpZgErN5j9aQ8kg* s_2;
	tyObject_StreamObj__r1XfanY7DoimMbYEDg3nww* colontmpD_;
	s_2 = NIM_NIL;
	colontmpD_ = NIM_NIL;
	colontmpD_ = eqdup___pureZstreams_u760(s_p0);
	s_2 = (*((tyObject_StringStreamObj__Pvdcjy1h9bpZgErN5j9aQ8kg**) (&(colontmpD_))));
	(*s_2).pos = clamp__pureZstreams_u802(pos_p1, ((NI)0), (*s_2).data.len);
	eqdestroy___pureZstreams_u704(s_2);
}
N_LIB_PRIVATE N_NIMCALL(NI, ssGetPosition__pureZstreams_u808)(tyObject_StreamObj__r1XfanY7DoimMbYEDg3nww* s_p0) {
	NI result;
	tyObject_StringStreamObj__Pvdcjy1h9bpZgErN5j9aQ8kg* s_2;
{	s_2 = NIM_NIL;
	s_2 = ((tyObject_StringStreamObj__Pvdcjy1h9bpZgErN5j9aQ8kg*) (s_p0));
	result = (*s_2).pos;
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest_p0, source_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, copyMem__system_u1731)(void* dest_p0, void* source_p1, NI size_p2) {
	nimCopyMem(dest_p0, source_p1, size_p2);
}
N_LIB_PRIVATE N_NIMCALL(NI, ssReadDataStr__pureZstreams_u812)(tyObject_StreamObj__r1XfanY7DoimMbYEDg3nww* s_p0, NimStringV2* buffer_p1, tyObject_HSlice__OAVEPXFBgbTm1jVNAuKEpw slice_p2) {
	NI result;
	tyObject_StringStreamObj__Pvdcjy1h9bpZgErN5j9aQ8kg* s_2;
	tyObject_StreamObj__r1XfanY7DoimMbYEDg3nww* colontmpD_;
	s_2 = NIM_NIL;
	colontmpD_ = NIM_NIL;
	colontmpD_ = eqdup___pureZstreams_u760(s_p0);
	s_2 = (*((tyObject_StringStreamObj__Pvdcjy1h9bpZgErN5j9aQ8kg**) (&(colontmpD_))));
	prepareMutation__system_u2385(buffer_p1);
	result = (((NI)((NI)(slice_p2.b + ((NI)1)) - slice_p2.a) <= (NI)((*s_2).data.len - (*s_2).pos)) ? (NI)((NI)(slice_p2.b + ((NI)1)) - slice_p2.a) : (NI)((*s_2).data.len - (*s_2).pos));
	{
		if (!(((NI)0) < result)) goto LA3_;
		{
			copyMem__system_u1731(((void*) ((&(*buffer_p1).p->data[slice_p2.a]))), ((void*) ((&(*s_2).data.p->data[(*s_2).pos]))), (result));
		}
		(*s_2).pos += result;
	}
	goto LA1_;
LA3_: ;
	{
		result = ((NI)0);
	}
LA1_: ;
	eqdestroy___pureZstreams_u704(s_2);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, ssReadData__pureZstreams_u869)(tyObject_StreamObj__r1XfanY7DoimMbYEDg3nww* s_p0, void* buffer_p1, NI bufLen_p2) {
	NI result;
	tyObject_StringStreamObj__Pvdcjy1h9bpZgErN5j9aQ8kg* s_2;
	tyObject_StreamObj__r1XfanY7DoimMbYEDg3nww* colontmpD_;
	s_2 = NIM_NIL;
	colontmpD_ = NIM_NIL;
	colontmpD_ = eqdup___pureZstreams_u760(s_p0);
	s_2 = (*((tyObject_StringStreamObj__Pvdcjy1h9bpZgErN5j9aQ8kg**) (&(colontmpD_))));
	result = ((bufLen_p2 <= (NI)((*s_2).data.len - (*s_2).pos)) ? bufLen_p2 : (NI)((*s_2).data.len - (*s_2).pos));
	{
		if (!(((NI)0) < result)) goto LA3_;
		copyMem__system_u1731(buffer_p1, ((void*) ((&(*s_2).data.p->data[(*s_2).pos]))), (result));
		(*s_2).pos += result;
	}
	goto LA1_;
LA3_: ;
	{
		result = ((NI)0);
	}
LA1_: ;
	eqdestroy___pureZstreams_u704(s_2);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, ssPeekData__pureZstreams_u880)(tyObject_StreamObj__r1XfanY7DoimMbYEDg3nww* s_p0, void* buffer_p1, NI bufLen_p2) {
	NI result;
	tyObject_StringStreamObj__Pvdcjy1h9bpZgErN5j9aQ8kg* s_2;
	s_2 = NIM_NIL;
	s_2 = ((tyObject_StringStreamObj__Pvdcjy1h9bpZgErN5j9aQ8kg*) (s_p0));
	result = ((bufLen_p2 <= (NI)((*s_2).data.len - (*s_2).pos)) ? bufLen_p2 : (NI)((*s_2).data.len - (*s_2).pos));
	{
		if (!(((NI)0) < result)) goto LA3_;
		copyMem__system_u1731(buffer_p1, ((void*) ((&(*s_2).data.p->data[(*s_2).pos]))), (result));
	}
	goto LA1_;
LA3_: ;
	{
		result = ((NI)0);
	}
LA1_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, ssWriteData__pureZstreams_u886)(tyObject_StreamObj__r1XfanY7DoimMbYEDg3nww* s_p0, void* buffer_p1, NI bufLen_p2) {
	tyObject_StringStreamObj__Pvdcjy1h9bpZgErN5j9aQ8kg* s_2;
	tyObject_StreamObj__r1XfanY7DoimMbYEDg3nww* colontmpD_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	s_2 = NIM_NIL;
	colontmpD_ = NIM_NIL;
	colontmpD_ = eqdup___pureZstreams_u760(s_p0);
	s_2 = (*((tyObject_StringStreamObj__Pvdcjy1h9bpZgErN5j9aQ8kg**) (&(colontmpD_))));
	{
		if (!(bufLen_p2 <= ((NI)0))) goto LA4_;
		eqdestroy___pureZstreams_u704(s_2);
		goto BeforeRet_;
	}
LA4_: ;
	{
		if (!((*s_2).data.len < (NI)((*s_2).pos + bufLen_p2))) goto LA8_;
		setLengthStrV2((&(*s_2).data), ((NI)((*s_2).pos + bufLen_p2)));
	}
LA8_: ;
	copyMem__system_u1731(((void*) ((&(*s_2).data.p->data[(*s_2).pos]))), buffer_p1, (bufLen_p2));
	(*s_2).pos += bufLen_p2;
	{
		LA1_:;
	}
	{
		eqdestroy___pureZstreams_u704(s_2);
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_StringStreamObj__Pvdcjy1h9bpZgErN5j9aQ8kg*, newStringStream__pureZstreams_u899)(NimStringV2 s_p0) {
	tyObject_StringStreamObj__Pvdcjy1h9bpZgErN5j9aQ8kg* result;
	result = NIM_NIL;
	eqdestroy___pureZstreams_u704(result);
	result = (tyObject_StringStreamObj__Pvdcjy1h9bpZgErN5j9aQ8kg*) nimNewObj(sizeof(tyObject_StringStreamObj__Pvdcjy1h9bpZgErN5j9aQ8kg), NIM_ALIGNOF(tyObject_StringStreamObj__Pvdcjy1h9bpZgErN5j9aQ8kg));
	(*result).Sup.Sup.m_type = (&NTIv2__Pvdcjy1h9bpZgErN5j9aQ8kg_);
	eqsink___system_u2616((&(*result).data), s_p0);
	prepareMutation__system_u2385((&(*result).data));
	(*result).pos = ((NI)0);
	(*result).Sup.closeImpl = ssClose__pureZstreams_u896;
	(*result).Sup.atEndImpl = ssAtEnd__pureZstreams_u697;
	(*result).Sup.setPositionImpl = ssSetPosition__pureZstreams_u798;
	(*result).Sup.getPositionImpl = ssGetPosition__pureZstreams_u808;
	(*result).Sup.readDataStrImpl = ssReadDataStr__pureZstreams_u812;
	(*result).Sup.readDataImpl = ssReadData__pureZstreams_u869;
	(*result).Sup.peekDataImpl = ssPeekData__pureZstreams_u880;
	(*result).Sup.writeDataImpl = ssWriteData__pureZstreams_u886;
	return result;
}
