/* Generated by Nim Compiler v2.2.4 */
#define NIM_INTBITS 32
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#include <math.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef NU8 tyEnum_FloatClass__SMjs1dKNiOUeXuhzS3bjqg;
static N_INLINE(NIM_BOOL, isNaN__pureZmath_u207)(NF x_p0);
static N_INLINE(NF, abs__system_u4283)(NF x_p0);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
extern NIM_BOOL nimInErrorMode__system_u3521;
N_LIB_PRIVATE N_NIMCALL(NI, nextPowerOfTwo__pureZmath_u245)(NI x_p0) {
	NI result;
	result = (NI)(x_p0 - ((NI)1));
	result = (NI)(result | (NI)((NI32)(result) >> (NU32)(((NI)16))));
	result = (NI)(result | (NI)((NI32)(result) >> (NU32)(((NI)8))));
	result = (NI)(result | (NI)((NI32)(result) >> (NU32)(((NI)4))));
	result = (NI)(result | (NI)((NI32)(result) >> (NU32)(((NI)2))));
	result = (NI)(result | (NI)((NI32)(result) >> (NU32)(((NI)1))));
	result += (NI)(((NI)1) + (x_p0 <= ((NI)0)));
	return result;
}
static N_INLINE(NIM_BOOL, isNaN__pureZmath_u207)(NF x_p0) {
	NIM_BOOL result;
	result = (NIM_BOOL)0;
	result = isnan(x_p0);
	return result;
}
static N_INLINE(NF, abs__system_u4283)(NF x_p0) {
	NF result;
	result = (NF)0;
	result = fabs(x_p0);
	return result;
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u3521);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyEnum_FloatClass__SMjs1dKNiOUeXuhzS3bjqg, classify__pureZmath_u204)(NF x_p0) {
	tyEnum_FloatClass__SMjs1dKNiOUeXuhzS3bjqg result;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = isNaN__pureZmath_u207(x_p0);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (!T3_) goto LA4_;
		result = ((tyEnum_FloatClass__SMjs1dKNiOUeXuhzS3bjqg)4);
		goto BeforeRet_;
	}
LA4_: ;
	{
		if (!(x_p0 == 0.0)) goto LA8_;
		{
			if (!(((NF)(1.0) / (NF)(x_p0)) == INF)) goto LA12_;
			result = ((tyEnum_FloatClass__SMjs1dKNiOUeXuhzS3bjqg)2);
			goto BeforeRet_;
		}
		goto LA10_;
LA12_: ;
		{
			result = ((tyEnum_FloatClass__SMjs1dKNiOUeXuhzS3bjqg)3);
			goto BeforeRet_;
		}
LA10_: ;
	}
LA8_: ;
	{
		if (!(((NF)(x_p0) * (NF)(0.5)) == x_p0)) goto LA17_;
		{
			if (!(0.0 < x_p0)) goto LA21_;
			result = ((tyEnum_FloatClass__SMjs1dKNiOUeXuhzS3bjqg)5);
			goto BeforeRet_;
		}
		goto LA19_;
LA21_: ;
		{
			result = ((tyEnum_FloatClass__SMjs1dKNiOUeXuhzS3bjqg)6);
			goto BeforeRet_;
		}
LA19_: ;
	}
LA17_: ;
	{
		NF T26_;
		T26_ = (NF)0;
		T26_ = abs__system_u4283(x_p0);
		if (!(T26_ < 2.225073858507201e-308)) goto LA27_;
		result = ((tyEnum_FloatClass__SMjs1dKNiOUeXuhzS3bjqg)1);
		goto BeforeRet_;
	}
LA27_: ;
	result = ((tyEnum_FloatClass__SMjs1dKNiOUeXuhzS3bjqg)0);
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
