/* Generated by Nim Compiler v2.2.4 */
#define NIM_INTBITS 32
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_OrderedTable__qEJVXJleSn4PbwLXkdGuEw tyObject_OrderedTable__qEJVXJleSn4PbwLXkdGuEw;
typedef struct tySequence__focVCaRY1axNSYW9at2kyIQ tySequence__focVCaRY1axNSYW9at2kyIQ;
typedef struct tySequence__focVCaRY1axNSYW9at2kyIQ_Content tySequence__focVCaRY1axNSYW9at2kyIQ_Content;
typedef struct tySequence__jKinQKK5sMW4kMIzl4PsKQ tySequence__jKinQKK5sMW4kMIzl4PsKQ;
typedef struct tySequence__jKinQKK5sMW4kMIzl4PsKQ_Content tySequence__jKinQKK5sMW4kMIzl4PsKQ_Content;
typedef struct tyObject_RefHeader__ZRImJ0JOtQAFc4hlgAu5tA tyObject_RefHeader__ZRImJ0JOtQAFc4hlgAu5tA;
typedef struct tyTuple__yeSFujPok8SfAGi9apNECrw tyTuple__yeSFujPok8SfAGi9apNECrw;
typedef struct tyObject_NimRawSeq__9cILcSEMTM25Wr2S8osw5Bw tyObject_NimRawSeq__9cILcSEMTM25Wr2S8osw5Bw;
typedef struct tyTuple__djYX1zUye8QMbG2U8KWWqg tyTuple__djYX1zUye8QMbG2U8KWWqg;
typedef struct tyObject_StringStreamObj__Pvdcjy1h9bpZgErN5j9aQ8kg tyObject_StringStreamObj__Pvdcjy1h9bpZgErN5j9aQ8kg;
typedef struct tyObject_StreamObj__r1XfanY7DoimMbYEDg3nww tyObject_StreamObj__r1XfanY7DoimMbYEDg3nww;
typedef struct tyObject_JsonParser__quW1I9aCxKWHT6UgEfPIy2Q tyObject_JsonParser__quW1I9aCxKWHT6UgEfPIy2Q;
typedef struct tyObject_BaseLexer__oR0gs9bvHMyWCd2oIUY25gg tyObject_BaseLexer__oR0gs9bvHMyWCd2oIUY25gg;
typedef struct RootObj RootObj;
typedef struct TNimTypeV2 TNimTypeV2;
typedef struct tySequence__yeWmXso4I1bpE59aNecDtXg tySequence__yeWmXso4I1bpE59aNecDtXg;
typedef struct tySequence__yeWmXso4I1bpE59aNecDtXg_Content tySequence__yeWmXso4I1bpE59aNecDtXg_Content;
typedef struct Exception Exception;
typedef struct tySequence__lQ1UsDGK2GVVm9bDjc3VrPQ tySequence__lQ1UsDGK2GVVm9bDjc3VrPQ;
typedef struct tySequence__lQ1UsDGK2GVVm9bDjc3VrPQ_Content tySequence__lQ1UsDGK2GVVm9bDjc3VrPQ_Content;
typedef struct tyObject_HSlice__OAVEPXFBgbTm1jVNAuKEpw tyObject_HSlice__OAVEPXFBgbTm1jVNAuKEpw;
typedef struct tyObject_StackTraceEntry__Ys9cmA3ckZAVfrZgZt9axXEw tyObject_StackTraceEntry__Ys9cmA3ckZAVfrZgZt9axXEw;
typedef NU8 tyEnum_JsonNodeKind__k9adLs9b9b0zH29baARdDeUL5A;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
struct tySequence__focVCaRY1axNSYW9at2kyIQ {
  NI len; tySequence__focVCaRY1axNSYW9at2kyIQ_Content* p;
};
struct tyObject_OrderedTable__qEJVXJleSn4PbwLXkdGuEw {
	tySequence__focVCaRY1axNSYW9at2kyIQ data;
	NI counter;
	NI first;
	NI last;
};
struct tySequence__jKinQKK5sMW4kMIzl4PsKQ {
  NI len; tySequence__jKinQKK5sMW4kMIzl4PsKQ_Content* p;
};
struct tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg {
	NIM_BOOL isUnquoted;
	tyEnum_JsonNodeKind__k9adLs9b9b0zH29baARdDeUL5A kind;
union{
	struct {
	NimStringV2 str;
} _kind_1;
	struct {
	NI64 num;
} _kind_2;
	struct {
	NF fnum;
} _kind_3;
	struct {
	NIM_BOOL bval;
} _kind_4;
	struct {
	tyObject_OrderedTable__qEJVXJleSn4PbwLXkdGuEw fields;
} _kind_6;
	struct {
	tySequence__jKinQKK5sMW4kMIzl4PsKQ elems;
} _kind_7;
};
};
struct tyObject_RefHeader__ZRImJ0JOtQAFc4hlgAu5tA {
	NI rc;
};
struct tyTuple__yeSFujPok8SfAGi9apNECrw {
	NimStringV2 Field0;
	tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* Field1;
};
struct tyObject_NimRawSeq__9cILcSEMTM25Wr2S8osw5Bw {
	NI len;
	void* p;
};
struct tyTuple__djYX1zUye8QMbG2U8KWWqg {
	NI Field0;
	NI Field1;
	NimStringV2 Field2;
	tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* Field3;
};
struct TNimTypeV2 {
	void* destructor;
	NI size;
	NI16 align;
	NI16 depth;
	NU32* display;
	void* traceImpl;
	void* typeInfoV1;
	NI flags;
	void* vTable[SEQ_DECL_SIZE];
};
struct RootObj {
	TNimTypeV2* m_type;
};
typedef NU8 tySet_tyChar__nmiMWKVIe46vacnhAFrQvw[32];
struct tyObject_BaseLexer__oR0gs9bvHMyWCd2oIUY25gg {
	RootObj Sup;
	NI bufpos;
	NimStringV2 buf;
	tyObject_StreamObj__r1XfanY7DoimMbYEDg3nww* input;
	NI lineNumber;
	NI sentinel;
	NI lineStart;
	NI offsetBase;
	tySet_tyChar__nmiMWKVIe46vacnhAFrQvw refillChars;
};
typedef NU8 tyEnum_TokKind__ASGiPTHO0n9bhCozD9afmTaQ;
typedef NU8 tyEnum_JsonEventKind__6kmIqDZYZOxa3lx7cJEjOA;
typedef NU8 tyEnum_JsonError__wD5VcfSJDUFltjmsIg0d2g;
struct tySequence__yeWmXso4I1bpE59aNecDtXg {
  NI len; tySequence__yeWmXso4I1bpE59aNecDtXg_Content* p;
};
struct tyObject_JsonParser__quW1I9aCxKWHT6UgEfPIy2Q {
	tyObject_BaseLexer__oR0gs9bvHMyWCd2oIUY25gg Sup;
	NimStringV2 a;
	tyEnum_TokKind__ASGiPTHO0n9bhCozD9afmTaQ tok;
	tyEnum_JsonEventKind__6kmIqDZYZOxa3lx7cJEjOA kind;
	tyEnum_JsonError__wD5VcfSJDUFltjmsIg0d2g err;
	tySequence__yeWmXso4I1bpE59aNecDtXg state;
	NimStringV2 filename;
	NIM_BOOL rawStringLiterals;
};
struct tySequence__lQ1UsDGK2GVVm9bDjc3VrPQ {
  NI len; tySequence__lQ1UsDGK2GVVm9bDjc3VrPQ_Content* p;
};
struct Exception {
	RootObj Sup;
	Exception* parent;
	NCSTRING name;
	NimStringV2 message;
	tySequence__lQ1UsDGK2GVVm9bDjc3VrPQ trace;
	Exception* up;
};
typedef N_NIMCALL_PTR(void, tyProc__Z0BGe1CQqBBdRybSatYpHw) (tyObject_StreamObj__r1XfanY7DoimMbYEDg3nww* s_p0);
typedef N_NIMCALL_PTR(NIM_BOOL, tyProc__89aG1kw2dG4NN8Qo3wE1EfQ) (tyObject_StreamObj__r1XfanY7DoimMbYEDg3nww* s_p0);
typedef N_NIMCALL_PTR(void, tyProc__79btBbP7mmY49bkBkdL9aNcMw) (tyObject_StreamObj__r1XfanY7DoimMbYEDg3nww* s_p0, NI pos_p1);
typedef N_NIMCALL_PTR(NI, tyProc__xhBjlkggT2vfymS38f7RNQ) (tyObject_StreamObj__r1XfanY7DoimMbYEDg3nww* s_p0);
typedef N_NIMCALL_PTR(NI, tyProc__KX6bdurwETtk5lOHJL7HmA) (tyObject_StreamObj__r1XfanY7DoimMbYEDg3nww* s_p0, NimStringV2* buffer_p1, tyObject_HSlice__OAVEPXFBgbTm1jVNAuKEpw slice_p2);
typedef N_NIMCALL_PTR(NIM_BOOL, tyProc__K7ZcPe9agH2LiEIBEJuXBFA) (tyObject_StreamObj__r1XfanY7DoimMbYEDg3nww* s_p0, NimStringV2* line_p1);
typedef N_NIMCALL_PTR(NI, tyProc__nJyGO2VoE5B0hQ59aBVXYeQ) (tyObject_StreamObj__r1XfanY7DoimMbYEDg3nww* s_p0, void* buffer_p1, NI bufLen_p2);
typedef N_NIMCALL_PTR(void, tyProc__oJJrIOLVAgIyvDzlWXQnXA) (tyObject_StreamObj__r1XfanY7DoimMbYEDg3nww* s_p0, void* buffer_p1, NI bufLen_p2);
struct tyObject_StreamObj__r1XfanY7DoimMbYEDg3nww {
	RootObj Sup;
	tyProc__Z0BGe1CQqBBdRybSatYpHw closeImpl;
	tyProc__89aG1kw2dG4NN8Qo3wE1EfQ atEndImpl;
	tyProc__79btBbP7mmY49bkBkdL9aNcMw setPositionImpl;
	tyProc__xhBjlkggT2vfymS38f7RNQ getPositionImpl;
	tyProc__KX6bdurwETtk5lOHJL7HmA readDataStrImpl;
	tyProc__K7ZcPe9agH2LiEIBEJuXBFA readLineImpl;
	tyProc__nJyGO2VoE5B0hQ59aBVXYeQ readDataImpl;
	tyProc__nJyGO2VoE5B0hQ59aBVXYeQ peekDataImpl;
	tyProc__oJJrIOLVAgIyvDzlWXQnXA writeDataImpl;
	tyProc__Z0BGe1CQqBBdRybSatYpHw flushImpl;
};
struct tyObject_StringStreamObj__Pvdcjy1h9bpZgErN5j9aQ8kg {
	tyObject_StreamObj__r1XfanY7DoimMbYEDg3nww Sup;
	NimStringV2 data;
	NI pos;
};
struct tySequence__focVCaRY1axNSYW9at2kyIQ_Content { NI cap; tyTuple__djYX1zUye8QMbG2U8KWWqg data[SEQ_DECL_SIZE]; };
struct tySequence__jKinQKK5sMW4kMIzl4PsKQ_Content { NI cap; tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* data[SEQ_DECL_SIZE]; };
typedef NU8 tyEnum_ParserState__eLzDFWJ5rkUUwQ1KASNsdA;
struct tySequence__yeWmXso4I1bpE59aNecDtXg_Content { NI cap; tyEnum_ParserState__eLzDFWJ5rkUUwQ1KASNsdA data[SEQ_DECL_SIZE]; };
struct tyObject_StackTraceEntry__Ys9cmA3ckZAVfrZgZt9axXEw {
	NCSTRING procname;
	NI line;
	NCSTRING filename;
};
struct tySequence__lQ1UsDGK2GVVm9bDjc3VrPQ_Content { NI cap; tyObject_StackTraceEntry__Ys9cmA3ckZAVfrZgZt9axXEw data[SEQ_DECL_SIZE]; };
struct tyObject_HSlice__OAVEPXFBgbTm1jVNAuKEpw {
	NI a;
	NI b;
};
N_LIB_PRIVATE N_NIMCALL(void*, nimNewObj)(NI size_p0, NI alignment_p1);
N_LIB_PRIVATE N_NIMCALL(tyObject_OrderedTable__qEJVXJleSn4PbwLXkdGuEw, initOrderedTable__pureZjson_u428)(NI initialSize_p0);
N_LIB_PRIVATE N_NOCONV(void, dealloc)(void* p_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZjson_u85)(tySequence__focVCaRY1axNSYW9at2kyIQ dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZjson_u238)(tySequence__jKinQKK5sMW4kMIzl4PsKQ dest_p0);
static N_INLINE(NIM_BOOL, nimDecRefIsLast)(void* p_p0);
static N_INLINE(NI, minuspercent___system_u813)(NI x_p0, NI y_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZjson_u64)(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, nimRawDispose)(void* p_p0, NI alignment_p1);
N_LIB_PRIVATE N_NIMCALL(void, alignedDealloc)(void* p_p0, NI align_p1);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
static N_INLINE(void, nimIncRef)(void* p_p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, eqdup___system_u2613)(NimStringV2 src_p0);
N_LIB_PRIVATE N_NIMCALL(void*, newSeqPayload)(NI cap_p0, NI elemSize_p1, NI elemAlign_p2);
N_LIB_PRIVATE N_NIMCALL(void, add__pureZjson_u622)(tySequence__jKinQKK5sMW4kMIzl4PsKQ* x_p0, tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* y_p1);
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg*, eqdup___pureZjson_u308)(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* src_p0);
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg*, newJArray__pureZjson_u474)(void);
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg*, newJObject__pureZjson_u414)(void);
N_LIB_PRIVATE N_NIMCALL(void, X5BX5Deq___pureZjson_u689)(tyObject_OrderedTable__qEJVXJleSn4PbwLXkdGuEw* t_p0, NimStringV2 key_p1, tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* val_p2);
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg*, newJString__pureZjson_u42)(NimStringV2 s_p0);
N_NIMCALL(NimStringV2, rawNewString)(NI cap_p0);
N_LIB_PRIVATE N_NIMCALL(NI, len__pureZjson_u3389)(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* n_p0);
static N_INLINE(NI, len__pureZjson_u2537)(tyObject_OrderedTable__qEJVXJleSn4PbwLXkdGuEw t_p0);
N_LIB_PRIVATE N_NIMCALL(void, toUgly__pureZjson_u4692)(NimStringV2* result_p0, tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* node_p1);
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1);
static N_INLINE(void, copyMem__system_u1731)(void* dest_p0, void* source_p1, NI size_p2);
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(void, prepareAdd)(NimStringV2* s_p0, NI addLen_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___pureZjson_u241)(tySequence__jKinQKK5sMW4kMIzl4PsKQ* dest_p0, tySequence__jKinQKK5sMW4kMIzl4PsKQ src_p1);
static N_INLINE(NIM_BOOL, sameSeqPayload)(void* x_p0, void* y_p1);
N_LIB_PRIVATE N_NIMCALL(void, setLen__pureZjson_u257)(tySequence__jKinQKK5sMW4kMIzl4PsKQ* s_p0, NI newlen_p1);
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1);
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___pureZjson_u460)(tyObject_OrderedTable__qEJVXJleSn4PbwLXkdGuEw* dest_p0, tyObject_OrderedTable__qEJVXJleSn4PbwLXkdGuEw src_p1);
static N_INLINE(NIM_BOOL, isFilled__pureZcollectionsZtables_u31)(NI hcode_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___system_u2610)(NimStringV2* dest_p0, NimStringV2 src_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___pureZjson_u305)(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg** dest_p0, tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* src_p1);
N_LIB_PRIVATE N_NIMCALL(void, escapeJson__pureZjson_u4682)(NimStringV2 s_p0, NimStringV2* result_p1);
N_LIB_PRIVATE N_NIMCALL(void, escapeJsonUnquoted__pureZjson_u4661)(NimStringV2 s_p0, NimStringV2* result_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___systemZdollars_u14)(NI xX60gensym0__p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, toHex__pureZstrutils_u2082)(NI x_p0, NI len_p1);
static N_INLINE(void, nimAddCharV1)(NimStringV2* s_p0, NIM_CHAR c_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZjson_u457)(tyObject_OrderedTable__qEJVXJleSn4PbwLXkdGuEw* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZjson_u302)(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, addInt__stdZprivateZdigitsutils_u178)(NimStringV2* result_p0, NI64 x_p1);
static N_INLINE(void, addFloat__system_u3947)(NimStringV2* result_p0, NF x_p1);
N_LIB_PRIVATE N_NIMCALL(void, addFloatRoundtrip__system_u3952)(NimStringV2* result_p0, NF x_p1);
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg*, parseJson__pureZjson_u5531)(tyObject_StreamObj__r1XfanY7DoimMbYEDg3nww* s_p0, NimStringV2 filename_p1, NIM_BOOL rawIntegers_p2, NIM_BOOL rawFloats_p3);
N_LIB_PRIVATE N_NIMCALL(void, open__pureZparsejson_u79)(tyObject_JsonParser__quW1I9aCxKWHT6UgEfPIy2Q* my_p0, tyObject_StreamObj__r1XfanY7DoimMbYEDg3nww* input_p1, NimStringV2 filename_p2, NIM_BOOL rawStringLiterals_p3);
N_LIB_PRIVATE N_NIMCALL(tyEnum_TokKind__ASGiPTHO0n9bhCozD9afmTaQ, getTok__pureZparsejson_u629)(tyObject_JsonParser__quW1I9aCxKWHT6UgEfPIy2Q* my_p0);
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg*, parseJson__pureZjson_u5485)(tyObject_JsonParser__quW1I9aCxKWHT6UgEfPIy2Q* p_p0, NIM_BOOL rawIntegers_p1, NIM_BOOL rawFloats_p2, NI depth_p3);
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___system_u2607)(NimStringV2* dest_p0);
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg*, newJRawNumber__pureZjson_u400)(NimStringV2 s_p0);
N_LIB_PRIVATE N_NIMCALL(void*, nimNewObjUninit)(NI size_p0, NI alignment_p1);
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg*, newJInt__pureZjson_u403)(NI64 n_p0);
N_LIB_PRIVATE N_NIMCALL(NI64, nsuParseBiggestInt)(NimStringV2 s_p0);
static N_INLINE(NIM_BOOL, isObjDisplayCheck)(TNimTypeV2* source_p0, NI16 targetDepth_p1, NU32 token_p2);
static N_INLINE(Exception*, nimBorrowCurrentException)(void);
static N_INLINE(void, popCurrentException)(void);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___system_u3269)(Exception** dest_p0, Exception* src_p1);
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg*, newJFloat__pureZjson_u406)(NF n_p0);
N_LIB_PRIVATE N_NIMCALL(NF, nsuParseFloat)(NimStringV2 s_p0);
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg*, newJBool__pureZjson_u409)(NIM_BOOL b_p0);
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg*, newJNull__pureZjson_u412)(void);
N_LIB_PRIVATE N_NOINLINE(void, raiseParseErr__pureZparsejson_u820)(tyObject_JsonParser__quW1I9aCxKWHT6UgEfPIy2Q* p_p0, NimStringV2 msg_p1);
N_LIB_PRIVATE N_NIMCALL(void, eat__pureZparsejson_u868)(tyObject_JsonParser__quW1I9aCxKWHT6UgEfPIy2Q* p_p0, tyEnum_TokKind__ASGiPTHO0n9bhCozD9afmTaQ tok_p1);
static N_INLINE(void, X5BX5Deq___pureZjson_u2249)(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* obj_p0, NimStringV2 key_p1, tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* val_p2);
N_LIB_PRIVATE N_NIMCALL(void, add__pureZjson_u612)(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* father_p0, tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* child_p1);
static N_INLINE(void, close__pureZparsejson_u288)(tyObject_JsonParser__quW1I9aCxKWHT6UgEfPIy2Q* my_p0);
N_LIB_PRIVATE N_NIMCALL(void, close__pureZlexbase_u14)(tyObject_BaseLexer__oR0gs9bvHMyWCd2oIUY25gg* L_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZparsejson_u121)(tyObject_JsonParser__quW1I9aCxKWHT6UgEfPIy2Q* dest_p0);
N_LIB_PRIVATE N_NIMCALL(tyObject_StringStreamObj__Pvdcjy1h9bpZgErN5j9aQ8kg*, newStringStream__pureZstreams_u899)(NimStringV2 s_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZstreams_u704)(tyObject_StringStreamObj__Pvdcjy1h9bpZgErN5j9aQ8kg* dest_p0);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, hasKey__pureZjson_u2941)(tyObject_OrderedTable__qEJVXJleSn4PbwLXkdGuEw t_p0, NimStringV2 key_p1);
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__9b9bytt1stv9cZ8uqII7HFgew_2 = { 3 | NIM_STRLIT_FLAG, "nan" };
static const NimStringV2 TM__9b9bytt1stv9cZ8uqII7HFgew_3 = {3, (NimStrPayload*)&TM__9b9bytt1stv9cZ8uqII7HFgew_2};
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__9b9bytt1stv9cZ8uqII7HFgew_4 = { 3 | NIM_STRLIT_FLAG, "inf" };
static const NimStringV2 TM__9b9bytt1stv9cZ8uqII7HFgew_5 = {3, (NimStrPayload*)&TM__9b9bytt1stv9cZ8uqII7HFgew_4};
static const struct {
  NI cap; NIM_CHAR data[4+1];
} TM__9b9bytt1stv9cZ8uqII7HFgew_6 = { 4 | NIM_STRLIT_FLAG, "-inf" };
static const NimStringV2 TM__9b9bytt1stv9cZ8uqII7HFgew_7 = {4, (NimStrPayload*)&TM__9b9bytt1stv9cZ8uqII7HFgew_6};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__9b9bytt1stv9cZ8uqII7HFgew_8 = { 1 | NIM_STRLIT_FLAG, "[" };
static const NimStringV2 TM__9b9bytt1stv9cZ8uqII7HFgew_9 = {1, (NimStrPayload*)&TM__9b9bytt1stv9cZ8uqII7HFgew_8};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__9b9bytt1stv9cZ8uqII7HFgew_10 = { 1 | NIM_STRLIT_FLAG, "," };
static const NimStringV2 TM__9b9bytt1stv9cZ8uqII7HFgew_11 = {1, (NimStrPayload*)&TM__9b9bytt1stv9cZ8uqII7HFgew_10};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__9b9bytt1stv9cZ8uqII7HFgew_12 = { 1 | NIM_STRLIT_FLAG, "]" };
static const NimStringV2 TM__9b9bytt1stv9cZ8uqII7HFgew_13 = {1, (NimStrPayload*)&TM__9b9bytt1stv9cZ8uqII7HFgew_12};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__9b9bytt1stv9cZ8uqII7HFgew_14 = { 1 | NIM_STRLIT_FLAG, "{" };
static const NimStringV2 TM__9b9bytt1stv9cZ8uqII7HFgew_15 = {1, (NimStrPayload*)&TM__9b9bytt1stv9cZ8uqII7HFgew_14};
static const NimStringV2 TM__9b9bytt1stv9cZ8uqII7HFgew_16 = {1, (NimStrPayload*)&TM__9b9bytt1stv9cZ8uqII7HFgew_10};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__9b9bytt1stv9cZ8uqII7HFgew_17 = { 1 | NIM_STRLIT_FLAG, "\"" };
static const NimStringV2 TM__9b9bytt1stv9cZ8uqII7HFgew_18 = {1, (NimStrPayload*)&TM__9b9bytt1stv9cZ8uqII7HFgew_17};
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__9b9bytt1stv9cZ8uqII7HFgew_19 = { 2 | NIM_STRLIT_FLAG, "\\n" };
static const NimStringV2 TM__9b9bytt1stv9cZ8uqII7HFgew_20 = {2, (NimStrPayload*)&TM__9b9bytt1stv9cZ8uqII7HFgew_19};
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__9b9bytt1stv9cZ8uqII7HFgew_21 = { 2 | NIM_STRLIT_FLAG, "\\b" };
static const NimStringV2 TM__9b9bytt1stv9cZ8uqII7HFgew_22 = {2, (NimStrPayload*)&TM__9b9bytt1stv9cZ8uqII7HFgew_21};
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__9b9bytt1stv9cZ8uqII7HFgew_23 = { 2 | NIM_STRLIT_FLAG, "\\f" };
static const NimStringV2 TM__9b9bytt1stv9cZ8uqII7HFgew_24 = {2, (NimStrPayload*)&TM__9b9bytt1stv9cZ8uqII7HFgew_23};
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__9b9bytt1stv9cZ8uqII7HFgew_25 = { 2 | NIM_STRLIT_FLAG, "\\t" };
static const NimStringV2 TM__9b9bytt1stv9cZ8uqII7HFgew_26 = {2, (NimStrPayload*)&TM__9b9bytt1stv9cZ8uqII7HFgew_25};
static const struct {
  NI cap; NIM_CHAR data[6+1];
} TM__9b9bytt1stv9cZ8uqII7HFgew_27 = { 6 | NIM_STRLIT_FLAG, "\\u000b" };
static const NimStringV2 TM__9b9bytt1stv9cZ8uqII7HFgew_28 = {6, (NimStrPayload*)&TM__9b9bytt1stv9cZ8uqII7HFgew_27};
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__9b9bytt1stv9cZ8uqII7HFgew_29 = { 2 | NIM_STRLIT_FLAG, "\\r" };
static const NimStringV2 TM__9b9bytt1stv9cZ8uqII7HFgew_30 = {2, (NimStrPayload*)&TM__9b9bytt1stv9cZ8uqII7HFgew_29};
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__9b9bytt1stv9cZ8uqII7HFgew_31 = { 2 | NIM_STRLIT_FLAG, "\\\"" };
static const NimStringV2 TM__9b9bytt1stv9cZ8uqII7HFgew_32 = {2, (NimStrPayload*)&TM__9b9bytt1stv9cZ8uqII7HFgew_31};
static const struct {
  NI cap; NIM_CHAR data[5+1];
} TM__9b9bytt1stv9cZ8uqII7HFgew_33 = { 5 | NIM_STRLIT_FLAG, "\\u000" };
static const NimStringV2 TM__9b9bytt1stv9cZ8uqII7HFgew_34 = {5, (NimStrPayload*)&TM__9b9bytt1stv9cZ8uqII7HFgew_33};
static const struct {
  NI cap; NIM_CHAR data[4+1];
} TM__9b9bytt1stv9cZ8uqII7HFgew_35 = { 4 | NIM_STRLIT_FLAG, "\\u00" };
static const NimStringV2 TM__9b9bytt1stv9cZ8uqII7HFgew_36 = {4, (NimStrPayload*)&TM__9b9bytt1stv9cZ8uqII7HFgew_35};
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__9b9bytt1stv9cZ8uqII7HFgew_37 = { 2 | NIM_STRLIT_FLAG, "\\\\" };
static const NimStringV2 TM__9b9bytt1stv9cZ8uqII7HFgew_38 = {2, (NimStrPayload*)&TM__9b9bytt1stv9cZ8uqII7HFgew_37};
static const NimStringV2 TM__9b9bytt1stv9cZ8uqII7HFgew_39 = {1, (NimStrPayload*)&TM__9b9bytt1stv9cZ8uqII7HFgew_17};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__9b9bytt1stv9cZ8uqII7HFgew_40 = { 1 | NIM_STRLIT_FLAG, ":" };
static const NimStringV2 TM__9b9bytt1stv9cZ8uqII7HFgew_41 = {1, (NimStrPayload*)&TM__9b9bytt1stv9cZ8uqII7HFgew_40};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__9b9bytt1stv9cZ8uqII7HFgew_42 = { 1 | NIM_STRLIT_FLAG, "}" };
static const NimStringV2 TM__9b9bytt1stv9cZ8uqII7HFgew_43 = {1, (NimStrPayload*)&TM__9b9bytt1stv9cZ8uqII7HFgew_42};
static const struct {
  NI cap; NIM_CHAR data[4+1];
} TM__9b9bytt1stv9cZ8uqII7HFgew_44 = { 4 | NIM_STRLIT_FLAG, "true" };
static const NimStringV2 TM__9b9bytt1stv9cZ8uqII7HFgew_45 = {4, (NimStrPayload*)&TM__9b9bytt1stv9cZ8uqII7HFgew_44};
static const struct {
  NI cap; NIM_CHAR data[5+1];
} TM__9b9bytt1stv9cZ8uqII7HFgew_46 = { 5 | NIM_STRLIT_FLAG, "false" };
static const NimStringV2 TM__9b9bytt1stv9cZ8uqII7HFgew_47 = {5, (NimStrPayload*)&TM__9b9bytt1stv9cZ8uqII7HFgew_46};
static const struct {
  NI cap; NIM_CHAR data[4+1];
} TM__9b9bytt1stv9cZ8uqII7HFgew_48 = { 4 | NIM_STRLIT_FLAG, "null" };
static const NimStringV2 TM__9b9bytt1stv9cZ8uqII7HFgew_49 = {4, (NimStrPayload*)&TM__9b9bytt1stv9cZ8uqII7HFgew_48};
extern TNimTypeV2 NTIv2__quW1I9aCxKWHT6UgEfPIy2Q_;
static const NimStringV2 TM__9b9bytt1stv9cZ8uqII7HFgew_50 = {1, (NimStrPayload*)&TM__9b9bytt1stv9cZ8uqII7HFgew_42};
static const struct {
  NI cap; NIM_CHAR data[21+1];
} TM__9b9bytt1stv9cZ8uqII7HFgew_51 = { 21 | NIM_STRLIT_FLAG, "string literal as key" };
static const NimStringV2 TM__9b9bytt1stv9cZ8uqII7HFgew_52 = {21, (NimStrPayload*)&TM__9b9bytt1stv9cZ8uqII7HFgew_51};
static const NimStringV2 TM__9b9bytt1stv9cZ8uqII7HFgew_53 = {1, (NimStrPayload*)&TM__9b9bytt1stv9cZ8uqII7HFgew_12};
static const NimStringV2 TM__9b9bytt1stv9cZ8uqII7HFgew_54 = {1, (NimStrPayload*)&TM__9b9bytt1stv9cZ8uqII7HFgew_14};
static const struct {
  NI cap; NIM_CHAR data[5+1];
} TM__9b9bytt1stv9cZ8uqII7HFgew_55 = { 5 | NIM_STRLIT_FLAG, "input" };
static const NimStringV2 TM__9b9bytt1stv9cZ8uqII7HFgew_56 = {5, (NimStrPayload*)&TM__9b9bytt1stv9cZ8uqII7HFgew_55};
extern NIM_BOOL nimInErrorMode__system_u3521;
extern Exception* currException__system_u3239;
static N_INLINE(NI, minuspercent___system_u813)(NI x_p0, NI y_p1) {
	NI result;
	result = ((NI) ((NU)((NU32)(((NU) (x_p0))) - (NU32)(((NU) (y_p1))))));
	return result;
}
static N_INLINE(NIM_BOOL, nimDecRefIsLast)(void* p_p0) {
	NIM_BOOL result;
	result = NIM_FALSE;
	{
		tyObject_RefHeader__ZRImJ0JOtQAFc4hlgAu5tA* cell_1;
		NI T5_;
		if (!!((p_p0 == NIM_NIL))) goto LA3_;
		T5_ = (NI)0;
		T5_ = minuspercent___system_u813(((NI) (ptrdiff_t) (p_p0)), ((NI)4));
		cell_1 = ((tyObject_RefHeader__ZRImJ0JOtQAFc4hlgAu5tA*) (T5_));
		{
			if (!((NI)((NI32)((*cell_1).rc) >> (NU32)(((NI)3))) == ((NI)0))) goto LA8_;
			result = NIM_TRUE;
		}
		goto LA6_;
LA8_: ;
		{
			(*cell_1).rc -= ((NI)8);
		}
LA6_: ;
	}
LA3_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZjson_u238)(tySequence__jKinQKK5sMW4kMIzl4PsKQ dest_p0) {
	NI colontmp_;
	colontmp_ = ((NI)0);
	{
		while (1) {
			NI T3_;
			T3_ = dest_p0.len;
			if (!(colontmp_ < T3_)) goto LA2;
			{
				NIM_BOOL T6_;
				T6_ = (NIM_BOOL)0;
				T6_ = nimDecRefIsLast(dest_p0.p->data[colontmp_]);
				if (!T6_) goto LA7_;
				eqdestroy___pureZjson_u64(dest_p0.p->data[colontmp_]);
				nimRawDispose(dest_p0.p->data[colontmp_], ((NI)8));
			}
LA7_: ;
			colontmp_ += ((NI)1);
		} LA2: ;
	}
	if (dest_p0.p && !(dest_p0.p->cap & NIM_STRLIT_FLAG)) {
 alignedDealloc(dest_p0.p, NIM_ALIGNOF(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg*));
}
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZjson_u64)(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* dest_p0) {
	switch ((*dest_p0).kind) {
	case ((tyEnum_JsonNodeKind__k9adLs9b9b0zH29baARdDeUL5A)4):
	{
		if ((*dest_p0)._kind_1.str.p && !((*dest_p0)._kind_1.str.p->cap & NIM_STRLIT_FLAG)) {
 dealloc((*dest_p0)._kind_1.str.p);
}
	}
	break;
	case ((tyEnum_JsonNodeKind__k9adLs9b9b0zH29baARdDeUL5A)2):
	{
	}
	break;
	case ((tyEnum_JsonNodeKind__k9adLs9b9b0zH29baARdDeUL5A)3):
	{
	}
	break;
	case ((tyEnum_JsonNodeKind__k9adLs9b9b0zH29baARdDeUL5A)1):
	{
	}
	break;
	case ((tyEnum_JsonNodeKind__k9adLs9b9b0zH29baARdDeUL5A)0):
	{
	}
	break;
	case ((tyEnum_JsonNodeKind__k9adLs9b9b0zH29baARdDeUL5A)5):
	{
		eqdestroy___pureZjson_u85((*dest_p0)._kind_6.fields.data);
	}
	break;
	case ((tyEnum_JsonNodeKind__k9adLs9b9b0zH29baARdDeUL5A)6):
	{
		eqdestroy___pureZjson_u238((*dest_p0)._kind_7.elems);
	}
	break;
	default: __builtin_unreachable();
	}
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u3521);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg*, newJObject__pureZjson_u414)(void) {
	tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* result;
	tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* T1_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = NIM_NIL;
	T1_ = NIM_NIL;
	T1_ = (tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg*) nimNewObj(sizeof(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg), NIM_ALIGNOF(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg));
	(*T1_).kind = ((tyEnum_JsonNodeKind__k9adLs9b9b0zH29baARdDeUL5A)5);
	(*T1_)._kind_6.fields = initOrderedTable__pureZjson_u428(((NI)2));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	result = T1_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqsink___pureZjson_u311)(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg** dest_p0, tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* src_p1) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLast((*dest_p0));
		if (!T3_) goto LA4_;
		eqdestroy___pureZjson_u64((*dest_p0));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		nimRawDispose((*dest_p0), ((NI)8));
	}
LA4_: ;
	(*dest_p0) = src_p1;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___pureZjson_u299)(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg** dest_p0) {
	(*dest_p0) = 0;
}
static N_INLINE(void, nimIncRef)(void* p_p0) {
	NI T1_;
	T1_ = (NI)0;
	T1_ = minuspercent___system_u813(((NI) (ptrdiff_t) (p_p0)), ((NI)4));
	(*((tyObject_RefHeader__ZRImJ0JOtQAFc4hlgAu5tA*) (T1_))).rc += ((NI)8);
}
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg*, eqdup___pureZjson_u308)(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* src_p0) {
	tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* result;
	result = src_p0;
	{
		if (!src_p0) goto LA3_;
		nimIncRef(src_p0);
	}
LA3_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg*, percent___pureZjson_u2115)(NI n_p0) {
	tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* result;
	NI colontmpD_;
	tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* T1_;
	colontmpD_ = (NI)0;
	T1_ = NIM_NIL;
	T1_ = (tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg*) nimNewObj(sizeof(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg), NIM_ALIGNOF(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg));
	(*T1_).kind = ((tyEnum_JsonNodeKind__k9adLs9b9b0zH29baARdDeUL5A)2);
	colontmpD_ = n_p0;
	(*T1_)._kind_2.num = ((NI64) (colontmpD_));
	result = T1_;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg*, percent___pureZjson_u2131)(NIM_BOOL b_p0) {
	tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* result;
	NIM_BOOL colontmpD_;
	tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* T1_;
	colontmpD_ = (NIM_BOOL)0;
	T1_ = NIM_NIL;
	T1_ = (tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg*) nimNewObj(sizeof(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg), NIM_ALIGNOF(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg));
	(*T1_).kind = ((tyEnum_JsonNodeKind__k9adLs9b9b0zH29baARdDeUL5A)1);
	colontmpD_ = b_p0;
	(*T1_)._kind_4.bval = colontmpD_;
	result = T1_;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg*, percent___pureZjson_u2105)(NimStringV2 s_p0) {
	tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* result;
	NimStringV2 colontmpD_;
	tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* T1_;
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	T1_ = NIM_NIL;
	T1_ = (tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg*) nimNewObj(sizeof(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg), NIM_ALIGNOF(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg));
	(*T1_).kind = ((tyEnum_JsonNodeKind__k9adLs9b9b0zH29baARdDeUL5A)4);
	colontmpD_ = eqdup___system_u2613(s_p0);
	(*T1_)._kind_1.str = colontmpD_;
	result = T1_;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg*, newJArray__pureZjson_u474)(void) {
	tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* result;
	tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* T1_;
	T1_ = NIM_NIL;
	T1_ = (tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg*) nimNewObj(sizeof(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg), NIM_ALIGNOF(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg));
	(*T1_).kind = ((tyEnum_JsonNodeKind__k9adLs9b9b0zH29baARdDeUL5A)6);
	(*T1_)._kind_7.elems.len = 0; (*T1_)._kind_7.elems.p = (tySequence__jKinQKK5sMW4kMIzl4PsKQ_Content*) newSeqPayload(0, sizeof(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg*), NIM_ALIGNOF(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg*));
	result = T1_;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, add__pureZjson_u612)(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* father_p0, tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* child_p1) {
	tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* colontmpD_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	colontmpD_ = NIM_NIL;
	colontmpD_ = eqdup___pureZjson_u308(child_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	add__pureZjson_u622((&(*father_p0)._kind_7.elems), colontmpD_);
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZjson_u302)(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLast(dest_p0);
		if (!T3_) goto LA4_;
		eqdestroy___pureZjson_u64(dest_p0);
		nimRawDispose(dest_p0, ((NI)8));
	}
LA4_: ;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg*, percent___pureZjson_u2134)(tyTuple__yeSFujPok8SfAGi9apNECrw* keyVals_p0, NI keyVals_p0Len_0) {
	tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* result;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = NIM_NIL;
	{
		if (!(keyVals_p0Len_0 == ((NI)0))) goto LA3_;
		result = newJArray__pureZjson_u474();
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		goto BeforeRet_;
	}
LA3_: ;
	result = newJObject__pureZjson_u414();
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	{
		NimStringV2* key_1;
		tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg** val_1;
		NI i_1;
		key_1 = (NimStringV2*)0;
		val_1 = (tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg**)0;
		i_1 = ((NI)0);
		{
			while (1) {
				tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* colontmpD_;
				if (!(i_1 < keyVals_p0Len_0)) goto LA7;
				colontmpD_ = NIM_NIL;
				key_1 = (&keyVals_p0[i_1].Field0);
				val_1 = &keyVals_p0[i_1].Field1;
				colontmpD_ = eqdup___pureZjson_u308((*val_1));
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				X5BX5Deq___pureZjson_u689((&(*result)._kind_6.fields), (*key_1), colontmpD_);
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				i_1 += ((NI)1);
			} LA7: ;
		}
	}
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg*, newJString__pureZjson_u42)(NimStringV2 s_p0) {
	tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* result;
	NimStringV2 colontmpD_;
	tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* T1_;
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	T1_ = NIM_NIL;
	T1_ = (tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg*) nimNewObj(sizeof(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg), NIM_ALIGNOF(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg));
	(*T1_).kind = ((tyEnum_JsonNodeKind__k9adLs9b9b0zH29baARdDeUL5A)4);
	colontmpD_ = eqdup___system_u2613(s_p0);
	(*T1_)._kind_1.str = colontmpD_;
	result = T1_;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg*, percent___pureZjson_u2128)(NF n_p0) {
	tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* result;
	tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* T1_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = NIM_NIL;
	T1_ = NIM_NIL;
	{
		if (!!((n_p0 == n_p0))) goto LA4_;
		result = newJString__pureZjson_u42(TM__9b9bytt1stv9cZ8uqII7HFgew_3);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	goto LA2_;
LA4_: ;
	{
		if (!(n_p0 == INF)) goto LA7_;
		result = newJString__pureZjson_u42(TM__9b9bytt1stv9cZ8uqII7HFgew_5);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	goto LA2_;
LA7_: ;
	{
		if (!(n_p0 == -INF)) goto LA10_;
		result = newJString__pureZjson_u42(TM__9b9bytt1stv9cZ8uqII7HFgew_7);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	goto LA2_;
LA10_: ;
	{
		NF colontmpD_;
		tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* T13_;
		colontmpD_ = (NF)0;
		T13_ = NIM_NIL;
		T13_ = (tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg*) nimNewObj(sizeof(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg), NIM_ALIGNOF(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg));
		(*T13_).kind = ((tyEnum_JsonNodeKind__k9adLs9b9b0zH29baARdDeUL5A)3);
		colontmpD_ = n_p0;
		(*T13_)._kind_3.fnum = colontmpD_;
		result = T13_;
	}
LA2_: ;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(NI, len__pureZjson_u2537)(tyObject_OrderedTable__qEJVXJleSn4PbwLXkdGuEw t_p0) {
	NI result;
	result = t_p0.counter;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, len__pureZjson_u3389)(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* n_p0) {
	NI result;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NI)0;
	switch ((*n_p0).kind) {
	case ((tyEnum_JsonNodeKind__k9adLs9b9b0zH29baARdDeUL5A)6):
	{
		NI T2_;
		T2_ = (*n_p0)._kind_7.elems.len;
		result = T2_;
	}
	break;
	case ((tyEnum_JsonNodeKind__k9adLs9b9b0zH29baARdDeUL5A)5):
	{
		result = len__pureZjson_u2537((*n_p0)._kind_6.fields);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	break;
	default:
	{
		result = ((NI)0);
	}
	break;
	}
	}BeforeRet_: ;
	return result;
}
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest_p0, source_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, copyMem__system_u1731)(void* dest_p0, void* source_p1, NI size_p2) {
	nimCopyMem(dest_p0, source_p1, size_p2);
}
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1) {
	{
		if (!(((NI)0) < src_p1.len)) goto LA3_;
		copyMem__system_u1731(((void*) ((&(*(*dest_p0).p).data[(*dest_p0).len]))), ((void*) ((&(*src_p1.p).data[((NI)0)]))), (src_p1.len));
		(*dest_p0).len += src_p1.len;
		(*(*dest_p0).p).data[(*dest_p0).len] = 0;
	}
LA3_: ;
}
static N_INLINE(NIM_BOOL, sameSeqPayload)(void* x_p0, void* y_p1) {
	NIM_BOOL result;
	result = ((*((tyObject_NimRawSeq__9cILcSEMTM25Wr2S8osw5Bw*) (x_p0))).p == (*((tyObject_NimRawSeq__9cILcSEMTM25Wr2S8osw5Bw*) (y_p1))).p);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___pureZjson_u241)(tySequence__jKinQKK5sMW4kMIzl4PsKQ* dest_p0, tySequence__jKinQKK5sMW4kMIzl4PsKQ src_p1) {
	NI T6_;
	NI colontmp_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = sameSeqPayload(dest_p0, (&src_p1));
		if (!T3_) goto LA4_;
		goto BeforeRet_;
	}
LA4_: ;
	T6_ = src_p1.len;
	setLen__pureZjson_u257((&(*dest_p0)), T6_);
	colontmp_ = ((NI)0);
	{
		while (1) {
			NI T9_;
			T9_ = (*dest_p0).len;
			if (!(colontmp_ < T9_)) goto LA8;
			{
				if (!src_p1.p->data[colontmp_]) goto LA12_;
				nimIncRef(src_p1.p->data[colontmp_]);
			}
LA12_: ;
			{
				NIM_BOOL T16_;
				T16_ = (NIM_BOOL)0;
				T16_ = nimDecRefIsLast((*dest_p0).p->data[colontmp_]);
				if (!T16_) goto LA17_;
				eqdestroy___pureZjson_u64((*dest_p0).p->data[colontmp_]);
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				nimRawDispose((*dest_p0).p->data[colontmp_], ((NI)8));
			}
LA17_: ;
			(*dest_p0).p->data[colontmp_] = src_p1.p->data[colontmp_];
			colontmp_ += ((NI)1);
		} LA8: ;
	}
	}BeforeRet_: ;
}
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a_p0, v_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimSetMem__systemZmemory_u7(p_p0, ((int)0), size_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
static N_INLINE(NIM_BOOL, isFilled__pureZcollectionsZtables_u31)(NI hcode_p0) {
	NIM_BOOL result;
	result = !((hcode_p0 == ((NI)0)));
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___pureZjson_u305)(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg** dest_p0, tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* src_p1) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	{
		if (!src_p1) goto LA3_;
		nimIncRef(src_p1);
	}
LA3_: ;
	{
		NIM_BOOL T7_;
		T7_ = (NIM_BOOL)0;
		T7_ = nimDecRefIsLast((*dest_p0));
		if (!T7_) goto LA8_;
		eqdestroy___pureZjson_u64((*dest_p0));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		nimRawDispose((*dest_p0), ((NI)8));
	}
LA8_: ;
	(*dest_p0) = src_p1;
	}BeforeRet_: ;
}
static N_INLINE(void, nimAddCharV1)(NimStringV2* s_p0, NIM_CHAR c_p1) {
	prepareAdd(s_p0, ((NI)1));
	(*(*s_p0).p).data[(*s_p0).len] = c_p1;
	(*s_p0).len += ((NI)1);
	(*(*s_p0).p).data[(*s_p0).len] = 0;
}
N_LIB_PRIVATE N_NIMCALL(void, escapeJsonUnquoted__pureZjson_u4661)(NimStringV2 s_p0, NimStringV2* result_p1) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	{
		NIM_CHAR c_1;
		NI i_1;
		NI L_1;
		c_1 = (NIM_CHAR)0;
		i_1 = ((NI)0);
		L_1 = s_p0.len;
		{
			while (1) {
				if (!(i_1 < L_1)) goto LA3;
				c_1 = s_p0.p->data[i_1];
				switch (((NU8)(c_1))) {
				case 10:
				{
					prepareAdd((&(*result_p1)), 2);
appendString((&(*result_p1)), TM__9b9bytt1stv9cZ8uqII7HFgew_20);
				}
				break;
				case 8:
				{
					prepareAdd((&(*result_p1)), 2);
appendString((&(*result_p1)), TM__9b9bytt1stv9cZ8uqII7HFgew_22);
				}
				break;
				case 12:
				{
					prepareAdd((&(*result_p1)), 2);
appendString((&(*result_p1)), TM__9b9bytt1stv9cZ8uqII7HFgew_24);
				}
				break;
				case 9:
				{
					prepareAdd((&(*result_p1)), 2);
appendString((&(*result_p1)), TM__9b9bytt1stv9cZ8uqII7HFgew_26);
				}
				break;
				case 11:
				{
					prepareAdd((&(*result_p1)), 6);
appendString((&(*result_p1)), TM__9b9bytt1stv9cZ8uqII7HFgew_28);
				}
				break;
				case 13:
				{
					prepareAdd((&(*result_p1)), 2);
appendString((&(*result_p1)), TM__9b9bytt1stv9cZ8uqII7HFgew_30);
				}
				break;
				case 34:
				{
					prepareAdd((&(*result_p1)), 2);
appendString((&(*result_p1)), TM__9b9bytt1stv9cZ8uqII7HFgew_32);
				}
				break;
				case 0 ... 7:
				{
					NimStringV2 colontmpD_;
					NimStringV2 colontmpD__2;
					NimStringV2 T12_;
					colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
					colontmpD__2.len = 0; colontmpD__2.p = NIM_NIL;
					T12_.len = 0; T12_.p = NIM_NIL;
					colontmpD_ = dollar___systemZdollars_u14(((NU8)(c_1)));
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
					T12_ = rawNewString(colontmpD_.len + 5);
appendString((&T12_), TM__9b9bytt1stv9cZ8uqII7HFgew_34);
appendString((&T12_), colontmpD_);
					colontmpD__2 = T12_;
					prepareAdd((&(*result_p1)), colontmpD__2.len + 0);
appendString((&(*result_p1)), colontmpD__2);
					if (colontmpD__2.p && !(colontmpD__2.p->cap & NIM_STRLIT_FLAG)) {
 dealloc(colontmpD__2.p);
}
					if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 dealloc(colontmpD_.p);
}
				}
				break;
				case 14 ... 31:
				{
					NimStringV2 colontmpD__3;
					NimStringV2 colontmpD__4;
					NimStringV2 T14_;
					colontmpD__3.len = 0; colontmpD__3.p = NIM_NIL;
					colontmpD__4.len = 0; colontmpD__4.p = NIM_NIL;
					T14_.len = 0; T14_.p = NIM_NIL;
					colontmpD__3 = toHex__pureZstrutils_u2082(((NU8)(c_1)), ((NI)2));
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
					T14_ = rawNewString(colontmpD__3.len + 4);
appendString((&T14_), TM__9b9bytt1stv9cZ8uqII7HFgew_36);
appendString((&T14_), colontmpD__3);
					colontmpD__4 = T14_;
					prepareAdd((&(*result_p1)), colontmpD__4.len + 0);
appendString((&(*result_p1)), colontmpD__4);
					if (colontmpD__4.p && !(colontmpD__4.p->cap & NIM_STRLIT_FLAG)) {
 dealloc(colontmpD__4.p);
}
					if (colontmpD__3.p && !(colontmpD__3.p->cap & NIM_STRLIT_FLAG)) {
 dealloc(colontmpD__3.p);
}
				}
				break;
				case 92:
				{
					prepareAdd((&(*result_p1)), 2);
appendString((&(*result_p1)), TM__9b9bytt1stv9cZ8uqII7HFgew_38);
				}
				break;
				default:
				{
					nimAddCharV1((&(*result_p1)), c_1);
				}
				break;
				}
				i_1 += ((NI)1);
			} LA3: ;
		}
	}
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, escapeJson__pureZjson_u4682)(NimStringV2 s_p0, NimStringV2* result_p1) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	prepareAdd((&(*result_p1)), 1);
appendString((&(*result_p1)), TM__9b9bytt1stv9cZ8uqII7HFgew_18);
	escapeJsonUnquoted__pureZjson_u4661(s_p0, result_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	prepareAdd((&(*result_p1)), 1);
appendString((&(*result_p1)), TM__9b9bytt1stv9cZ8uqII7HFgew_39);
	}BeforeRet_: ;
}
static N_INLINE(void, addFloat__system_u3947)(NimStringV2* result_p0, NF x_p1) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	addFloatRoundtrip__system_u3952(result_p0, x_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, toUgly__pureZjson_u4692)(NimStringV2* result_p0, tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* node_p1) {
	NIM_BOOL comma_1;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	comma_1 = NIM_FALSE;
	switch ((*node_p1).kind) {
	case ((tyEnum_JsonNodeKind__k9adLs9b9b0zH29baARdDeUL5A)6):
	{
		prepareAdd((&(*result_p0)), 1);
appendString((&(*result_p0)), TM__9b9bytt1stv9cZ8uqII7HFgew_9);
		{
			tySequence__jKinQKK5sMW4kMIzl4PsKQ colontmp_;
			tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg** child_1;
			NI i_1;
			NI L_1;
			NI T3_;
			colontmp_.len = 0; colontmp_.p = NIM_NIL;
			child_1 = (tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg**)0;
			eqcopy___pureZjson_u241((&colontmp_), (*node_p1)._kind_7.elems);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			i_1 = ((NI)0);
			T3_ = colontmp_.len;
			L_1 = T3_;
			{
				while (1) {
					if (!(i_1 < L_1)) goto LA5;
					child_1 = &colontmp_.p->data[i_1];
					{
						if (!comma_1) goto LA8_;
						prepareAdd((&(*result_p0)), 1);
appendString((&(*result_p0)), TM__9b9bytt1stv9cZ8uqII7HFgew_11);
					}
					goto LA6_;
LA8_: ;
					{
						comma_1 = NIM_TRUE;
					}
LA6_: ;
					toUgly__pureZjson_u4692(result_p0, (*child_1));
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
					i_1 += ((NI)1);
				} LA5: ;
			}
			eqdestroy___pureZjson_u238(colontmp_);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		}
		prepareAdd((&(*result_p0)), 1);
appendString((&(*result_p0)), TM__9b9bytt1stv9cZ8uqII7HFgew_13);
	}
	break;
	case ((tyEnum_JsonNodeKind__k9adLs9b9b0zH29baARdDeUL5A)5):
	{
		prepareAdd((&(*result_p0)), 1);
appendString((&(*result_p0)), TM__9b9bytt1stv9cZ8uqII7HFgew_15);
		{
			NimStringV2 key_1;
			tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* value_1;
			tyObject_OrderedTable__qEJVXJleSn4PbwLXkdGuEw colontmp__2;
			NI L_2;
			key_1.len = 0; key_1.p = NIM_NIL;
			value_1 = NIM_NIL;
			nimZeroMem((void*)(&colontmp__2), sizeof(tyObject_OrderedTable__qEJVXJleSn4PbwLXkdGuEw));
			eqcopy___pureZjson_u460((&colontmp__2), (*node_p1)._kind_6.fields);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			L_2 = len__pureZjson_u2537(colontmp__2);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			{
				NI h_1;
				if (!(((NI)0) < colontmp__2.counter)) goto LA15_;
				h_1 = colontmp__2.first;
				{
					while (1) {
						NI nxt_1;
						if (!(((NI)0) <= h_1)) goto LA18;
						nxt_1 = colontmp__2.data.p->data[h_1].Field1;
						{
							NIM_BOOL T21_;
							T21_ = (NIM_BOOL)0;
							T21_ = isFilled__pureZcollectionsZtables_u31(colontmp__2.data.p->data[h_1].Field0);
							if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
							if (!T21_) goto LA22_;
							eqcopy___system_u2610((&key_1), colontmp__2.data.p->data[h_1].Field2);
							eqcopy___pureZjson_u305(&value_1, colontmp__2.data.p->data[h_1].Field3);
							if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
							{
								if (!comma_1) goto LA26_;
								prepareAdd((&(*result_p0)), 1);
appendString((&(*result_p0)), TM__9b9bytt1stv9cZ8uqII7HFgew_16);
							}
							goto LA24_;
LA26_: ;
							{
								comma_1 = NIM_TRUE;
							}
LA24_: ;
							escapeJson__pureZjson_u4682(key_1, result_p0);
							if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
							prepareAdd((&(*result_p0)), 1);
appendString((&(*result_p0)), TM__9b9bytt1stv9cZ8uqII7HFgew_41);
							toUgly__pureZjson_u4692(result_p0, value_1);
							if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
						}
LA22_: ;
						h_1 = nxt_1;
					} LA18: ;
				}
			}
LA15_: ;
			eqdestroy___pureZjson_u457((&colontmp__2));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			eqdestroy___pureZjson_u302(value_1);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			if (key_1.p && !(key_1.p->cap & NIM_STRLIT_FLAG)) {
 dealloc(key_1.p);
}
		}
		prepareAdd((&(*result_p0)), 1);
appendString((&(*result_p0)), TM__9b9bytt1stv9cZ8uqII7HFgew_43);
	}
	break;
	case ((tyEnum_JsonNodeKind__k9adLs9b9b0zH29baARdDeUL5A)4):
	{
		{
			if (!(*node_p1).isUnquoted) goto LA32_;
			prepareAdd((&(*result_p0)), (*node_p1)._kind_1.str.len + 0);
appendString((&(*result_p0)), (*node_p1)._kind_1.str);
		}
		goto LA30_;
LA32_: ;
		{
			escapeJson__pureZjson_u4682((*node_p1)._kind_1.str, result_p0);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		}
LA30_: ;
	}
	break;
	case ((tyEnum_JsonNodeKind__k9adLs9b9b0zH29baARdDeUL5A)2):
	{
		addInt__stdZprivateZdigitsutils_u178(result_p0, (*node_p1)._kind_2.num);
	}
	break;
	case ((tyEnum_JsonNodeKind__k9adLs9b9b0zH29baARdDeUL5A)3):
	{
		addFloat__system_u3947(result_p0, (*node_p1)._kind_3.fnum);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	break;
	case ((tyEnum_JsonNodeKind__k9adLs9b9b0zH29baARdDeUL5A)1):
	{
		NimStringV2 colontmpD_;
		NimStringV2 colontmpD__2;
		NimStringV2 T38_;
		colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
		colontmpD__2.len = 0; colontmpD__2.p = NIM_NIL;
		T38_.len = 0; T38_.p = NIM_NIL;
		{
			if (!(*node_p1)._kind_4.bval) goto LA41_;
			colontmpD_ = TM__9b9bytt1stv9cZ8uqII7HFgew_45;
			T38_ = colontmpD_;
		}
		goto LA39_;
LA41_: ;
		{
			colontmpD__2 = TM__9b9bytt1stv9cZ8uqII7HFgew_47;
			T38_ = colontmpD__2;
		}
LA39_: ;
		prepareAdd((&(*result_p0)), T38_.len + 0);
appendString((&(*result_p0)), T38_);
		if (colontmpD__2.p && !(colontmpD__2.p->cap & NIM_STRLIT_FLAG)) {
 dealloc(colontmpD__2.p);
}
		if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 dealloc(colontmpD_.p);
}
	}
	break;
	case ((tyEnum_JsonNodeKind__k9adLs9b9b0zH29baARdDeUL5A)0):
	{
		prepareAdd((&(*result_p0)), 4);
appendString((&(*result_p0)), TM__9b9bytt1stv9cZ8uqII7HFgew_49);
	}
	break;
	default: __builtin_unreachable();
	}
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___pureZjson_u4792)(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* node_p0) {
	NimStringV2 result;
	NI T1_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	T1_ = (NI)0;
	T1_ = len__pureZjson_u3389(node_p0);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	result = rawNewString(((NI)((NU32)(T1_) << (NU32)(((NI)1)))));
	toUgly__pureZjson_u4692((&result), node_p0);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg*, newJRawNumber__pureZjson_u400)(NimStringV2 s_p0) {
	tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* result;
	NimStringV2 colontmpD_;
	tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* T1_;
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	T1_ = NIM_NIL;
	T1_ = (tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg*) nimNewObjUninit(sizeof(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg), NIM_ALIGNOF(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg));
	(*T1_).kind = ((tyEnum_JsonNodeKind__k9adLs9b9b0zH29baARdDeUL5A)4);
	colontmpD_ = eqdup___system_u2613(s_p0);
	(*T1_)._kind_1.str = colontmpD_;
	(*T1_).isUnquoted = NIM_TRUE;
	result = T1_;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg*, newJInt__pureZjson_u403)(NI64 n_p0) {
	tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* result;
	NI64 colontmpD_;
	tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* T1_;
	colontmpD_ = (NI64)0;
	T1_ = NIM_NIL;
	T1_ = (tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg*) nimNewObj(sizeof(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg), NIM_ALIGNOF(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg));
	(*T1_).kind = ((tyEnum_JsonNodeKind__k9adLs9b9b0zH29baARdDeUL5A)2);
	colontmpD_ = n_p0;
	(*T1_)._kind_2.num = colontmpD_;
	result = T1_;
	return result;
}
static N_INLINE(NIM_BOOL, isObjDisplayCheck)(TNimTypeV2* source_p0, NI16 targetDepth_p1, NU32 token_p2) {
	NIM_BOOL result;
	NIM_BOOL T1_;
	T1_ = (NIM_BOOL)0;
	T1_ = (targetDepth_p1 <= (*source_p0).depth);
	if (!(T1_)) goto LA2_;
	T1_ = ((*source_p0).display[targetDepth_p1] == token_p2);
LA2_: ;
	result = T1_;
	return result;
}
static N_INLINE(Exception*, nimBorrowCurrentException)(void) {
	Exception* result;
	result = currException__system_u3239;
	return result;
}
static N_INLINE(void, popCurrentException)(void) {
	eqcopy___system_u3269(&currException__system_u3239, (*currException__system_u3239).up);
}
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg*, newJFloat__pureZjson_u406)(NF n_p0) {
	tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* result;
	NF colontmpD_;
	tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* T1_;
	colontmpD_ = (NF)0;
	T1_ = NIM_NIL;
	T1_ = (tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg*) nimNewObj(sizeof(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg), NIM_ALIGNOF(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg));
	(*T1_).kind = ((tyEnum_JsonNodeKind__k9adLs9b9b0zH29baARdDeUL5A)3);
	colontmpD_ = n_p0;
	(*T1_)._kind_3.fnum = colontmpD_;
	result = T1_;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg*, newJBool__pureZjson_u409)(NIM_BOOL b_p0) {
	tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* result;
	NIM_BOOL colontmpD_;
	tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* T1_;
	colontmpD_ = (NIM_BOOL)0;
	T1_ = NIM_NIL;
	T1_ = (tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg*) nimNewObj(sizeof(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg), NIM_ALIGNOF(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg));
	(*T1_).kind = ((tyEnum_JsonNodeKind__k9adLs9b9b0zH29baARdDeUL5A)1);
	colontmpD_ = b_p0;
	(*T1_)._kind_4.bval = colontmpD_;
	result = T1_;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg*, newJNull__pureZjson_u412)(void) {
	tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* result;
	tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* T1_;
	T1_ = NIM_NIL;
	T1_ = (tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg*) nimNewObj(sizeof(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg), NIM_ALIGNOF(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg));
	(*T1_).kind = ((tyEnum_JsonNodeKind__k9adLs9b9b0zH29baARdDeUL5A)0);
	result = T1_;
	return result;
}
static N_INLINE(void, X5BX5Deq___pureZjson_u2249)(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* obj_p0, NimStringV2 key_p1, tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* val_p2) {
	tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* colontmpD_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	colontmpD_ = NIM_NIL;
	colontmpD_ = eqdup___pureZjson_u308(val_p2);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	X5BX5Deq___pureZjson_u689((&(*obj_p0)._kind_6.fields), key_p1, colontmpD_);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg*, parseJson__pureZjson_u5485)(tyObject_JsonParser__quW1I9aCxKWHT6UgEfPIy2Q* p_p0, NIM_BOOL rawIntegers_p1, NIM_BOOL rawFloats_p2, NI depth_p3) {
	tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* result;
NIM_BOOL oldNimErrFin51_;
NIM_BOOL oldNimErrFin74_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = NIM_NIL;
	switch ((*p_p0).tok) {
	case ((tyEnum_TokKind__ASGiPTHO0n9bhCozD9afmTaQ)2):
	{
		tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* T2_;
		tyEnum_TokKind__ASGiPTHO0n9bhCozD9afmTaQ T3_;
		T2_ = NIM_NIL;
		T2_ = (tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg*) nimNewObj(sizeof(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg), NIM_ALIGNOF(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg));
		(*T2_).kind = ((tyEnum_JsonNodeKind__k9adLs9b9b0zH29baARdDeUL5A)4);
		(*T2_)._kind_1.str = (*p_p0).a;
		eqwasMoved___system_u2607((&(*p_p0).a));
		result = T2_;
		T3_ = (tyEnum_TokKind__ASGiPTHO0n9bhCozD9afmTaQ)0;
		T3_ = getTok__pureZparsejson_u629(p_p0);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		(void)(T3_);
	}
	break;
	case ((tyEnum_TokKind__ASGiPTHO0n9bhCozD9afmTaQ)3):
	{
		tyEnum_TokKind__ASGiPTHO0n9bhCozD9afmTaQ T17_;
		{
			if (!rawIntegers_p1) goto LA7_;
			result = newJRawNumber__pureZjson_u400((*p_p0).a);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		}
		goto LA5_;
LA7_: ;
		{
			NI64 T11_;
			tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* T12_;
			T11_ = (NI64)0;
			T11_ = nsuParseBiggestInt((*p_p0).a);
			if (NIM_UNLIKELY(*nimErr_)) goto LA10_;
			T12_ = NIM_NIL;
			T12_ = newJInt__pureZjson_u403(T11_);
			if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___pureZjson_u302(T12_); goto LA10_;}
			result = T12_;
			if (NIM_UNLIKELY(*nimErr_)) {
				LA10_:;
				if (isObjDisplayCheck(nimBorrowCurrentException()->Sup.m_type, 3, 186794752)) {
					tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* T16_;
					*nimErr_ = NIM_FALSE;
					T16_ = NIM_NIL;
					T16_ = newJRawNumber__pureZjson_u400((*p_p0).a);
					if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___pureZjson_u302(T16_); goto LA14_;}
					result = T16_;
					popCurrentException();
					LA14_:;
				}
			}
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		}
LA5_: ;
		T17_ = (tyEnum_TokKind__ASGiPTHO0n9bhCozD9afmTaQ)0;
		T17_ = getTok__pureZparsejson_u629(p_p0);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		(void)(T17_);
	}
	break;
	case ((tyEnum_TokKind__ASGiPTHO0n9bhCozD9afmTaQ)4):
	{
		tyEnum_TokKind__ASGiPTHO0n9bhCozD9afmTaQ T32_;
		{
			tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* T23_;
			if (!rawFloats_p2) goto LA21_;
			T23_ = NIM_NIL;
			T23_ = newJRawNumber__pureZjson_u400((*p_p0).a);
			if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___pureZjson_u302(T23_); goto BeforeRet_;}
			result = T23_;
		}
		goto LA19_;
LA21_: ;
		{
			NF T26_;
			tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* T27_;
			T26_ = (NF)0;
			T26_ = nsuParseFloat((*p_p0).a);
			if (NIM_UNLIKELY(*nimErr_)) goto LA25_;
			T27_ = NIM_NIL;
			T27_ = newJFloat__pureZjson_u406(T26_);
			if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___pureZjson_u302(T27_); goto LA25_;}
			result = T27_;
			if (NIM_UNLIKELY(*nimErr_)) {
				LA25_:;
				if (isObjDisplayCheck(nimBorrowCurrentException()->Sup.m_type, 3, 186794752)) {
					tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* T31_;
					*nimErr_ = NIM_FALSE;
					T31_ = NIM_NIL;
					T31_ = newJRawNumber__pureZjson_u400((*p_p0).a);
					if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___pureZjson_u302(T31_); goto LA29_;}
					result = T31_;
					popCurrentException();
					LA29_:;
				}
			}
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		}
LA19_: ;
		T32_ = (tyEnum_TokKind__ASGiPTHO0n9bhCozD9afmTaQ)0;
		T32_ = getTok__pureZparsejson_u629(p_p0);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		(void)(T32_);
	}
	break;
	case ((tyEnum_TokKind__ASGiPTHO0n9bhCozD9afmTaQ)5):
	{
		tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* T34_;
		tyEnum_TokKind__ASGiPTHO0n9bhCozD9afmTaQ T35_;
		T34_ = NIM_NIL;
		T34_ = newJBool__pureZjson_u409(NIM_TRUE);
		if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___pureZjson_u302(T34_); goto BeforeRet_;}
		result = T34_;
		T35_ = (tyEnum_TokKind__ASGiPTHO0n9bhCozD9afmTaQ)0;
		T35_ = getTok__pureZparsejson_u629(p_p0);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		(void)(T35_);
	}
	break;
	case ((tyEnum_TokKind__ASGiPTHO0n9bhCozD9afmTaQ)6):
	{
		tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* T37_;
		tyEnum_TokKind__ASGiPTHO0n9bhCozD9afmTaQ T38_;
		T37_ = NIM_NIL;
		T37_ = newJBool__pureZjson_u409(NIM_FALSE);
		if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___pureZjson_u302(T37_); goto BeforeRet_;}
		result = T37_;
		T38_ = (tyEnum_TokKind__ASGiPTHO0n9bhCozD9afmTaQ)0;
		T38_ = getTok__pureZparsejson_u629(p_p0);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		(void)(T38_);
	}
	break;
	case ((tyEnum_TokKind__ASGiPTHO0n9bhCozD9afmTaQ)7):
	{
		tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* T40_;
		tyEnum_TokKind__ASGiPTHO0n9bhCozD9afmTaQ T41_;
		T40_ = NIM_NIL;
		T40_ = newJNull__pureZjson_u412();
		if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___pureZjson_u302(T40_); goto BeforeRet_;}
		result = T40_;
		T41_ = (tyEnum_TokKind__ASGiPTHO0n9bhCozD9afmTaQ)0;
		T41_ = getTok__pureZparsejson_u629(p_p0);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		(void)(T41_);
	}
	break;
	case ((tyEnum_TokKind__ASGiPTHO0n9bhCozD9afmTaQ)8):
	{
		tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* T47_;
		tyEnum_TokKind__ASGiPTHO0n9bhCozD9afmTaQ T48_;
		{
			if (!(((NI)1000) < depth_p3)) goto LA45_;
			raiseParseErr__pureZparsejson_u820((&(*p_p0)), TM__9b9bytt1stv9cZ8uqII7HFgew_50);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		}
LA45_: ;
		T47_ = NIM_NIL;
		T47_ = newJObject__pureZjson_u414();
		if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___pureZjson_u302(T47_); goto BeforeRet_;}
		result = T47_;
		T48_ = (tyEnum_TokKind__ASGiPTHO0n9bhCozD9afmTaQ)0;
		T48_ = getTok__pureZparsejson_u629(p_p0);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		(void)(T48_);
		{
			while (1) {
				NimStringV2 key_1;
				tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* val_1;
				tyEnum_TokKind__ASGiPTHO0n9bhCozD9afmTaQ T56_;
				tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* T57_;
				tyEnum_TokKind__ASGiPTHO0n9bhCozD9afmTaQ T62_;
				if (!!(((*p_p0).tok == ((tyEnum_TokKind__ASGiPTHO0n9bhCozD9afmTaQ)9)))) goto LA50;
				key_1.len = 0; key_1.p = NIM_NIL;
				val_1 = NIM_NIL;
				{
					if (!!(((*p_p0).tok == ((tyEnum_TokKind__ASGiPTHO0n9bhCozD9afmTaQ)2)))) goto LA54_;
					raiseParseErr__pureZparsejson_u820((&(*p_p0)), TM__9b9bytt1stv9cZ8uqII7HFgew_52);
					if (NIM_UNLIKELY(*nimErr_)) goto LA51_;
				}
LA54_: ;
				eqcopy___system_u2610((&key_1), (*p_p0).a);
				T56_ = (tyEnum_TokKind__ASGiPTHO0n9bhCozD9afmTaQ)0;
				T56_ = getTok__pureZparsejson_u629(p_p0);
				if (NIM_UNLIKELY(*nimErr_)) goto LA51_;
				(void)(T56_);
				eat__pureZparsejson_u868(p_p0, ((tyEnum_TokKind__ASGiPTHO0n9bhCozD9afmTaQ)12));
				if (NIM_UNLIKELY(*nimErr_)) goto LA51_;
				T57_ = NIM_NIL;
				T57_ = parseJson__pureZjson_u5485(p_p0, rawIntegers_p1, rawFloats_p2, (NI)(depth_p3 + ((NI)1)));
				if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___pureZjson_u302(T57_); goto LA51_;}
				val_1 = T57_;
				X5BX5Deq___pureZjson_u2249(result, key_1, val_1);
				if (NIM_UNLIKELY(*nimErr_)) goto LA51_;
				{
					if (!!(((*p_p0).tok == ((tyEnum_TokKind__ASGiPTHO0n9bhCozD9afmTaQ)13)))) goto LA60_;
					eqdestroy___pureZjson_u302(val_1);
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
					if (key_1.p && !(key_1.p->cap & NIM_STRLIT_FLAG)) {
 dealloc(key_1.p);
}
					goto LA49;
				}
LA60_: ;
				T62_ = (tyEnum_TokKind__ASGiPTHO0n9bhCozD9afmTaQ)0;
				T62_ = getTok__pureZparsejson_u629(p_p0);
				if (NIM_UNLIKELY(*nimErr_)) goto LA51_;
				(void)(T62_);
				{
					LA51_:;
				}
				{
					oldNimErrFin51_ = *nimErr_; *nimErr_ = NIM_FALSE;
					eqdestroy___pureZjson_u302(val_1);
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
					if (key_1.p && !(key_1.p->cap & NIM_STRLIT_FLAG)) {
 dealloc(key_1.p);
}
					*nimErr_ = oldNimErrFin51_;
				}
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			} LA50: ;
		} LA49: ;
		eat__pureZparsejson_u868(p_p0, ((tyEnum_TokKind__ASGiPTHO0n9bhCozD9afmTaQ)9));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	break;
	case ((tyEnum_TokKind__ASGiPTHO0n9bhCozD9afmTaQ)10):
	{
		tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* T70_;
		tyEnum_TokKind__ASGiPTHO0n9bhCozD9afmTaQ T71_;
		{
			if (!(((NI)1000) < depth_p3)) goto LA68_;
			raiseParseErr__pureZparsejson_u820((&(*p_p0)), TM__9b9bytt1stv9cZ8uqII7HFgew_53);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		}
LA68_: ;
		T70_ = NIM_NIL;
		T70_ = newJArray__pureZjson_u474();
		if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___pureZjson_u302(T70_); goto BeforeRet_;}
		result = T70_;
		T71_ = (tyEnum_TokKind__ASGiPTHO0n9bhCozD9afmTaQ)0;
		T71_ = getTok__pureZparsejson_u629(p_p0);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		(void)(T71_);
		{
			while (1) {
				tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* colontmpD_;
				tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* T75_;
				tyEnum_TokKind__ASGiPTHO0n9bhCozD9afmTaQ T80_;
				if (!!(((*p_p0).tok == ((tyEnum_TokKind__ASGiPTHO0n9bhCozD9afmTaQ)11)))) goto LA73;
				colontmpD_ = NIM_NIL;
				T75_ = NIM_NIL;
				T75_ = parseJson__pureZjson_u5485(p_p0, rawIntegers_p1, rawFloats_p2, (NI)(depth_p3 + ((NI)1)));
				if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___pureZjson_u302(T75_); goto LA74_;}
				colontmpD_ = T75_;
				add__pureZjson_u612(result, colontmpD_);
				if (NIM_UNLIKELY(*nimErr_)) goto LA74_;
				{
					if (!!(((*p_p0).tok == ((tyEnum_TokKind__ASGiPTHO0n9bhCozD9afmTaQ)13)))) goto LA78_;
					eqdestroy___pureZjson_u302(colontmpD_);
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
					goto LA72;
				}
LA78_: ;
				T80_ = (tyEnum_TokKind__ASGiPTHO0n9bhCozD9afmTaQ)0;
				T80_ = getTok__pureZparsejson_u629(p_p0);
				if (NIM_UNLIKELY(*nimErr_)) goto LA74_;
				(void)(T80_);
				{
					LA74_:;
				}
				{
					oldNimErrFin74_ = *nimErr_; *nimErr_ = NIM_FALSE;
					eqdestroy___pureZjson_u302(colontmpD_);
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
					*nimErr_ = oldNimErrFin74_;
				}
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			} LA73: ;
		} LA72: ;
		eat__pureZparsejson_u868(p_p0, ((tyEnum_TokKind__ASGiPTHO0n9bhCozD9afmTaQ)11));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	break;
	case ((tyEnum_TokKind__ASGiPTHO0n9bhCozD9afmTaQ)0):
	case ((tyEnum_TokKind__ASGiPTHO0n9bhCozD9afmTaQ)9):
	case ((tyEnum_TokKind__ASGiPTHO0n9bhCozD9afmTaQ)11):
	case ((tyEnum_TokKind__ASGiPTHO0n9bhCozD9afmTaQ)12):
	case ((tyEnum_TokKind__ASGiPTHO0n9bhCozD9afmTaQ)13):
	case ((tyEnum_TokKind__ASGiPTHO0n9bhCozD9afmTaQ)1):
	{
		raiseParseErr__pureZparsejson_u820((&(*p_p0)), TM__9b9bytt1stv9cZ8uqII7HFgew_54);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	break;
	default: __builtin_unreachable();
	}
	}BeforeRet_: ;
	return result;
}
static N_INLINE(void, close__pureZparsejson_u288)(tyObject_JsonParser__quW1I9aCxKWHT6UgEfPIy2Q* my_p0) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	close__pureZlexbase_u14(&my_p0->Sup);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg*, parseJson__pureZjson_u5531)(tyObject_StreamObj__r1XfanY7DoimMbYEDg3nww* s_p0, NimStringV2 filename_p1, NIM_BOOL rawIntegers_p2, NIM_BOOL rawFloats_p3) {
	tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* result;
	tyObject_JsonParser__quW1I9aCxKWHT6UgEfPIy2Q p_1;
	tyEnum_TokKind__ASGiPTHO0n9bhCozD9afmTaQ T3_;
NIM_BOOL oldNimErrFin2_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = NIM_NIL;
	nimZeroMem((void*)(&p_1), sizeof(tyObject_JsonParser__quW1I9aCxKWHT6UgEfPIy2Q));
	p_1.Sup.Sup.m_type = (&NTIv2__quW1I9aCxKWHT6UgEfPIy2Q_);
	nimZeroMem((void*)(&p_1), sizeof(tyObject_JsonParser__quW1I9aCxKWHT6UgEfPIy2Q));
	p_1.Sup.Sup.m_type = (&NTIv2__quW1I9aCxKWHT6UgEfPIy2Q_);
	open__pureZparsejson_u79((&p_1), s_p0, filename_p1, NIM_FALSE);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	T3_ = (tyEnum_TokKind__ASGiPTHO0n9bhCozD9afmTaQ)0;
	T3_ = getTok__pureZparsejson_u629((&p_1));
	if (NIM_UNLIKELY(*nimErr_)) goto LA2_;
	(void)(T3_);
	result = parseJson__pureZjson_u5485((&p_1), rawIntegers_p2, rawFloats_p3, ((NI)0));
	if (NIM_UNLIKELY(*nimErr_)) goto LA2_;
	eat__pureZparsejson_u868((&p_1), ((tyEnum_TokKind__ASGiPTHO0n9bhCozD9afmTaQ)1));
	if (NIM_UNLIKELY(*nimErr_)) goto LA2_;
	{
		LA2_:;
	}
	{
		oldNimErrFin2_ = *nimErr_; *nimErr_ = NIM_FALSE;
		close__pureZparsejson_u288((&p_1));
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		*nimErr_ = oldNimErrFin2_;
	}
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	{
		LA1_:;
	}
	{
		eqdestroy___pureZparsejson_u121((&p_1));
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg*, parseJson__pureZjson_u5542)(NimStringV2 buffer_p0, NIM_BOOL rawIntegers_p1, NIM_BOOL rawFloats_p2) {
	tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* result;
	NimStringV2 colontmpD_;
	tyObject_StringStreamObj__Pvdcjy1h9bpZgErN5j9aQ8kg* colontmpD__2;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = NIM_NIL;
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	colontmpD__2 = NIM_NIL;
	colontmpD_ = eqdup___system_u2613(buffer_p0);
	colontmpD__2 = newStringStream__pureZstreams_u899(colontmpD_);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	result = parseJson__pureZjson_u5531((*((tyObject_StreamObj__r1XfanY7DoimMbYEDg3nww**) (&(colontmpD__2)))), TM__9b9bytt1stv9cZ8uqII7HFgew_56, rawIntegers_p1, rawFloats_p2);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	{
		LA1_:;
	}
	{
		eqdestroy___pureZstreams_u704(colontmpD__2);
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, getInt__pureZjson_u528)(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* n_p0, NI default_p1) {
	NI result;
{	result = (NI)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (n_p0 == 0);
		if (T3_) goto LA4_;
		T3_ = !(((*n_p0).kind == ((tyEnum_JsonNodeKind__k9adLs9b9b0zH29baARdDeUL5A)2)));
LA4_: ;
		if (!T3_) goto LA5_;
		result = default_p1;
		goto BeforeRet_;
	}
	goto LA1_;
LA5_: ;
	{
		result = ((NI) ((*n_p0)._kind_2.num));
		goto BeforeRet_;
	}
LA1_: ;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, getBool__pureZjson_u557)(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* n_p0, NIM_BOOL default_p1) {
	NIM_BOOL result;
{	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (n_p0 == 0);
		if (T3_) goto LA4_;
		T3_ = !(((*n_p0).kind == ((tyEnum_JsonNodeKind__k9adLs9b9b0zH29baARdDeUL5A)1)));
LA4_: ;
		if (!T3_) goto LA5_;
		result = default_p1;
		goto BeforeRet_;
	}
	goto LA1_;
LA5_: ;
	{
		result = (*n_p0)._kind_4.bval;
		goto BeforeRet_;
	}
LA1_: ;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, getStr__pureZjson_u516)(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* n_p0, NimStringV2 default_p1) {
	NimStringV2 result;
{	result.len = 0; result.p = NIM_NIL;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (n_p0 == 0);
		if (T3_) goto LA4_;
		T3_ = !(((*n_p0).kind == ((tyEnum_JsonNodeKind__k9adLs9b9b0zH29baARdDeUL5A)4)));
LA4_: ;
		if (!T3_) goto LA5_;
		eqcopy___system_u2610((&result), default_p1);
		goto BeforeRet_;
	}
	goto LA1_;
LA5_: ;
	{
		eqcopy___system_u2610((&result), (*n_p0)._kind_1.str);
		goto BeforeRet_;
	}
LA1_: ;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, hasKey__pureZjson_u3544)(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* node_p0, NimStringV2 key_p1) {
	NIM_BOOL result;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NIM_BOOL)0;
	result = hasKey__pureZjson_u2941((*node_p0)._kind_6.fields, key_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI64, getBiggestInt__pureZjson_u539)(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* n_p0, NI64 default_p1) {
	NI64 result;
{	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (n_p0 == 0);
		if (T3_) goto LA4_;
		T3_ = !(((*n_p0).kind == ((tyEnum_JsonNodeKind__k9adLs9b9b0zH29baARdDeUL5A)2)));
LA4_: ;
		if (!T3_) goto LA5_;
		result = default_p1;
		goto BeforeRet_;
	}
	goto LA1_;
LA5_: ;
	{
		result = (*n_p0)._kind_2.num;
		goto BeforeRet_;
	}
LA1_: ;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NF, getFloat__pureZjson_u550)(tyObject_JsonNodeObj__9aYOw7IIFWWbbytLff9a69cEg* n_p0, NF default_p1) {
	NF result;
{	{
		if (!(n_p0 == 0)) goto LA3_;
		result = default_p1;
		goto BeforeRet_;
	}
LA3_: ;
	switch ((*n_p0).kind) {
	case ((tyEnum_JsonNodeKind__k9adLs9b9b0zH29baARdDeUL5A)3):
	{
		result = (*n_p0)._kind_3.fnum;
		goto BeforeRet_;
	}
	break;
	case ((tyEnum_JsonNodeKind__k9adLs9b9b0zH29baARdDeUL5A)2):
	{
		result = ((NF) ((*n_p0)._kind_2.num));
		goto BeforeRet_;
	}
	break;
	default:
	{
		result = default_p1;
		goto BeforeRet_;
	}
	break;
	}
	}BeforeRet_: ;
	return result;
}
