/* Generated by Nim Compiler v2.2.4 */
#define NIM_INTBITS 32
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct tyObject_ValueObj__GvkVL3gYndVcF1SEP1HhDQ tyObject_ValueObj__GvkVL3gYndVcF1SEP1HhDQ;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tySequence__FZ9ca77725E4Q3UZTxnRAkA tySequence__FZ9ca77725E4Q3UZTxnRAkA;
typedef struct tySequence__FZ9ca77725E4Q3UZTxnRAkA_Content tySequence__FZ9ca77725E4Q3UZTxnRAkA_Content;
typedef struct tyObject_RefHeader__ZRImJ0JOtQAFc4hlgAu5tA tyObject_RefHeader__ZRImJ0JOtQAFc4hlgAu5tA;
typedef struct tyObject_NimRawSeq__9cILcSEMTM25Wr2S8osw5Bw tyObject_NimRawSeq__9cILcSEMTM25Wr2S8osw5Bw;
typedef struct tyTuple__8SGOCrG9bbn6dwn59ajK9aiRQ tyTuple__8SGOCrG9bbn6dwn59ajK9aiRQ;
typedef NU8 tyEnum_ValueKind__FfLIFKfIB9bQCxObIghtb9bg;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
struct tySequence__FZ9ca77725E4Q3UZTxnRAkA {
  NI len; tySequence__FZ9ca77725E4Q3UZTxnRAkA_Content* p;
};
typedef NU8 tyEnum_ArrElemType__ZAFftDK9bP4RM1cf9a3YJ2FQ;
struct tyObject_ValueObj__GvkVL3gYndVcF1SEP1HhDQ {
	tyEnum_ValueKind__FfLIFKfIB9bQCxObIghtb9bg kind;
union{
	struct {
	NI32 intVal;
} _kind_1;
	struct {
	NF floatVal;
} _kind_2;
	struct {
	NimStringV2 strVal;
} _kind_3;
	struct {
	tySequence__FZ9ca77725E4Q3UZTxnRAkA arrVal;
	tyEnum_ArrElemType__ZAFftDK9bP4RM1cf9a3YJ2FQ elemType;
} _kind_4;
	struct {
	NimStringV2 errMsg;
} _kind_5;
};
};
struct tyObject_RefHeader__ZRImJ0JOtQAFc4hlgAu5tA {
	NI rc;
};
struct tyObject_NimRawSeq__9cILcSEMTM25Wr2S8osw5Bw {
	NI len;
	void* p;
};
struct tyTuple__8SGOCrG9bbn6dwn59ajK9aiRQ {
	NI32 Field0;
	NIM_BOOL Field1;
};
struct tySequence__FZ9ca77725E4Q3UZTxnRAkA_Content { NI cap; tyObject_ValueObj__GvkVL3gYndVcF1SEP1HhDQ* data[SEQ_DECL_SIZE]; };
N_LIB_PRIVATE N_NOCONV(void, dealloc)(void* p_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZsrcZcakesparkZvalue_u86)(tySequence__FZ9ca77725E4Q3UZTxnRAkA dest_p0);
static N_INLINE(NIM_BOOL, nimDecRefIsLast)(void* p_p0);
static N_INLINE(NI, minuspercent___system_u813)(NI x_p0, NI y_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZsrcZcakesparkZvalue_u67)(tyObject_ValueObj__GvkVL3gYndVcF1SEP1HhDQ* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, nimRawDispose)(void* p_p0, NI alignment_p1);
N_LIB_PRIVATE N_NIMCALL(void, alignedDealloc)(void* p_p0, NI align_p1);
N_LIB_PRIVATE N_NIMCALL(void*, nimNewObjUninit)(NI size_p0, NI alignment_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, eqdup___system_u2613)(NimStringV2 src_p0);
N_LIB_PRIVATE N_NIMCALL(void*, nimNewObj)(NI size_p0, NI alignment_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___OOZsrcZcakesparkZvalue_u95)(tySequence__FZ9ca77725E4Q3UZTxnRAkA* dest_p0, tySequence__FZ9ca77725E4Q3UZTxnRAkA src_p1);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(tySequence__FZ9ca77725E4Q3UZTxnRAkA, newSeq__OOZsrcZcakesparkZvalue_u304)(NI len_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___OOZsrcZcakesparkZvalue_u89)(tySequence__FZ9ca77725E4Q3UZTxnRAkA* dest_p0, tySequence__FZ9ca77725E4Q3UZTxnRAkA src_p1);
static N_INLINE(NIM_BOOL, sameSeqPayload)(void* x_p0, void* y_p1);
N_LIB_PRIVATE N_NIMCALL(void, setLen__OOZsrcZcakesparkZvalue_u105)(tySequence__FZ9ca77725E4Q3UZTxnRAkA* s_p0, NI newlen_p1);
static N_INLINE(void, nimIncRef)(void* p_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___OOZsrcZcakesparkZvalue_u153)(tyObject_ValueObj__GvkVL3gYndVcF1SEP1HhDQ** dest_p0, tyObject_ValueObj__GvkVL3gYndVcF1SEP1HhDQ* src_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___OOZsrcZcakesparkZvalue_u159)(tyObject_ValueObj__GvkVL3gYndVcF1SEP1HhDQ** dest_p0, tyObject_ValueObj__GvkVL3gYndVcF1SEP1HhDQ* src_p1);
N_LIB_PRIVATE N_NIMCALL(tyObject_ValueObj__GvkVL3gYndVcF1SEP1HhDQ*, clone__OOZsrcZcakesparkZvalue_u282)(tyObject_ValueObj__GvkVL3gYndVcF1SEP1HhDQ* v_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZsrcZcakesparkZvalue_u150)(tyObject_ValueObj__GvkVL3gYndVcF1SEP1HhDQ* dest_p0);
N_LIB_PRIVATE N_NIMCALL(tySequence__FZ9ca77725E4Q3UZTxnRAkA, eqdup___OOZsrcZcakesparkZvalue_u92)(tySequence__FZ9ca77725E4Q3UZTxnRAkA src_p0);
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__QaZ11OW0lR4IF8eFlvSItw_2 = { 3 | NIM_STRLIT_FLAG, "i32" };
static const NimStringV2 TM__QaZ11OW0lR4IF8eFlvSItw_3 = {3, (NimStrPayload*)&TM__QaZ11OW0lR4IF8eFlvSItw_2};
static const struct {
  NI cap; NIM_CHAR data[5+1];
} TM__QaZ11OW0lR4IF8eFlvSItw_4 = { 5 | NIM_STRLIT_FLAG, "float" };
static const NimStringV2 TM__QaZ11OW0lR4IF8eFlvSItw_5 = {5, (NimStrPayload*)&TM__QaZ11OW0lR4IF8eFlvSItw_4};
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__QaZ11OW0lR4IF8eFlvSItw_6 = { 3 | NIM_STRLIT_FLAG, "str" };
static const NimStringV2 TM__QaZ11OW0lR4IF8eFlvSItw_7 = {3, (NimStrPayload*)&TM__QaZ11OW0lR4IF8eFlvSItw_6};
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__QaZ11OW0lR4IF8eFlvSItw_8 = { 3 | NIM_STRLIT_FLAG, "arr" };
static const NimStringV2 TM__QaZ11OW0lR4IF8eFlvSItw_9 = {3, (NimStrPayload*)&TM__QaZ11OW0lR4IF8eFlvSItw_8};
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__QaZ11OW0lR4IF8eFlvSItw_10 = { 3 | NIM_STRLIT_FLAG, "err" };
static const NimStringV2 TM__QaZ11OW0lR4IF8eFlvSItw_11 = {3, (NimStrPayload*)&TM__QaZ11OW0lR4IF8eFlvSItw_10};
extern NIM_BOOL nimInErrorMode__system_u3521;
static N_INLINE(NI, minuspercent___system_u813)(NI x_p0, NI y_p1) {
	NI result;
	result = ((NI) ((NU)((NU32)(((NU) (x_p0))) - (NU32)(((NU) (y_p1))))));
	return result;
}
static N_INLINE(NIM_BOOL, nimDecRefIsLast)(void* p_p0) {
	NIM_BOOL result;
	result = NIM_FALSE;
	{
		tyObject_RefHeader__ZRImJ0JOtQAFc4hlgAu5tA* cell_1;
		NI T5_;
		if (!!((p_p0 == NIM_NIL))) goto LA3_;
		T5_ = (NI)0;
		T5_ = minuspercent___system_u813(((NI) (ptrdiff_t) (p_p0)), ((NI)4));
		cell_1 = ((tyObject_RefHeader__ZRImJ0JOtQAFc4hlgAu5tA*) (T5_));
		{
			if (!((NI)((NI32)((*cell_1).rc) >> (NU32)(((NI)3))) == ((NI)0))) goto LA8_;
			result = NIM_TRUE;
		}
		goto LA6_;
LA8_: ;
		{
			(*cell_1).rc -= ((NI)8);
		}
LA6_: ;
	}
LA3_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZsrcZcakesparkZvalue_u86)(tySequence__FZ9ca77725E4Q3UZTxnRAkA dest_p0) {
	NI colontmp_;
	colontmp_ = ((NI)0);
	{
		while (1) {
			NI T3_;
			T3_ = dest_p0.len;
			if (!(colontmp_ < T3_)) goto LA2;
			{
				NIM_BOOL T6_;
				T6_ = (NIM_BOOL)0;
				T6_ = nimDecRefIsLast(dest_p0.p->data[colontmp_]);
				if (!T6_) goto LA7_;
				eqdestroy___OOZsrcZcakesparkZvalue_u67(dest_p0.p->data[colontmp_]);
				nimRawDispose(dest_p0.p->data[colontmp_], ((NI)8));
			}
LA7_: ;
			colontmp_ += ((NI)1);
		} LA2: ;
	}
	if (dest_p0.p && !(dest_p0.p->cap & NIM_STRLIT_FLAG)) {
 alignedDealloc(dest_p0.p, NIM_ALIGNOF(tyObject_ValueObj__GvkVL3gYndVcF1SEP1HhDQ*));
}
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZsrcZcakesparkZvalue_u67)(tyObject_ValueObj__GvkVL3gYndVcF1SEP1HhDQ* dest_p0) {
	switch ((*dest_p0).kind) {
	case ((tyEnum_ValueKind__FfLIFKfIB9bQCxObIghtb9bg)0):
	{
	}
	break;
	case ((tyEnum_ValueKind__FfLIFKfIB9bQCxObIghtb9bg)1):
	{
	}
	break;
	case ((tyEnum_ValueKind__FfLIFKfIB9bQCxObIghtb9bg)2):
	{
		if ((*dest_p0)._kind_3.strVal.p && !((*dest_p0)._kind_3.strVal.p->cap & NIM_STRLIT_FLAG)) {
 dealloc((*dest_p0)._kind_3.strVal.p);
}
	}
	break;
	case ((tyEnum_ValueKind__FfLIFKfIB9bQCxObIghtb9bg)3):
	{
		eqdestroy___OOZsrcZcakesparkZvalue_u86((*dest_p0)._kind_4.arrVal);
	}
	break;
	case ((tyEnum_ValueKind__FfLIFKfIB9bQCxObIghtb9bg)4):
	{
		if ((*dest_p0)._kind_5.errMsg.p && !((*dest_p0)._kind_5.errMsg.p->cap & NIM_STRLIT_FLAG)) {
 dealloc((*dest_p0)._kind_5.errMsg.p);
}
	}
	break;
	default: __builtin_unreachable();
	}
}
N_LIB_PRIVATE N_NIMCALL(tyObject_ValueObj__GvkVL3gYndVcF1SEP1HhDQ*, newErr__OOZsrcZcakesparkZvalue_u279)(NimStringV2 msg_p0) {
	tyObject_ValueObj__GvkVL3gYndVcF1SEP1HhDQ* result;
	NimStringV2 colontmpD_;
	tyObject_ValueObj__GvkVL3gYndVcF1SEP1HhDQ* T1_;
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	T1_ = NIM_NIL;
	T1_ = (tyObject_ValueObj__GvkVL3gYndVcF1SEP1HhDQ*) nimNewObjUninit(sizeof(tyObject_ValueObj__GvkVL3gYndVcF1SEP1HhDQ), NIM_ALIGNOF(tyObject_ValueObj__GvkVL3gYndVcF1SEP1HhDQ));
	(*T1_).kind = ((tyEnum_ValueKind__FfLIFKfIB9bQCxObIghtb9bg)4);
	colontmpD_ = eqdup___system_u2613(msg_p0);
	(*T1_)._kind_5.errMsg = colontmpD_;
	result = T1_;
	return result;
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u3521);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqsink___OOZsrcZcakesparkZvalue_u95)(tySequence__FZ9ca77725E4Q3UZTxnRAkA* dest_p0, tySequence__FZ9ca77725E4Q3UZTxnRAkA src_p1) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	if ((*dest_p0).p != src_p1.p) {	eqdestroy___OOZsrcZcakesparkZvalue_u86((*dest_p0));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
(*dest_p0).len = src_p1.len; (*dest_p0).p = src_p1.p;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZsrcZcakesparkZvalue_u150)(tyObject_ValueObj__GvkVL3gYndVcF1SEP1HhDQ* dest_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLast(dest_p0);
		if (!T3_) goto LA4_;
		eqdestroy___OOZsrcZcakesparkZvalue_u67(dest_p0);
		nimRawDispose(dest_p0, ((NI)8));
	}
LA4_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___OOZsrcZcakesparkZvalue_u147)(tyObject_ValueObj__GvkVL3gYndVcF1SEP1HhDQ** dest_p0) {
	(*dest_p0) = 0;
}
static N_INLINE(NIM_BOOL, sameSeqPayload)(void* x_p0, void* y_p1) {
	NIM_BOOL result;
	result = ((*((tyObject_NimRawSeq__9cILcSEMTM25Wr2S8osw5Bw*) (x_p0))).p == (*((tyObject_NimRawSeq__9cILcSEMTM25Wr2S8osw5Bw*) (y_p1))).p);
	return result;
}
static N_INLINE(void, nimIncRef)(void* p_p0) {
	NI T1_;
	T1_ = (NI)0;
	T1_ = minuspercent___system_u813(((NI) (ptrdiff_t) (p_p0)), ((NI)4));
	(*((tyObject_RefHeader__ZRImJ0JOtQAFc4hlgAu5tA*) (T1_))).rc += ((NI)8);
}
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___OOZsrcZcakesparkZvalue_u89)(tySequence__FZ9ca77725E4Q3UZTxnRAkA* dest_p0, tySequence__FZ9ca77725E4Q3UZTxnRAkA src_p1) {
	NI T6_;
	NI colontmp_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = sameSeqPayload(dest_p0, (&src_p1));
		if (!T3_) goto LA4_;
		goto BeforeRet_;
	}
LA4_: ;
	T6_ = src_p1.len;
	setLen__OOZsrcZcakesparkZvalue_u105((&(*dest_p0)), T6_);
	colontmp_ = ((NI)0);
	{
		while (1) {
			NI T9_;
			T9_ = (*dest_p0).len;
			if (!(colontmp_ < T9_)) goto LA8;
			{
				if (!src_p1.p->data[colontmp_]) goto LA12_;
				nimIncRef(src_p1.p->data[colontmp_]);
			}
LA12_: ;
			{
				NIM_BOOL T16_;
				T16_ = (NIM_BOOL)0;
				T16_ = nimDecRefIsLast((*dest_p0).p->data[colontmp_]);
				if (!T16_) goto LA17_;
				eqdestroy___OOZsrcZcakesparkZvalue_u67((*dest_p0).p->data[colontmp_]);
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				nimRawDispose((*dest_p0).p->data[colontmp_], ((NI)8));
			}
LA17_: ;
			(*dest_p0).p->data[colontmp_] = src_p1.p->data[colontmp_];
			colontmp_ += ((NI)1);
		} LA8: ;
	}
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___OOZsrcZcakesparkZvalue_u153)(tyObject_ValueObj__GvkVL3gYndVcF1SEP1HhDQ** dest_p0, tyObject_ValueObj__GvkVL3gYndVcF1SEP1HhDQ* src_p1) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	{
		if (!src_p1) goto LA3_;
		nimIncRef(src_p1);
	}
LA3_: ;
	{
		NIM_BOOL T7_;
		T7_ = (NIM_BOOL)0;
		T7_ = nimDecRefIsLast((*dest_p0));
		if (!T7_) goto LA8_;
		eqdestroy___OOZsrcZcakesparkZvalue_u67((*dest_p0));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		nimRawDispose((*dest_p0), ((NI)8));
	}
LA8_: ;
	(*dest_p0) = src_p1;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqsink___OOZsrcZcakesparkZvalue_u159)(tyObject_ValueObj__GvkVL3gYndVcF1SEP1HhDQ** dest_p0, tyObject_ValueObj__GvkVL3gYndVcF1SEP1HhDQ* src_p1) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nimDecRefIsLast((*dest_p0));
		if (!T3_) goto LA4_;
		eqdestroy___OOZsrcZcakesparkZvalue_u67((*dest_p0));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		nimRawDispose((*dest_p0), ((NI)8));
	}
LA4_: ;
	(*dest_p0) = src_p1;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_ValueObj__GvkVL3gYndVcF1SEP1HhDQ*, clone__OOZsrcZcakesparkZvalue_u282)(tyObject_ValueObj__GvkVL3gYndVcF1SEP1HhDQ* v_p0) {
	tyObject_ValueObj__GvkVL3gYndVcF1SEP1HhDQ* result;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	switch ((*v_p0).kind) {
	case ((tyEnum_ValueKind__FfLIFKfIB9bQCxObIghtb9bg)0):
	{
		NI32 colontmpD_;
		tyObject_ValueObj__GvkVL3gYndVcF1SEP1HhDQ* T2_;
		colontmpD_ = (NI32)0;
		T2_ = NIM_NIL;
		T2_ = (tyObject_ValueObj__GvkVL3gYndVcF1SEP1HhDQ*) nimNewObjUninit(sizeof(tyObject_ValueObj__GvkVL3gYndVcF1SEP1HhDQ), NIM_ALIGNOF(tyObject_ValueObj__GvkVL3gYndVcF1SEP1HhDQ));
		(*T2_).kind = ((tyEnum_ValueKind__FfLIFKfIB9bQCxObIghtb9bg)0);
		colontmpD_ = (*v_p0)._kind_1.intVal;
		(*T2_)._kind_1.intVal = colontmpD_;
		result = T2_;
	}
	break;
	case ((tyEnum_ValueKind__FfLIFKfIB9bQCxObIghtb9bg)1):
	{
		NF colontmpD__2;
		tyObject_ValueObj__GvkVL3gYndVcF1SEP1HhDQ* T4_;
		colontmpD__2 = (NF)0;
		T4_ = NIM_NIL;
		T4_ = (tyObject_ValueObj__GvkVL3gYndVcF1SEP1HhDQ*) nimNewObjUninit(sizeof(tyObject_ValueObj__GvkVL3gYndVcF1SEP1HhDQ), NIM_ALIGNOF(tyObject_ValueObj__GvkVL3gYndVcF1SEP1HhDQ));
		(*T4_).kind = ((tyEnum_ValueKind__FfLIFKfIB9bQCxObIghtb9bg)1);
		colontmpD__2 = (*v_p0)._kind_2.floatVal;
		(*T4_)._kind_2.floatVal = colontmpD__2;
		result = T4_;
	}
	break;
	case ((tyEnum_ValueKind__FfLIFKfIB9bQCxObIghtb9bg)2):
	{
		NimStringV2 colontmpD__3;
		tyObject_ValueObj__GvkVL3gYndVcF1SEP1HhDQ* T6_;
		colontmpD__3.len = 0; colontmpD__3.p = NIM_NIL;
		T6_ = NIM_NIL;
		T6_ = (tyObject_ValueObj__GvkVL3gYndVcF1SEP1HhDQ*) nimNewObjUninit(sizeof(tyObject_ValueObj__GvkVL3gYndVcF1SEP1HhDQ), NIM_ALIGNOF(tyObject_ValueObj__GvkVL3gYndVcF1SEP1HhDQ));
		(*T6_).kind = ((tyEnum_ValueKind__FfLIFKfIB9bQCxObIghtb9bg)2);
		colontmpD__3 = eqdup___system_u2613((*v_p0)._kind_3.strVal);
		(*T6_)._kind_3.strVal = colontmpD__3;
		result = T6_;
	}
	break;
	case ((tyEnum_ValueKind__FfLIFKfIB9bQCxObIghtb9bg)3):
	{
		tyEnum_ArrElemType__ZAFftDK9bP4RM1cf9a3YJ2FQ colontmpD__4;
		tyObject_ValueObj__GvkVL3gYndVcF1SEP1HhDQ* T8_;
		NI T9_;
		tySequence__FZ9ca77725E4Q3UZTxnRAkA T10_;
		colontmpD__4 = (tyEnum_ArrElemType__ZAFftDK9bP4RM1cf9a3YJ2FQ)0;
		T8_ = NIM_NIL;
		T8_ = (tyObject_ValueObj__GvkVL3gYndVcF1SEP1HhDQ*) nimNewObj(sizeof(tyObject_ValueObj__GvkVL3gYndVcF1SEP1HhDQ), NIM_ALIGNOF(tyObject_ValueObj__GvkVL3gYndVcF1SEP1HhDQ));
		(*T8_).kind = ((tyEnum_ValueKind__FfLIFKfIB9bQCxObIghtb9bg)3);
		colontmpD__4 = (*v_p0)._kind_4.elemType;
		(*T8_)._kind_4.elemType = colontmpD__4;
		(*T8_)._kind_4.arrVal.len = 0; (*T8_)._kind_4.arrVal.p = NIM_NIL;
		result = T8_;
		T9_ = (*v_p0)._kind_4.arrVal.len;
		T10_.len = 0; T10_.p = NIM_NIL;
		T10_ = newSeq__OOZsrcZcakesparkZvalue_u304((T9_));
		eqsink___OOZsrcZcakesparkZvalue_u95((&(*result)._kind_4.arrVal), T10_);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		{
			tyObject_ValueObj__GvkVL3gYndVcF1SEP1HhDQ* e_1;
			tySequence__FZ9ca77725E4Q3UZTxnRAkA colontmp_;
			NI i_1;
			NI i_2;
			NI L_1;
			NI T12_;
			e_1 = NIM_NIL;
			colontmp_.len = 0; colontmp_.p = NIM_NIL;
			i_1 = (NI)0;
			eqcopy___OOZsrcZcakesparkZvalue_u89((&colontmp_), (*v_p0)._kind_4.arrVal);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			i_2 = ((NI)0);
			T12_ = colontmp_.len;
			L_1 = T12_;
			{
				while (1) {
					tyObject_ValueObj__GvkVL3gYndVcF1SEP1HhDQ* T15_;
					if (!(i_2 < L_1)) goto LA14;
					i_1 = i_2;
					eqcopy___OOZsrcZcakesparkZvalue_u153(&e_1, colontmp_.p->data[i_2]);
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
					T15_ = NIM_NIL;
					T15_ = clone__OOZsrcZcakesparkZvalue_u282(e_1);
					if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___OOZsrcZcakesparkZvalue_u150(T15_); goto BeforeRet_;}
					eqsink___OOZsrcZcakesparkZvalue_u159(&(*result)._kind_4.arrVal.p->data[i_1], T15_);
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
					i_2 += ((NI)1);
				} LA14: ;
			}
			eqdestroy___OOZsrcZcakesparkZvalue_u86(colontmp_);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			eqdestroy___OOZsrcZcakesparkZvalue_u150(e_1);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		}
	}
	break;
	case ((tyEnum_ValueKind__FfLIFKfIB9bQCxObIghtb9bg)4):
	{
		NimStringV2 colontmpD__5;
		tyObject_ValueObj__GvkVL3gYndVcF1SEP1HhDQ* T17_;
		colontmpD__5.len = 0; colontmpD__5.p = NIM_NIL;
		T17_ = NIM_NIL;
		T17_ = (tyObject_ValueObj__GvkVL3gYndVcF1SEP1HhDQ*) nimNewObjUninit(sizeof(tyObject_ValueObj__GvkVL3gYndVcF1SEP1HhDQ), NIM_ALIGNOF(tyObject_ValueObj__GvkVL3gYndVcF1SEP1HhDQ));
		(*T17_).kind = ((tyEnum_ValueKind__FfLIFKfIB9bQCxObIghtb9bg)4);
		colontmpD__5 = eqdup___system_u2613((*v_p0)._kind_5.errMsg);
		(*T17_)._kind_5.errMsg = colontmpD__5;
		result = T17_;
	}
	break;
	default: __builtin_unreachable();
	}
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_ValueObj__GvkVL3gYndVcF1SEP1HhDQ*, newStr__OOZsrcZcakesparkZvalue_u250)(NimStringV2 v_p0) {
	tyObject_ValueObj__GvkVL3gYndVcF1SEP1HhDQ* result;
	NimStringV2 colontmpD_;
	tyObject_ValueObj__GvkVL3gYndVcF1SEP1HhDQ* T1_;
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	T1_ = NIM_NIL;
	T1_ = (tyObject_ValueObj__GvkVL3gYndVcF1SEP1HhDQ*) nimNewObjUninit(sizeof(tyObject_ValueObj__GvkVL3gYndVcF1SEP1HhDQ), NIM_ALIGNOF(tyObject_ValueObj__GvkVL3gYndVcF1SEP1HhDQ));
	(*T1_).kind = ((tyEnum_ValueKind__FfLIFKfIB9bQCxObIghtb9bg)2);
	colontmpD_ = eqdup___system_u2613(v_p0);
	(*T1_)._kind_3.strVal = colontmpD_;
	result = T1_;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_ValueObj__GvkVL3gYndVcF1SEP1HhDQ*, newInt__OOZsrcZcakesparkZvalue_u45)(NI32 v_p0) {
	tyObject_ValueObj__GvkVL3gYndVcF1SEP1HhDQ* result;
	NI32 colontmpD_;
	tyObject_ValueObj__GvkVL3gYndVcF1SEP1HhDQ* T1_;
	colontmpD_ = (NI32)0;
	T1_ = NIM_NIL;
	T1_ = (tyObject_ValueObj__GvkVL3gYndVcF1SEP1HhDQ*) nimNewObjUninit(sizeof(tyObject_ValueObj__GvkVL3gYndVcF1SEP1HhDQ), NIM_ALIGNOF(tyObject_ValueObj__GvkVL3gYndVcF1SEP1HhDQ));
	(*T1_).kind = ((tyEnum_ValueKind__FfLIFKfIB9bQCxObIghtb9bg)0);
	colontmpD_ = v_p0;
	(*T1_)._kind_1.intVal = colontmpD_;
	result = T1_;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyTuple__8SGOCrG9bbn6dwn59ajK9aiRQ, checkAdd__OOZsrcZcakesparkZvalue_u416)(NI32 a_p0, NI32 b_p1) {
	tyTuple__8SGOCrG9bbn6dwn59ajK9aiRQ result;
	NI32 colontmp__5;
	NIM_BOOL colontmp__6;
{	{
		NIM_BOOL T3_;
		NI32 colontmp_;
		NIM_BOOL colontmp__2;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI32)0) < b_p1);
		if (!(T3_)) goto LA4_;
		T3_ = ((NI32)(((NI32)2147483647) - b_p1) < a_p0);
LA4_: ;
		if (!T3_) goto LA5_;
		colontmp_ = ((NI32)0);
		colontmp__2 = NIM_TRUE;
		result.Field0 = colontmp_;
		result.Field1 = colontmp__2;
		goto BeforeRet_;
	}
LA5_: ;
	{
		NIM_BOOL T9_;
		NI32 colontmp__3;
		NIM_BOOL colontmp__4;
		T9_ = (NIM_BOOL)0;
		T9_ = (b_p1 < ((NI32)0));
		if (!(T9_)) goto LA10_;
		T9_ = (a_p0 < (NI32)(((NI32)(-2147483647 -1)) - b_p1));
LA10_: ;
		if (!T9_) goto LA11_;
		colontmp__3 = ((NI32)0);
		colontmp__4 = NIM_TRUE;
		result.Field0 = colontmp__3;
		result.Field1 = colontmp__4;
		goto BeforeRet_;
	}
LA11_: ;
	colontmp__5 = (NI32)(a_p0 + b_p1);
	colontmp__6 = NIM_FALSE;
	result.Field0 = colontmp__5;
	result.Field1 = colontmp__6;
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_ValueObj__GvkVL3gYndVcF1SEP1HhDQ*, newFloat__OOZsrcZcakesparkZvalue_u247)(NF v_p0) {
	tyObject_ValueObj__GvkVL3gYndVcF1SEP1HhDQ* result;
	NF colontmpD_;
	tyObject_ValueObj__GvkVL3gYndVcF1SEP1HhDQ* T1_;
	colontmpD_ = (NF)0;
	T1_ = NIM_NIL;
	T1_ = (tyObject_ValueObj__GvkVL3gYndVcF1SEP1HhDQ*) nimNewObjUninit(sizeof(tyObject_ValueObj__GvkVL3gYndVcF1SEP1HhDQ), NIM_ALIGNOF(tyObject_ValueObj__GvkVL3gYndVcF1SEP1HhDQ));
	(*T1_).kind = ((tyEnum_ValueKind__FfLIFKfIB9bQCxObIghtb9bg)1);
	colontmpD_ = v_p0;
	(*T1_)._kind_2.floatVal = colontmpD_;
	result = T1_;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyTuple__8SGOCrG9bbn6dwn59ajK9aiRQ, checkSub__OOZsrcZcakesparkZvalue_u437)(NI32 a_p0, NI32 b_p1) {
	tyTuple__8SGOCrG9bbn6dwn59ajK9aiRQ result;
	NI32 colontmp__5;
	NIM_BOOL colontmp__6;
{	{
		NIM_BOOL T3_;
		NI32 colontmp_;
		NIM_BOOL colontmp__2;
		T3_ = (NIM_BOOL)0;
		T3_ = (b_p1 < ((NI32)0));
		if (!(T3_)) goto LA4_;
		T3_ = ((NI32)(((NI32)2147483647) + b_p1) < a_p0);
LA4_: ;
		if (!T3_) goto LA5_;
		colontmp_ = ((NI32)0);
		colontmp__2 = NIM_TRUE;
		result.Field0 = colontmp_;
		result.Field1 = colontmp__2;
		goto BeforeRet_;
	}
LA5_: ;
	{
		NIM_BOOL T9_;
		NI32 colontmp__3;
		NIM_BOOL colontmp__4;
		T9_ = (NIM_BOOL)0;
		T9_ = (((NI32)0) < b_p1);
		if (!(T9_)) goto LA10_;
		T9_ = (a_p0 < (NI32)(((NI32)(-2147483647 -1)) + b_p1));
LA10_: ;
		if (!T9_) goto LA11_;
		colontmp__3 = ((NI32)0);
		colontmp__4 = NIM_TRUE;
		result.Field0 = colontmp__3;
		result.Field1 = colontmp__4;
		goto BeforeRet_;
	}
LA11_: ;
	colontmp__5 = (NI32)(a_p0 - b_p1);
	colontmp__6 = NIM_FALSE;
	result.Field0 = colontmp__5;
	result.Field1 = colontmp__6;
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyTuple__8SGOCrG9bbn6dwn59ajK9aiRQ, checkMul__OOZsrcZcakesparkZvalue_u441)(NI32 a_p0, NI32 b_p1) {
	tyTuple__8SGOCrG9bbn6dwn59ajK9aiRQ result;
	NI32 product_1;
	NI32 colontmp__7;
	NIM_BOOL colontmp__8;
{	{
		NIM_BOOL T3_;
		NI32 colontmp_;
		NIM_BOOL colontmp__2;
		T3_ = (NIM_BOOL)0;
		T3_ = (a_p0 == ((NI32)0));
		if (T3_) goto LA4_;
		T3_ = (b_p1 == ((NI32)0));
LA4_: ;
		if (!T3_) goto LA5_;
		colontmp_ = ((NI32)0);
		colontmp__2 = NIM_FALSE;
		result.Field0 = colontmp_;
		result.Field1 = colontmp__2;
		goto BeforeRet_;
	}
LA5_: ;
	{
		NIM_BOOL T9_;
		NI32 colontmp__3;
		NIM_BOOL colontmp__4;
		T9_ = (NIM_BOOL)0;
		T9_ = (a_p0 == ((NI32)(-2147483647 -1)));
		if (!(T9_)) goto LA10_;
		T9_ = (b_p1 == ((NI32)-1));
LA10_: ;
		if (!T9_) goto LA11_;
		colontmp__3 = ((NI32)0);
		colontmp__4 = NIM_TRUE;
		result.Field0 = colontmp__3;
		result.Field1 = colontmp__4;
		goto BeforeRet_;
	}
LA11_: ;
	product_1 = (NI32)(a_p0 * b_p1);
	{
		NI32 colontmp__5;
		NIM_BOOL colontmp__6;
		if (!!(((NI32)(product_1 / a_p0) == b_p1))) goto LA15_;
		colontmp__5 = ((NI32)0);
		colontmp__6 = NIM_TRUE;
		result.Field0 = colontmp__5;
		result.Field1 = colontmp__6;
		goto BeforeRet_;
	}
LA15_: ;
	colontmp__7 = product_1;
	colontmp__8 = NIM_FALSE;
	result.Field0 = colontmp__7;
	result.Field1 = colontmp__8;
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyTuple__8SGOCrG9bbn6dwn59ajK9aiRQ, checkDiv__OOZsrcZcakesparkZvalue_u446)(NI32 a_p0, NI32 b_p1) {
	tyTuple__8SGOCrG9bbn6dwn59ajK9aiRQ result;
	NI32 colontmp__5;
	NIM_BOOL colontmp__6;
{	{
		NI32 colontmp_;
		NIM_BOOL colontmp__2;
		if (!(b_p1 == ((NI32)0))) goto LA3_;
		colontmp_ = ((NI32)0);
		colontmp__2 = NIM_TRUE;
		result.Field0 = colontmp_;
		result.Field1 = colontmp__2;
		goto BeforeRet_;
	}
LA3_: ;
	{
		NIM_BOOL T7_;
		NI32 colontmp__3;
		NIM_BOOL colontmp__4;
		T7_ = (NIM_BOOL)0;
		T7_ = (a_p0 == ((NI32)(-2147483647 -1)));
		if (!(T7_)) goto LA8_;
		T7_ = (b_p1 == ((NI32)-1));
LA8_: ;
		if (!T7_) goto LA9_;
		colontmp__3 = ((NI32)0);
		colontmp__4 = NIM_TRUE;
		result.Field0 = colontmp__3;
		result.Field1 = colontmp__4;
		goto BeforeRet_;
	}
LA9_: ;
	colontmp__5 = (NI32)(a_p0 / b_p1);
	colontmp__6 = NIM_FALSE;
	result.Field0 = colontmp__5;
	result.Field1 = colontmp__6;
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyTuple__8SGOCrG9bbn6dwn59ajK9aiRQ, checkNeg__OOZsrcZcakesparkZvalue_u450)(NI32 a_p0) {
	tyTuple__8SGOCrG9bbn6dwn59ajK9aiRQ result;
	NI32 colontmp__3;
	NIM_BOOL colontmp__4;
{	{
		NI32 colontmp_;
		NIM_BOOL colontmp__2;
		if (!(a_p0 == ((NI32)(-2147483647 -1)))) goto LA3_;
		colontmp_ = ((NI32)0);
		colontmp__2 = NIM_TRUE;
		result.Field0 = colontmp_;
		result.Field1 = colontmp__2;
		goto BeforeRet_;
	}
LA3_: ;
	colontmp__3 = ((NI32)-(a_p0));
	colontmp__4 = NIM_FALSE;
	result.Field0 = colontmp__3;
	result.Field1 = colontmp__4;
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, typeName__OOZsrcZcakesparkZvalue_u413)(tyObject_ValueObj__GvkVL3gYndVcF1SEP1HhDQ* v_p0) {
	NimStringV2 result;
	NimStringV2 T1_;
	T1_.len = 0; T1_.p = NIM_NIL;
	switch ((*v_p0).kind) {
	case ((tyEnum_ValueKind__FfLIFKfIB9bQCxObIghtb9bg)0):
	{
		result = TM__QaZ11OW0lR4IF8eFlvSItw_3;
	}
	break;
	case ((tyEnum_ValueKind__FfLIFKfIB9bQCxObIghtb9bg)1):
	{
		result = TM__QaZ11OW0lR4IF8eFlvSItw_5;
	}
	break;
	case ((tyEnum_ValueKind__FfLIFKfIB9bQCxObIghtb9bg)2):
	{
		result = TM__QaZ11OW0lR4IF8eFlvSItw_7;
	}
	break;
	case ((tyEnum_ValueKind__FfLIFKfIB9bQCxObIghtb9bg)3):
	{
		result = TM__QaZ11OW0lR4IF8eFlvSItw_9;
	}
	break;
	case ((tyEnum_ValueKind__FfLIFKfIB9bQCxObIghtb9bg)4):
	{
		result = TM__QaZ11OW0lR4IF8eFlvSItw_11;
	}
	break;
	default: __builtin_unreachable();
	}
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tySequence__FZ9ca77725E4Q3UZTxnRAkA, eqdup___OOZsrcZcakesparkZvalue_u92)(tySequence__FZ9ca77725E4Q3UZTxnRAkA src_p0) {
	tySequence__FZ9ca77725E4Q3UZTxnRAkA result;
	NI T1_;
	NI colontmp_;
	result.len = 0; result.p = NIM_NIL;
	T1_ = src_p0.len;
	setLen__OOZsrcZcakesparkZvalue_u105((&result), T1_);
	colontmp_ = ((NI)0);
	{
		while (1) {
			NI T4_;
			T4_ = result.len;
			if (!(colontmp_ < T4_)) goto LA3;
			result.p->data[colontmp_] = src_p0.p->data[colontmp_];
			{
				if (!src_p0.p->data[colontmp_]) goto LA7_;
				nimIncRef(src_p0.p->data[colontmp_]);
			}
LA7_: ;
			colontmp_ += ((NI)1);
		} LA3: ;
	}
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_ValueObj__GvkVL3gYndVcF1SEP1HhDQ*, newArr__OOZsrcZcakesparkZvalue_u253)(tySequence__FZ9ca77725E4Q3UZTxnRAkA elems_p0) {
	tyObject_ValueObj__GvkVL3gYndVcF1SEP1HhDQ* result;
	tySequence__FZ9ca77725E4Q3UZTxnRAkA colontmpD_;
	tyObject_ValueObj__GvkVL3gYndVcF1SEP1HhDQ* T1_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = NIM_NIL;
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	T1_ = NIM_NIL;
	T1_ = (tyObject_ValueObj__GvkVL3gYndVcF1SEP1HhDQ*) nimNewObjUninit(sizeof(tyObject_ValueObj__GvkVL3gYndVcF1SEP1HhDQ), NIM_ALIGNOF(tyObject_ValueObj__GvkVL3gYndVcF1SEP1HhDQ));
	(*T1_).kind = ((tyEnum_ValueKind__FfLIFKfIB9bQCxObIghtb9bg)3);
	colontmpD_ = eqdup___OOZsrcZcakesparkZvalue_u92(elems_p0);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	(*T1_)._kind_4.arrVal = colontmpD_;
	(*T1_)._kind_4.elemType = ((tyEnum_ArrElemType__ZAFftDK9bP4RM1cf9a3YJ2FQ)0);
	result = T1_;
	{
		NI T4_;
		T4_ = elems_p0.len;
		if (!(((NI)0) < T4_)) goto LA5_;
		switch ((*elems_p0.p->data[((NI)0)]).kind) {
		case ((tyEnum_ValueKind__FfLIFKfIB9bQCxObIghtb9bg)0):
		{
			(*result)._kind_4.elemType = ((tyEnum_ArrElemType__ZAFftDK9bP4RM1cf9a3YJ2FQ)1);
		}
		break;
		case ((tyEnum_ValueKind__FfLIFKfIB9bQCxObIghtb9bg)1):
		{
			(*result)._kind_4.elemType = ((tyEnum_ArrElemType__ZAFftDK9bP4RM1cf9a3YJ2FQ)2);
		}
		break;
		case ((tyEnum_ValueKind__FfLIFKfIB9bQCxObIghtb9bg)2):
		{
			(*result)._kind_4.elemType = ((tyEnum_ArrElemType__ZAFftDK9bP4RM1cf9a3YJ2FQ)3);
		}
		break;
		case ((tyEnum_ValueKind__FfLIFKfIB9bQCxObIghtb9bg)3):
		{
			(*result)._kind_4.elemType = ((tyEnum_ArrElemType__ZAFftDK9bP4RM1cf9a3YJ2FQ)4);
		}
		break;
		case ((tyEnum_ValueKind__FfLIFKfIB9bQCxObIghtb9bg)4):
		{
			(*result)._kind_4.elemType = ((tyEnum_ArrElemType__ZAFftDK9bP4RM1cf9a3YJ2FQ)5);
		}
		break;
		default: __builtin_unreachable();
		}
	}
LA5_: ;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_ValueObj__GvkVL3gYndVcF1SEP1HhDQ*, eqdup___OOZsrcZcakesparkZvalue_u156)(tyObject_ValueObj__GvkVL3gYndVcF1SEP1HhDQ* src_p0) {
	tyObject_ValueObj__GvkVL3gYndVcF1SEP1HhDQ* result;
	result = src_p0;
	{
		if (!src_p0) goto LA3_;
		nimIncRef(src_p0);
	}
LA3_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___OOZsrcZcakesparkZvalue_u83)(tySequence__FZ9ca77725E4Q3UZTxnRAkA* dest_p0) {
	(*dest_p0).len = 0; (*dest_p0).p = NIM_NIL;
}
