/* Generated by Nim Compiler v2.2.4 */
#define NIM_INTBITS 32
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct tyObject_CakeVMObj__34PPuLHRBi5xCED6l9cxqtg tyObject_CakeVMObj__34PPuLHRBi5xCED6l9cxqtg;
typedef struct tyObject_CakeLimits__2XYWqO8BQUN9b9cmdJrTSD7A tyObject_CakeLimits__2XYWqO8BQUN9b9cmdJrTSD7A;
typedef struct tyObject_CompiledProgram__rw4x9birAJsXbFMKqoyp47w tyObject_CompiledProgram__rw4x9birAJsXbFMKqoyp47w;
typedef struct tySequence__tjkxNOQY9cAdAh85u9cULN9cg tySequence__tjkxNOQY9cAdAh85u9cULN9cg;
typedef struct tySequence__tjkxNOQY9cAdAh85u9cULN9cg_Content tySequence__tjkxNOQY9cAdAh85u9cULN9cg_Content;
typedef struct tySequence__QSd3I0juamqA6Vj3d6tVAw tySequence__QSd3I0juamqA6Vj3d6tVAw;
typedef struct tySequence__QSd3I0juamqA6Vj3d6tVAw_Content tySequence__QSd3I0juamqA6Vj3d6tVAw_Content;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_VM__Vb9aBiSMJ3JOzO9ceFKf50cw tyObject_VM__Vb9aBiSMJ3JOzO9ceFKf50cw;
typedef struct tySequence__04t1eEEZQNAyf6WBHIz2aw tySequence__04t1eEEZQNAyf6WBHIz2aw;
typedef struct tySequence__04t1eEEZQNAyf6WBHIz2aw_Content tySequence__04t1eEEZQNAyf6WBHIz2aw_Content;
typedef struct tyObject_Table__XUxYzMtKpHmwzeIZXCNmlQ tyObject_Table__XUxYzMtKpHmwzeIZXCNmlQ;
typedef struct tySequence__pUxI6Ljo6IKKHXKOZkQ7Og tySequence__pUxI6Ljo6IKKHXKOZkQ7Og;
typedef struct tySequence__pUxI6Ljo6IKKHXKOZkQ7Og_Content tySequence__pUxI6Ljo6IKKHXKOZkQ7Og_Content;
typedef struct tyObject_ScopeFrameObj__79aJK3XdXc5CZiNkEpfDhCQ tyObject_ScopeFrameObj__79aJK3XdXc5CZiNkEpfDhCQ;
typedef struct tySequence__PPBaB565t0oqWHu7wDYghA tySequence__PPBaB565t0oqWHu7wDYghA;
typedef struct tySequence__PPBaB565t0oqWHu7wDYghA_Content tySequence__PPBaB565t0oqWHu7wDYghA_Content;
typedef struct tyObject_Table__9a66NC9blQIGrSsoZt4wuA9bA tyObject_Table__9a66NC9blQIGrSsoZt4wuA9bA;
typedef struct tySequence__ehwmGsb9ad9cXxegdq9a9a6QtQ tySequence__ehwmGsb9ad9cXxegdq9a9a6QtQ;
typedef struct tySequence__ehwmGsb9ad9cXxegdq9a9a6QtQ_Content tySequence__ehwmGsb9ad9cXxegdq9a9a6QtQ_Content;
typedef struct tyObject_Table__s4eUpSrH4WdAo9ba9cO1MWqQ tyObject_Table__s4eUpSrH4WdAo9ba9cO1MWqQ;
typedef struct tySequence__0pv9ai34D5C6bYu9aWlERk9cg tySequence__0pv9ai34D5C6bYu9aWlERk9cg;
typedef struct tySequence__0pv9ai34D5C6bYu9aWlERk9cg_Content tySequence__0pv9ai34D5C6bYu9aWlERk9cg_Content;
typedef struct tySequence__GWB2ugnQavMoz8YICIsyiw tySequence__GWB2ugnQavMoz8YICIsyiw;
typedef struct tySequence__GWB2ugnQavMoz8YICIsyiw_Content tySequence__GWB2ugnQavMoz8YICIsyiw_Content;
typedef struct tySequence__p4DprHqS6CWRWYxXa8hKOQ tySequence__p4DprHqS6CWRWYxXa8hKOQ;
typedef struct tySequence__p4DprHqS6CWRWYxXa8hKOQ_Content tySequence__p4DprHqS6CWRWYxXa8hKOQ_Content;
typedef struct tySequence__Cv7TuhXmGIkCLGuWTSaHow tySequence__Cv7TuhXmGIkCLGuWTSaHow;
typedef struct tySequence__Cv7TuhXmGIkCLGuWTSaHow_Content tySequence__Cv7TuhXmGIkCLGuWTSaHow_Content;
typedef struct tyTuple__GsU7WpoQEf9a39amWFeK9aVIQ tyTuple__GsU7WpoQEf9a39amWFeK9aVIQ;
typedef struct tyObject_ValueObj__GvkVL3gYndVcF1SEP1HhDQ tyObject_ValueObj__GvkVL3gYndVcF1SEP1HhDQ;
typedef struct tyTuple__A9avNQiAjJiDux9bLEU4a17Q tyTuple__A9avNQiAjJiDux9bLEU4a17Q;
typedef struct tyObject_Peripheral__67pLM35FlCh2M409bcB4B5Q tyObject_Peripheral__67pLM35FlCh2M409bcB4B5Q;
typedef struct tyObject_Table__mbpGVJrPdClMnjx1YPEhYA tyObject_Table__mbpGVJrPdClMnjx1YPEhYA;
typedef struct tySequence__3Ser9bAvvL6U0lEMcdzQiSw tySequence__3Ser9bAvvL6U0lEMcdzQiSw;
typedef struct tySequence__3Ser9bAvvL6U0lEMcdzQiSw_Content tySequence__3Ser9bAvvL6U0lEMcdzQiSw_Content;
typedef struct tySequence__FZ9ca77725E4Q3UZTxnRAkA tySequence__FZ9ca77725E4Q3UZTxnRAkA;
typedef struct tySequence__FZ9ca77725E4Q3UZTxnRAkA_Content tySequence__FZ9ca77725E4Q3UZTxnRAkA_Content;
typedef struct tyObject_Env_c_apidotnim_makeBuiltinWrapper___ra9cnzikOxz1Zeu1Kb1UkNg tyObject_Env_c_apidotnim_makeBuiltinWrapper___ra9cnzikOxz1Zeu1Kb1UkNg;
typedef struct RootObj RootObj;
typedef struct TNimTypeV2 TNimTypeV2;
typedef struct tyObject_CakePeripheral__1N2Ijp8MEoiX9agXZduCB1A tyObject_CakePeripheral__1N2Ijp8MEoiX9agXZduCB1A;
typedef struct tyObject_CakePeripheralProperty__VdUD5ZgF2oQkUm4Fmm8chg tyObject_CakePeripheralProperty__VdUD5ZgF2oQkUm4Fmm8chg;
typedef struct tyObject_CakePeripheralMethod__0bD3iqrOc9bYABKoNRo5kFQ tyObject_CakePeripheralMethod__0bD3iqrOc9bYABKoNRo5kFQ;
typedef struct tyObject_PeripheralProperty__q9bbhPnTUeZLtBNPVecSIig tyObject_PeripheralProperty__q9bbhPnTUeZLtBNPVecSIig;
typedef struct tyObject_Env_c_apidotnim_makeGetter___xsVbh0tLMBI9a5ePRycpUig tyObject_Env_c_apidotnim_makeGetter___xsVbh0tLMBI9a5ePRycpUig;
typedef struct tyObject_Env_c_apidotnim_makeSetter___YrM9bHq9c9aIC9cq9bWjTwQKQUw tyObject_Env_c_apidotnim_makeSetter___YrM9bHq9c9aIC9cq9bWjTwQKQUw;
typedef struct tyObject_Env_c_apidotnim_makeMethod___P3ev4im13F5MEkE6FL5f0g tyObject_Env_c_apidotnim_makeMethod___P3ev4im13F5MEkE6FL5f0g;
typedef struct tyObject_Instruction__XTstQEb9co2NNRaKJBBih9ag tyObject_Instruction__XTstQEb9co2NNRaKJBBih9ag;
typedef struct tySequence__WsDlUegMKP5qbZfDE7UOgg tySequence__WsDlUegMKP5qbZfDE7UOgg;
typedef struct tySequence__WsDlUegMKP5qbZfDE7UOgg_Content tySequence__WsDlUegMKP5qbZfDE7UOgg_Content;
typedef struct tyObject_Condition__pS6iJoNrp0lYt3mVF9cXsPQ tyObject_Condition__pS6iJoNrp0lYt3mVF9cXsPQ;
typedef struct tyObject_Arg__E9boIsLlAjypGlVaV0b9crIA tyObject_Arg__E9boIsLlAjypGlVaV0b9crIA;
typedef struct tySequence__blakBku9aKYZtnss5hJNT1Q tySequence__blakBku9aKYZtnss5hJNT1Q;
typedef struct tySequence__blakBku9aKYZtnss5hJNT1Q_Content tySequence__blakBku9aKYZtnss5hJNT1Q_Content;
typedef struct tySequence__B5XQ2QsS79aU7kZkd2Wo9ckQ tySequence__B5XQ2QsS79aU7kZkd2Wo9ckQ;
typedef struct tySequence__B5XQ2QsS79aU7kZkd2Wo9ckQ_Content tySequence__B5XQ2QsS79aU7kZkd2Wo9ckQ_Content;
typedef struct tyTuple__C9b9afwUTvJA9cIgAGy6KA9bmA tyTuple__C9b9afwUTvJA9cIgAGy6KA9bmA;
typedef struct tyTuple__sr3s7uVHpu9cEbbDnCSg8yQ tyTuple__sr3s7uVHpu9cEbbDnCSg8yQ;
typedef struct tyTuple__1mz0biObQVP6bIC9aN2C6Wg tyTuple__1mz0biObQVP6bIC9aN2C6Wg;
typedef struct tyTuple__snyXV4Zy8jmzo1DV7Xf9ayA tyTuple__snyXV4Zy8jmzo1DV7Xf9ayA;
typedef struct tyTuple__SLuMioJc9c7fCSoNPZct1yg tyTuple__SLuMioJc9c7fCSoNPZct1yg;
typedef struct tyObject_LoopState__pqHnaBqXqwBYAYqU2t3ZiQ tyObject_LoopState__pqHnaBqXqwBYAYqU2t3ZiQ;
typedef struct tyTuple__wtWLNU9apnkPc9agX3NbNVKA tyTuple__wtWLNU9apnkPc9agX3NbNVKA;
typedef struct tyObject_ResolvedArg__N9brVylJks69a9bZnI4zt9bmYQ tyObject_ResolvedArg__N9brVylJks69a9bZnI4zt9bmYQ;
typedef struct tyObject_StringPart__HKwvF6B260acLKHOHlpVRQ tyObject_StringPart__HKwvF6B260acLKHOHlpVRQ;
struct tyObject_CakeLimits__2XYWqO8BQUN9b9cmdJrTSD7A {
	NI32 maxCallDepth;
	NI32 maxIterations;
	NI32 maxTicks;
	NI32 maxVariables;
	NI32 maxMemory;
};
struct tySequence__tjkxNOQY9cAdAh85u9cULN9cg {
  NI len; tySequence__tjkxNOQY9cAdAh85u9cULN9cg_Content* p;
};
struct tySequence__QSd3I0juamqA6Vj3d6tVAw {
  NI len; tySequence__QSd3I0juamqA6Vj3d6tVAw_Content* p;
};
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
struct tyObject_CompiledProgram__rw4x9birAJsXbFMKqoyp47w {
	tySequence__tjkxNOQY9cAdAh85u9cULN9cg instructions;
	tySequence__QSd3I0juamqA6Vj3d6tVAw blocks;
	NIM_BOOL hasError;
	NimStringV2 errorMsg;
};
struct tySequence__04t1eEEZQNAyf6WBHIz2aw {
  NI len; tySequence__04t1eEEZQNAyf6WBHIz2aw_Content* p;
};
struct tySequence__pUxI6Ljo6IKKHXKOZkQ7Og {
  NI len; tySequence__pUxI6Ljo6IKKHXKOZkQ7Og_Content* p;
};
struct tyObject_Table__XUxYzMtKpHmwzeIZXCNmlQ {
	tySequence__pUxI6Ljo6IKKHXKOZkQ7Og data;
	NI counter;
};
struct tySequence__PPBaB565t0oqWHu7wDYghA {
  NI len; tySequence__PPBaB565t0oqWHu7wDYghA_Content* p;
};
struct tySequence__ehwmGsb9ad9cXxegdq9a9a6QtQ {
  NI len; tySequence__ehwmGsb9ad9cXxegdq9a9a6QtQ_Content* p;
};
struct tyObject_Table__9a66NC9blQIGrSsoZt4wuA9bA {
	tySequence__ehwmGsb9ad9cXxegdq9a9a6QtQ data;
	NI counter;
};
struct tySequence__0pv9ai34D5C6bYu9aWlERk9cg {
  NI len; tySequence__0pv9ai34D5C6bYu9aWlERk9cg_Content* p;
};
struct tyObject_Table__s4eUpSrH4WdAo9ba9cO1MWqQ {
	tySequence__0pv9ai34D5C6bYu9aWlERk9cg data;
	NI counter;
};
struct tySequence__GWB2ugnQavMoz8YICIsyiw {
  NI len; tySequence__GWB2ugnQavMoz8YICIsyiw_Content* p;
};
struct tyObject_VM__Vb9aBiSMJ3JOzO9ceFKf50cw {
	tySequence__04t1eEEZQNAyf6WBHIz2aw allInstructions;
	tyObject_Table__XUxYzMtKpHmwzeIZXCNmlQ blockIndex;
	NI currentList;
	NI ip;
	NIM_BOOL halted;
	NimStringV2 error;
	NI errorLine;
	NI errorCol;
	tyObject_ScopeFrameObj__79aJK3XdXc5CZiNkEpfDhCQ* scope;
	tySequence__PPBaB565t0oqWHu7wDYghA callStack;
	NimStringV2 outputBuffer;
	tyObject_Table__9a66NC9blQIGrSsoZt4wuA9bA builtins;
	tyObject_Table__s4eUpSrH4WdAo9ba9cO1MWqQ peripherals;
	NI maxCallDepth;
	NI maxIterations;
	NI maxTicks;
	NI maxVariables;
	NI maxMemory;
	NI tickCount;
	NI iterationCount;
	NI memUsage;
	NI varCount;
	NIM_BOOL lastAllocating;
	tySequence__GWB2ugnQavMoz8YICIsyiw loopStack;
};
struct tySequence__p4DprHqS6CWRWYxXa8hKOQ {
  NI len; tySequence__p4DprHqS6CWRWYxXa8hKOQ_Content* p;
};
struct tySequence__Cv7TuhXmGIkCLGuWTSaHow {
  NI len; tySequence__Cv7TuhXmGIkCLGuWTSaHow_Content* p;
};
struct tyObject_CakeVMObj__34PPuLHRBi5xCED6l9cxqtg {
	tyObject_VM__Vb9aBiSMJ3JOzO9ceFKf50cw vm;
	NimStringV2 savedState;
	tyObject_CakeLimits__2XYWqO8BQUN9b9cmdJrTSD7A limits;
	tySequence__p4DprHqS6CWRWYxXa8hKOQ customFns;
	tySequence__Cv7TuhXmGIkCLGuWTSaHow peripheralRegs;
};
typedef N_CDECL_PTR(tyObject_ValueObj__GvkVL3gYndVcF1SEP1HhDQ*, tyProc__9bbtL29aopzhWTrQe2vOYoxQ) (tyObject_CakeVMObj__34PPuLHRBi5xCED6l9cxqtg* vm_p0, NI32 argc_p1, tyObject_ValueObj__GvkVL3gYndVcF1SEP1HhDQ** argv_p2);
struct tyTuple__GsU7WpoQEf9a39amWFeK9aVIQ {
	NimStringV2 Field0;
	tyProc__9bbtL29aopzhWTrQe2vOYoxQ Field1;
};
struct tySequence__3Ser9bAvvL6U0lEMcdzQiSw {
  NI len; tySequence__3Ser9bAvvL6U0lEMcdzQiSw_Content* p;
};
struct tyObject_Table__mbpGVJrPdClMnjx1YPEhYA {
	tySequence__3Ser9bAvvL6U0lEMcdzQiSw data;
	NI counter;
};
struct tyObject_Peripheral__67pLM35FlCh2M409bcB4B5Q {
	tyObject_Table__mbpGVJrPdClMnjx1YPEhYA properties;
	tyObject_Table__9a66NC9blQIGrSsoZt4wuA9bA methods;
};
struct tyTuple__A9avNQiAjJiDux9bLEU4a17Q {
	NimStringV2 Field0;
	tyObject_Peripheral__67pLM35FlCh2M409bcB4B5Q Field1;
};
struct tySequence__FZ9ca77725E4Q3UZTxnRAkA {
  NI len; tySequence__FZ9ca77725E4Q3UZTxnRAkA_Content* p;
};
typedef struct {
N_NIMCALL_PTR(tyObject_ValueObj__GvkVL3gYndVcF1SEP1HhDQ*, ClP_0) (tyObject_VM__Vb9aBiSMJ3JOzO9ceFKf50cw* vm_p0, tySequence__FZ9ca77725E4Q3UZTxnRAkA args_p1, void* ClE_0);
void* ClE_0;
} tyProc__QGRrQEKOEc0STyzpnx8rcQ;
struct TNimTypeV2 {
	void* destructor;
	NI size;
	NI16 align;
	NI16 depth;
	NU32* display;
	void* traceImpl;
	void* typeInfoV1;
	NI flags;
	void* vTable[SEQ_DECL_SIZE];
};
struct RootObj {
	TNimTypeV2* m_type;
};
struct tyObject_Env_c_apidotnim_makeBuiltinWrapper___ra9cnzikOxz1Zeu1Kb1UkNg {
	RootObj Sup;
	tyProc__9bbtL29aopzhWTrQe2vOYoxQ cb0;
	tyObject_CakeVMObj__34PPuLHRBi5xCED6l9cxqtg* cv1;
};
typedef NU8 tyEnum_ValueKind__FfLIFKfIB9bQCxObIghtb9bg;
typedef NU8 tyEnum_ArrElemType__ZAFftDK9bP4RM1cf9a3YJ2FQ;
struct tyObject_ValueObj__GvkVL3gYndVcF1SEP1HhDQ {
	tyEnum_ValueKind__FfLIFKfIB9bQCxObIghtb9bg kind;
union{
	struct {
	NI32 intVal;
} _kind_1;
	struct {
	NF floatVal;
} _kind_2;
	struct {
	NimStringV2 strVal;
} _kind_3;
	struct {
	tySequence__FZ9ca77725E4Q3UZTxnRAkA arrVal;
	tyEnum_ArrElemType__ZAFftDK9bP4RM1cf9a3YJ2FQ elemType;
} _kind_4;
	struct {
	NimStringV2 errMsg;
} _kind_5;
};
};
struct tyObject_CakePeripheral__1N2Ijp8MEoiX9agXZduCB1A {
	tyObject_CakePeripheralProperty__VdUD5ZgF2oQkUm4Fmm8chg* properties;
	NI32 propertyCount;
	tyObject_CakePeripheralMethod__0bD3iqrOc9bYABKoNRo5kFQ* methods;
	NI32 methodCount;
};
typedef struct {
N_NIMCALL_PTR(void, ClP_0) (tyObject_VM__Vb9aBiSMJ3JOzO9ceFKf50cw* vm_p0, tyObject_ValueObj__GvkVL3gYndVcF1SEP1HhDQ* val_p1, void* ClE_0);
void* ClE_0;
} tyProc__OCdmoTN9cKklB20TMMtdlfQ;
typedef N_CDECL_PTR(tyObject_ValueObj__GvkVL3gYndVcF1SEP1HhDQ*, tyProc__b6IdTe9biZNPLZku48W2hHQ) (tyObject_CakeVMObj__34PPuLHRBi5xCED6l9cxqtg* vm_p0);
typedef N_CDECL_PTR(void, tyProc__EfyASrJCsslKlWVp4WQm5g) (tyObject_CakeVMObj__34PPuLHRBi5xCED6l9cxqtg* vm_p0, tyObject_ValueObj__GvkVL3gYndVcF1SEP1HhDQ* val_p1);
struct tyObject_CakePeripheralProperty__VdUD5ZgF2oQkUm4Fmm8chg {
	NCSTRING name;
	tyProc__b6IdTe9biZNPLZku48W2hHQ getter;
	tyProc__EfyASrJCsslKlWVp4WQm5g setter;
};
typedef struct {
N_NIMCALL_PTR(tyObject_ValueObj__GvkVL3gYndVcF1SEP1HhDQ*, ClP_0) (tyObject_VM__Vb9aBiSMJ3JOzO9ceFKf50cw* vm_p0, void* ClE_0);
void* ClE_0;
} tyProc__0okpiiXGH9b74rFj7fridcg;
struct tyObject_PeripheralProperty__q9bbhPnTUeZLtBNPVecSIig {
	tyProc__0okpiiXGH9b74rFj7fridcg getter;
	tyProc__OCdmoTN9cKklB20TMMtdlfQ setter;
	NIM_BOOL hasSetter;
};
struct tyObject_Env_c_apidotnim_makeGetter___xsVbh0tLMBI9a5ePRycpUig {
	RootObj Sup;
	tyProc__b6IdTe9biZNPLZku48W2hHQ cb0;
	tyObject_CakeVMObj__34PPuLHRBi5xCED6l9cxqtg* cv1;
};
struct tyObject_Env_c_apidotnim_makeSetter___YrM9bHq9c9aIC9cq9bWjTwQKQUw {
	RootObj Sup;
	tyProc__EfyASrJCsslKlWVp4WQm5g cb0;
	tyObject_CakeVMObj__34PPuLHRBi5xCED6l9cxqtg* cv1;
};
struct tyObject_CakePeripheralMethod__0bD3iqrOc9bYABKoNRo5kFQ {
	NCSTRING name;
	tyProc__9bbtL29aopzhWTrQe2vOYoxQ handler;
};
struct tyObject_Env_c_apidotnim_makeMethod___P3ev4im13F5MEkE6FL5f0g {
	RootObj Sup;
	tyProc__9bbtL29aopzhWTrQe2vOYoxQ cb0;
	tyObject_CakeVMObj__34PPuLHRBi5xCED6l9cxqtg* cv1;
};
typedef NU8 tyEnum_InstrKind__rQo514xDUpHi9bK2iBT5E9bw;
struct tySequence__WsDlUegMKP5qbZfDE7UOgg {
  NI len; tySequence__WsDlUegMKP5qbZfDE7UOgg_Content* p;
};
typedef NU8 tyEnum_ArgKind__cRc9crps0ZqW7m703wzDXLQ;
struct tySequence__blakBku9aKYZtnss5hJNT1Q {
  NI len; tySequence__blakBku9aKYZtnss5hJNT1Q_Content* p;
};
struct tySequence__B5XQ2QsS79aU7kZkd2Wo9ckQ {
  NI len; tySequence__B5XQ2QsS79aU7kZkd2Wo9ckQ_Content* p;
};
struct tyObject_Arg__E9boIsLlAjypGlVaV0b9crIA {
	NI line;
	NI col;
	tyEnum_ArgKind__cRc9crps0ZqW7m703wzDXLQ kind;
union{
	struct {
	NI32 intVal;
} _kind_1;
	struct {
	NF floatVal;
} _kind_2;
	struct {
	tySequence__blakBku9aKYZtnss5hJNT1Q strParts;
} _kind_3;
	struct {
	NimStringV2 identName;
} _kind_4;
	struct {
	tySequence__B5XQ2QsS79aU7kZkd2Wo9ckQ arrayElems;
} _kind_5;
};
};
typedef NU8 tyEnum_TokenType__KSIs0B9bnT5A3drOf5JgESQ;
struct tyObject_Condition__pS6iJoNrp0lYt3mVF9cXsPQ {
	tyObject_Arg__E9boIsLlAjypGlVaV0b9crIA left;
	tyEnum_TokenType__KSIs0B9bnT5A3drOf5JgESQ op;
	tyObject_Arg__E9boIsLlAjypGlVaV0b9crIA right;
};
struct tyObject_Instruction__XTstQEb9co2NNRaKJBBih9ag {
	tyEnum_InstrKind__rQo514xDUpHi9bK2iBT5E9bw kind;
	NI line;
	NI col;
	NimStringV2 funcName;
	NIM_BOOL isMethod;
	NimStringV2 peripheral;
	NimStringV2 methodName;
	tySequence__WsDlUegMKP5qbZfDE7UOgg args;
	NimStringV2 destVar;
	NimStringV2 destPeripheral;
	NimStringV2 destProperty;
	NIM_BOOL hasDest;
	tyObject_Condition__pS6iJoNrp0lYt3mVF9cXsPQ condition;
	NI jumpTarget;
	NI loopEndIp;
	NimStringV2 countName;
	NI32 countVal;
	NimStringV2 arrayName;
	tySequence__WsDlUegMKP5qbZfDE7UOgg arrayLit;
	NimStringV2 itemVar;
	NimStringV2 blockName;
};
struct tySequence__tjkxNOQY9cAdAh85u9cULN9cg_Content { NI cap; tyObject_Instruction__XTstQEb9co2NNRaKJBBih9ag data[SEQ_DECL_SIZE]; };
struct tyTuple__C9b9afwUTvJA9cIgAGy6KA9bmA {
	NimStringV2 Field0;
	tySequence__tjkxNOQY9cAdAh85u9cULN9cg Field1;
};
struct tySequence__QSd3I0juamqA6Vj3d6tVAw_Content { NI cap; tyTuple__C9b9afwUTvJA9cIgAGy6KA9bmA data[SEQ_DECL_SIZE]; };
struct tySequence__04t1eEEZQNAyf6WBHIz2aw_Content { NI cap; tySequence__tjkxNOQY9cAdAh85u9cULN9cg data[SEQ_DECL_SIZE]; };
struct tyTuple__sr3s7uVHpu9cEbbDnCSg8yQ {
	NI Field0;
	NimStringV2 Field1;
	NI Field2;
};
struct tySequence__pUxI6Ljo6IKKHXKOZkQ7Og_Content { NI cap; tyTuple__sr3s7uVHpu9cEbbDnCSg8yQ data[SEQ_DECL_SIZE]; };
struct tyTuple__1mz0biObQVP6bIC9aN2C6Wg {
	NI Field0;
	NI Field1;
	tyObject_ScopeFrameObj__79aJK3XdXc5CZiNkEpfDhCQ* Field2;
};
struct tySequence__PPBaB565t0oqWHu7wDYghA_Content { NI cap; tyTuple__1mz0biObQVP6bIC9aN2C6Wg data[SEQ_DECL_SIZE]; };
struct tyTuple__snyXV4Zy8jmzo1DV7Xf9ayA {
	NI Field0;
	NimStringV2 Field1;
	tyProc__QGRrQEKOEc0STyzpnx8rcQ Field2;
};
struct tySequence__ehwmGsb9ad9cXxegdq9a9a6QtQ_Content { NI cap; tyTuple__snyXV4Zy8jmzo1DV7Xf9ayA data[SEQ_DECL_SIZE]; };
struct tyTuple__SLuMioJc9c7fCSoNPZct1yg {
	NI Field0;
	NimStringV2 Field1;
	tyObject_Peripheral__67pLM35FlCh2M409bcB4B5Q Field2;
};
struct tySequence__0pv9ai34D5C6bYu9aWlERk9cg_Content { NI cap; tyTuple__SLuMioJc9c7fCSoNPZct1yg data[SEQ_DECL_SIZE]; };
struct tyObject_LoopState__pqHnaBqXqwBYAYqU2t3ZiQ {
	tyObject_ScopeFrameObj__79aJK3XdXc5CZiNkEpfDhCQ* loopScope;
	NI innerLoopList;
	NI innerLoopHeaderIp;
	NI32 loopCounter;
	NI32 loopTarget;
	tySequence__FZ9ca77725E4Q3UZTxnRAkA eachArray;
	NI eachIndex;
	NimStringV2 eachItemVar;
};
struct tySequence__GWB2ugnQavMoz8YICIsyiw_Content { NI cap; tyObject_LoopState__pqHnaBqXqwBYAYqU2t3ZiQ data[SEQ_DECL_SIZE]; };
struct tySequence__p4DprHqS6CWRWYxXa8hKOQ_Content { NI cap; tyTuple__GsU7WpoQEf9a39amWFeK9aVIQ data[SEQ_DECL_SIZE]; };
struct tySequence__Cv7TuhXmGIkCLGuWTSaHow_Content { NI cap; tyTuple__A9avNQiAjJiDux9bLEU4a17Q data[SEQ_DECL_SIZE]; };
struct tyTuple__wtWLNU9apnkPc9agX3NbNVKA {
	NI Field0;
	NimStringV2 Field1;
	tyObject_PeripheralProperty__q9bbhPnTUeZLtBNPVecSIig Field2;
};
struct tySequence__3Ser9bAvvL6U0lEMcdzQiSw_Content { NI cap; tyTuple__wtWLNU9apnkPc9agX3NbNVKA data[SEQ_DECL_SIZE]; };
struct tySequence__FZ9ca77725E4Q3UZTxnRAkA_Content { NI cap; tyObject_ValueObj__GvkVL3gYndVcF1SEP1HhDQ* data[SEQ_DECL_SIZE]; };
typedef NU8 tyEnum_ResolvedArgKind__rOyDWs6RUOZGhPFyds3edw;
struct tyObject_ResolvedArg__N9brVylJks69a9bZnI4zt9bmYQ {
	tyEnum_ResolvedArgKind__rOyDWs6RUOZGhPFyds3edw kind;
union{
	struct {
	NI32 intVal;
} _kind_1;
	struct {
	NF floatVal;
} _kind_2;
	struct {
	tySequence__blakBku9aKYZtnss5hJNT1Q strParts;
} _kind_3;
	struct {
	NimStringV2 varName;
} _kind_4;
	struct {
	tySequence__WsDlUegMKP5qbZfDE7UOgg elements;
} _kind_5;
};
};
struct tySequence__WsDlUegMKP5qbZfDE7UOgg_Content { NI cap; tyObject_ResolvedArg__N9brVylJks69a9bZnI4zt9bmYQ data[SEQ_DECL_SIZE]; };
struct tyObject_StringPart__HKwvF6B260acLKHOHlpVRQ {
	NIM_BOOL isInterp;
union{
	struct {
	NimStringV2 lit;
} _isInterp_1;
	struct {
	NimStringV2 varName;
} _isInterp_2;
};
};
struct tySequence__blakBku9aKYZtnss5hJNT1Q_Content { NI cap; tyObject_StringPart__HKwvF6B260acLKHOHlpVRQ data[SEQ_DECL_SIZE]; };
struct tySequence__B5XQ2QsS79aU7kZkd2Wo9ckQ_Content { NI cap; tyObject_Arg__E9boIsLlAjypGlVaV0b9crIA data[SEQ_DECL_SIZE]; };
N_LIB_EXPORT N_CDECL(NCSTRING, cake_version)(void);
N_LIB_EXPORT N_CDECL(tyObject_CakeVMObj__34PPuLHRBi5xCED6l9cxqtg*, cake_new)(tyObject_CakeLimits__2XYWqO8BQUN9b9cmdJrTSD7A limits_p0);
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1);
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NOCONV(void*, alloc0Impl__system_u1749)(NI size_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___OOZsrcZcakesparkZc95api_u720)(tyObject_VM__Vb9aBiSMJ3JOzO9ceFKf50cw* dest_p0, tyObject_VM__Vb9aBiSMJ3JOzO9ceFKf50cw* src_p1);
N_LIB_PRIVATE N_NIMCALL(void, newVM__OOZsrcZcakesparkZvm_u15947)(tyObject_CompiledProgram__rw4x9birAJsXbFMKqoyp47w* program_p0, tyObject_VM__Vb9aBiSMJ3JOzO9ceFKf50cw* Result);
N_LIB_PRIVATE N_NIMCALL(void, compileSource__OOZsrcZcakesparkZcakespark_u6)(NimStringV2 source_p0, tyObject_CompiledProgram__rw4x9birAJsXbFMKqoyp47w* Result);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___system_u2616)(NimStringV2* dest_p0, NimStringV2 src_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___OOZsrcZcakesparkZc95api_u378)(tySequence__p4DprHqS6CWRWYxXa8hKOQ* dest_p0, tySequence__p4DprHqS6CWRWYxXa8hKOQ src_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZsrcZcakesparkZc95api_u369)(tySequence__p4DprHqS6CWRWYxXa8hKOQ dest_p0);
N_LIB_PRIVATE N_NOCONV(void, dealloc)(void* p_p0);
N_LIB_PRIVATE N_NIMCALL(void, alignedDealloc)(void* p_p0, NI align_p1);
N_LIB_PRIVATE N_NIMCALL(void*, newSeqPayload)(NI cap_p0, NI elemSize_p1, NI elemAlign_p2);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___OOZsrcZcakesparkZc95api_u548)(tySequence__Cv7TuhXmGIkCLGuWTSaHow* dest_p0, tySequence__Cv7TuhXmGIkCLGuWTSaHow src_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZsrcZcakesparkZc95api_u539)(tySequence__Cv7TuhXmGIkCLGuWTSaHow dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZsrcZcakesparkZvm_u2828)(tySequence__3Ser9bAvvL6U0lEMcdzQiSw dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZsrcZcakesparkZvm_u2994)(tySequence__ehwmGsb9ad9cXxegdq9a9a6QtQ dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, applyLimits__OOZsrcZcakesparkZc95api_u44)(tyObject_CakeVMObj__34PPuLHRBi5xCED6l9cxqtg* cv_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZsrcZcakesparkZcakespark_u15)(tyObject_CompiledProgram__rw4x9birAJsXbFMKqoyp47w* dest_p0);
N_LIB_EXPORT N_CDECL(void, cake_free)(tyObject_CakeVMObj__34PPuLHRBi5xCED6l9cxqtg* cv_p0);
N_LIB_PRIVATE N_NIMCALL(void, reset__OOZsrcZcakesparkZc95api_u860)(tyObject_VM__Vb9aBiSMJ3JOzO9ceFKf50cw* obj_p0);
N_LIB_PRIVATE N_NIMCALL(void, reset__system_u3013)(NimStringV2* obj_p0);
N_LIB_PRIVATE N_NIMCALL(void, reset__OOZsrcZcakesparkZc95api_u877)(tySequence__p4DprHqS6CWRWYxXa8hKOQ* obj_p0);
N_LIB_PRIVATE N_NIMCALL(void, reset__OOZsrcZcakesparkZc95api_u891)(tySequence__Cv7TuhXmGIkCLGuWTSaHow* obj_p0);
N_LIB_EXPORT N_CDECL(NI32, cake_compile)(tyObject_CakeVMObj__34PPuLHRBi5xCED6l9cxqtg* cv_p0, NCSTRING source_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, cstrToNimstr)(NCSTRING str_p0);
N_LIB_PRIVATE N_NIMCALL(void, reapplyRegistrations__OOZsrcZcakesparkZc95api_u262)(tyObject_CakeVMObj__34PPuLHRBi5xCED6l9cxqtg* cv_p0);
N_LIB_PRIVATE N_NIMCALL(void, X5BX5Deq___OOZsrcZcakesparkZvm_u11899)(tyObject_Table__9a66NC9blQIGrSsoZt4wuA9bA* t_p0, NimStringV2 key_p1, tyProc__QGRrQEKOEc0STyzpnx8rcQ val_p2);
N_LIB_PRIVATE N_NIMCALL(void, makeBuiltinWrapper__OOZsrcZcakesparkZc95api_u46)(tyObject_CakeVMObj__34PPuLHRBi5xCED6l9cxqtg* cv_p0, tyProc__9bbtL29aopzhWTrQe2vOYoxQ cb_p1, tyProc__QGRrQEKOEc0STyzpnx8rcQ* Result);
N_LIB_PRIVATE N_NIMCALL(void*, nimNewObj)(NI size_p0, NI alignment_p1);
N_LIB_PRIVATE N_CLOSURE(tyObject_ValueObj__GvkVL3gYndVcF1SEP1HhDQ*, colonanonymous___OOZsrcZcakesparkZc95api_u50)(tyObject_VM__Vb9aBiSMJ3JOzO9ceFKf50cw* vm_p0, tySequence__FZ9ca77725E4Q3UZTxnRAkA args_p1, void* ClE_0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZsrcZcakesparkZvalue_u86)(tySequence__FZ9ca77725E4Q3UZTxnRAkA dest_p0);
N_LIB_PRIVATE N_NIMCALL(tySequence__FZ9ca77725E4Q3UZTxnRAkA, newSeq__OOZsrcZcakesparkZvalue_u304)(NI len_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___OOZsrcZcakesparkZvalue_u153)(tyObject_ValueObj__GvkVL3gYndVcF1SEP1HhDQ** dest_p0, tyObject_ValueObj__GvkVL3gYndVcF1SEP1HhDQ* src_p1);
N_LIB_PRIVATE N_NIMCALL(void, registerPeripheral__OOZsrcZcakesparkZvm_u11788)(tyObject_VM__Vb9aBiSMJ3JOzO9ceFKf50cw* vm_p0, NimStringV2 name_p1, tyObject_Peripheral__67pLM35FlCh2M409bcB4B5Q p_p2);
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___system_u2607)(NimStringV2* dest_p0);
N_LIB_EXPORT N_CDECL(NI32, cake_tick)(tyObject_CakeVMObj__34PPuLHRBi5xCED6l9cxqtg* cv_p0);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, tick__OOZsrcZcakesparkZvm_u7995)(tyObject_VM__Vb9aBiSMJ3JOzO9ceFKf50cw* vm_p0);
N_LIB_EXPORT N_CDECL(NI32, cake_run)(tyObject_CakeVMObj__34PPuLHRBi5xCED6l9cxqtg* cv_p0);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, run__OOZsrcZcakesparkZvm_u8003)(tyObject_VM__Vb9aBiSMJ3JOzO9ceFKf50cw* vm_p0);
N_LIB_EXPORT N_CDECL(void, cake_register_fn)(tyObject_CakeVMObj__34PPuLHRBi5xCED6l9cxqtg* cv_p0, NCSTRING name_p1, tyProc__9bbtL29aopzhWTrQe2vOYoxQ handler_p2);
N_LIB_PRIVATE N_NIMCALL(void, add__OOZsrcZcakesparkZc95api_u921)(tySequence__p4DprHqS6CWRWYxXa8hKOQ* x_p0, tyTuple__GsU7WpoQEf9a39amWFeK9aVIQ y_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, eqdup___system_u2613)(NimStringV2 src_p0);
N_LIB_EXPORT N_CDECL(void, cake_register_peripheral)(tyObject_CakeVMObj__34PPuLHRBi5xCED6l9cxqtg* cv_p0, NCSTRING name_p1, tyObject_CakePeripheral__1N2Ijp8MEoiX9agXZduCB1A* p_p2);
N_LIB_PRIVATE N_NIMCALL(tyObject_Table__mbpGVJrPdClMnjx1YPEhYA, initTable__OOZsrcZcakesparkZvm_u10197)(NI initialSize_p0);
N_LIB_PRIVATE N_NIMCALL(tyObject_Table__9a66NC9blQIGrSsoZt4wuA9bA, initTable__OOZsrcZcakesparkZvm_u9892)(NI initialSize_p0);
N_LIB_PRIVATE N_NIMCALL(void, X5BX5Deq___OOZsrcZcakesparkZc95api_u1076)(tyObject_Table__mbpGVJrPdClMnjx1YPEhYA* t_p0, NimStringV2 key_p1, tyObject_PeripheralProperty__q9bbhPnTUeZLtBNPVecSIig val_p2);
N_LIB_PRIVATE N_NIMCALL(void, makeGetter__OOZsrcZcakesparkZc95api_u124)(tyObject_CakeVMObj__34PPuLHRBi5xCED6l9cxqtg* cv_p0, tyProc__b6IdTe9biZNPLZku48W2hHQ cb_p1, tyProc__0okpiiXGH9b74rFj7fridcg* Result);
N_LIB_PRIVATE N_CLOSURE(tyObject_ValueObj__GvkVL3gYndVcF1SEP1HhDQ*, colonanonymous___OOZsrcZcakesparkZc95api_u128)(tyObject_VM__Vb9aBiSMJ3JOzO9ceFKf50cw* vm_p0, void* ClE_0);
N_LIB_PRIVATE N_NIMCALL(void, makeSetter__OOZsrcZcakesparkZc95api_u170)(tyObject_CakeVMObj__34PPuLHRBi5xCED6l9cxqtg* cv_p0, tyProc__EfyASrJCsslKlWVp4WQm5g cb_p1, tyProc__OCdmoTN9cKklB20TMMtdlfQ* Result);
N_LIB_PRIVATE N_CLOSURE(void, colonanonymous___OOZsrcZcakesparkZc95api_u174)(tyObject_VM__Vb9aBiSMJ3JOzO9ceFKf50cw* vm_p0, tyObject_ValueObj__GvkVL3gYndVcF1SEP1HhDQ* val_p1, void* ClE_0);
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___OOZsrcZcakesparkZc95api_u177)(tyProc__OCdmoTN9cKklB20TMMtdlfQ* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZsrcZcakesparkZc95api_u180)(tyProc__OCdmoTN9cKklB20TMMtdlfQ* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, makeMethod__OOZsrcZcakesparkZc95api_u216)(tyObject_CakeVMObj__34PPuLHRBi5xCED6l9cxqtg* cv_p0, tyProc__9bbtL29aopzhWTrQe2vOYoxQ cb_p1, tyProc__QGRrQEKOEc0STyzpnx8rcQ* Result);
N_LIB_PRIVATE N_CLOSURE(tyObject_ValueObj__GvkVL3gYndVcF1SEP1HhDQ*, colonanonymous___OOZsrcZcakesparkZc95api_u220)(tyObject_VM__Vb9aBiSMJ3JOzO9ceFKf50cw* vm_p0, tySequence__FZ9ca77725E4Q3UZTxnRAkA args_p1, void* ClE_0);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringV2 a_p0, NimStringV2 b_p1);
static N_INLINE(NIM_BOOL, equalMem__system_u1739)(void* a_p0, void* b_p1, NI size_p2);
static N_INLINE(int, nimCmpMem)(void* a_p0, void* b_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(void, add__OOZsrcZcakesparkZc95api_u2094)(tySequence__Cv7TuhXmGIkCLGuWTSaHow* x_p0, tyTuple__A9avNQiAjJiDux9bLEU4a17Q* y_p1);
N_LIB_PRIVATE N_NIMCALL(tyObject_Peripheral__67pLM35FlCh2M409bcB4B5Q, eqdup___OOZsrcZcakesparkZvm_u10960)(tyObject_Peripheral__67pLM35FlCh2M409bcB4B5Q src_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZsrcZcakesparkZvm_u10954)(tyObject_Peripheral__67pLM35FlCh2M409bcB4B5Q* dest_p0);
N_LIB_EXPORT N_CDECL(tyObject_ValueObj__GvkVL3gYndVcF1SEP1HhDQ*, cake_get_var)(tyObject_CakeVMObj__34PPuLHRBi5xCED6l9cxqtg* cv_p0, NCSTRING name_p1);
N_LIB_PRIVATE N_NIMCALL(tyObject_ValueObj__GvkVL3gYndVcF1SEP1HhDQ*, getVar__OOZsrcZcakesparkZvm_u426)(tyObject_VM__Vb9aBiSMJ3JOzO9ceFKf50cw* vm_p0, NimStringV2 name_p1);
N_LIB_EXPORT N_CDECL(void, cake_set_var)(tyObject_CakeVMObj__34PPuLHRBi5xCED6l9cxqtg* cv_p0, NCSTRING name_p1, tyObject_ValueObj__GvkVL3gYndVcF1SEP1HhDQ* val_p2);
N_LIB_PRIVATE N_NIMCALL(void, setVar__OOZsrcZcakesparkZvm_u900)(tyObject_VM__Vb9aBiSMJ3JOzO9ceFKf50cw* vm_p0, NimStringV2 name_p1, tyObject_ValueObj__GvkVL3gYndVcF1SEP1HhDQ* value_p2);
N_LIB_EXPORT N_CDECL(NCSTRING, cake_get_output)(tyObject_CakeVMObj__34PPuLHRBi5xCED6l9cxqtg* cv_p0);
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringV2 s_p0);
N_LIB_EXPORT N_CDECL(NCSTRING, cake_get_error)(tyObject_CakeVMObj__34PPuLHRBi5xCED6l9cxqtg* cv_p0);
N_LIB_EXPORT N_CDECL(NCSTRING, cake_save_state)(tyObject_CakeVMObj__34PPuLHRBi5xCED6l9cxqtg* cv_p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, saveState__OOZsrcZcakesparkZvm_u8880)(tyObject_VM__Vb9aBiSMJ3JOzO9ceFKf50cw* vm_p0);
static N_INLINE(void, eqdestroy___system_u281)(NimStringV2 x_p0);
N_LIB_EXPORT N_CDECL(NI32, cake_load_state)(tyObject_CakeVMObj__34PPuLHRBi5xCED6l9cxqtg* cv_p0, NCSTRING json_p1);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, loadState__OOZsrcZcakesparkZvm_u9746)(tyObject_VM__Vb9aBiSMJ3JOzO9ceFKf50cw* vm_p0, NimStringV2 json_p1);
static const struct {
  NI cap; NIM_CHAR data[0+1];
} TM__I4SZIQDGLVz9bpAuFLC4Ptg_2 = { 0 | NIM_STRLIT_FLAG, "" };
static const NimStringV2 TM__I4SZIQDGLVz9bpAuFLC4Ptg_3 = {0, (NimStrPayload*)&TM__I4SZIQDGLVz9bpAuFLC4Ptg_2};
static const NimStringV2 TM__I4SZIQDGLVz9bpAuFLC4Ptg_4 = {0, (NimStrPayload*)&TM__I4SZIQDGLVz9bpAuFLC4Ptg_2};
N_LIB_PRIVATE TNimTypeV2 NTIv2__ra9cnzikOxz1Zeu1Kb1UkNg_;
N_LIB_PRIVATE TNimTypeV2 NTIv2__xsVbh0tLMBI9a5ePRycpUig_;
N_LIB_PRIVATE TNimTypeV2 NTIv2__YrM9bHq9c9aIC9cq9bWjTwQKQUw_;
static NIM_CONST tyProc__OCdmoTN9cKklB20TMMtdlfQ TM__I4SZIQDGLVz9bpAuFLC4Ptg_8 = {NIM_NIL,NIM_NIL};
N_LIB_PRIVATE TNimTypeV2 NTIv2__P3ev4im13F5MEkE6FL5f0g_;
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__I4SZIQDGLVz9bpAuFLC4Ptg_10 = { 3 | NIM_STRLIT_FLAG, "str" };
static const NimStringV2 TM__I4SZIQDGLVz9bpAuFLC4Ptg_11 = {3, (NimStrPayload*)&TM__I4SZIQDGLVz9bpAuFLC4Ptg_10};
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__I4SZIQDGLVz9bpAuFLC4Ptg_12 = { 3 | NIM_STRLIT_FLAG, "arr" };
static const NimStringV2 TM__I4SZIQDGLVz9bpAuFLC4Ptg_13 = {3, (NimStrPayload*)&TM__I4SZIQDGLVz9bpAuFLC4Ptg_12};
extern NIM_BOOL nimInErrorMode__system_u3521;
static NIM_CONST NU32 TM__I4SZIQDGLVz9bpAuFLC4Ptg_5[2] = {3701606400, 2951204352};
N_LIB_PRIVATE TNimTypeV2 NTIv2__ra9cnzikOxz1Zeu1Kb1UkNg_ = {.destructor = (void*)NIM_NIL, .size = sizeof(tyObject_Env_c_apidotnim_makeBuiltinWrapper___ra9cnzikOxz1Zeu1Kb1UkNg), .align = (NI16) NIM_ALIGNOF(tyObject_Env_c_apidotnim_makeBuiltinWrapper___ra9cnzikOxz1Zeu1Kb1UkNg), .depth = 1, .display = TM__I4SZIQDGLVz9bpAuFLC4Ptg_5, .traceImpl = (void*)NIM_NIL, .flags = 0};
static NIM_CONST NU32 TM__I4SZIQDGLVz9bpAuFLC4Ptg_6[2] = {3701606400, 3311109888};
N_LIB_PRIVATE TNimTypeV2 NTIv2__xsVbh0tLMBI9a5ePRycpUig_ = {.destructor = (void*)NIM_NIL, .size = sizeof(tyObject_Env_c_apidotnim_makeGetter___xsVbh0tLMBI9a5ePRycpUig), .align = (NI16) NIM_ALIGNOF(tyObject_Env_c_apidotnim_makeGetter___xsVbh0tLMBI9a5ePRycpUig), .depth = 1, .display = TM__I4SZIQDGLVz9bpAuFLC4Ptg_6, .traceImpl = (void*)NIM_NIL, .flags = 0};
static NIM_CONST NU32 TM__I4SZIQDGLVz9bpAuFLC4Ptg_7[2] = {3701606400, 3007192576};
N_LIB_PRIVATE TNimTypeV2 NTIv2__YrM9bHq9c9aIC9cq9bWjTwQKQUw_ = {.destructor = (void*)NIM_NIL, .size = sizeof(tyObject_Env_c_apidotnim_makeSetter___YrM9bHq9c9aIC9cq9bWjTwQKQUw), .align = (NI16) NIM_ALIGNOF(tyObject_Env_c_apidotnim_makeSetter___YrM9bHq9c9aIC9cq9bWjTwQKQUw), .depth = 1, .display = TM__I4SZIQDGLVz9bpAuFLC4Ptg_7, .traceImpl = (void*)NIM_NIL, .flags = 0};
static NIM_CONST NU32 TM__I4SZIQDGLVz9bpAuFLC4Ptg_9[2] = {3701606400, 2008015360};
N_LIB_PRIVATE TNimTypeV2 NTIv2__P3ev4im13F5MEkE6FL5f0g_ = {.destructor = (void*)NIM_NIL, .size = sizeof(tyObject_Env_c_apidotnim_makeMethod___P3ev4im13F5MEkE6FL5f0g), .align = (NI16) NIM_ALIGNOF(tyObject_Env_c_apidotnim_makeMethod___P3ev4im13F5MEkE6FL5f0g), .depth = 1, .display = TM__I4SZIQDGLVz9bpAuFLC4Ptg_9, .traceImpl = (void*)NIM_NIL, .flags = 0};
N_LIB_EXPORT N_CDECL(NCSTRING, cake_version)(void) {
	NCSTRING result;
{	result = "1.0.0";
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a_p0, v_p1, ((size_t) (size_p2)));
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u3521);
	return result;
}
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimSetMem__systemZmemory_u7(p_p0, ((int)0), size_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZsrcZcakesparkZc95api_u369)(tySequence__p4DprHqS6CWRWYxXa8hKOQ dest_p0) {
	NI colontmp_;
	colontmp_ = ((NI)0);
	{
		while (1) {
			NI T3_;
			T3_ = dest_p0.len;
			if (!(colontmp_ < T3_)) goto LA2;
			if (dest_p0.p->data[colontmp_].Field0.p && !(dest_p0.p->data[colontmp_].Field0.p->cap & NIM_STRLIT_FLAG)) {
 dealloc(dest_p0.p->data[colontmp_].Field0.p);
}
			colontmp_ += ((NI)1);
		} LA2: ;
	}
	if (dest_p0.p && !(dest_p0.p->cap & NIM_STRLIT_FLAG)) {
 alignedDealloc(dest_p0.p, NIM_ALIGNOF(tyTuple__GsU7WpoQEf9a39amWFeK9aVIQ));
}
}
N_LIB_PRIVATE N_NIMCALL(void, eqsink___OOZsrcZcakesparkZc95api_u378)(tySequence__p4DprHqS6CWRWYxXa8hKOQ* dest_p0, tySequence__p4DprHqS6CWRWYxXa8hKOQ src_p1) {
	if ((*dest_p0).p != src_p1.p) {	eqdestroy___OOZsrcZcakesparkZc95api_u369((*dest_p0));
	}
(*dest_p0).len = src_p1.len; (*dest_p0).p = src_p1.p;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZsrcZcakesparkZc95api_u539)(tySequence__Cv7TuhXmGIkCLGuWTSaHow dest_p0) {
	NI colontmp_;
	colontmp_ = ((NI)0);
	{
		while (1) {
			NI T3_;
			T3_ = dest_p0.len;
			if (!(colontmp_ < T3_)) goto LA2;
			if (dest_p0.p->data[colontmp_].Field0.p && !(dest_p0.p->data[colontmp_].Field0.p->cap & NIM_STRLIT_FLAG)) {
 dealloc(dest_p0.p->data[colontmp_].Field0.p);
}
			eqdestroy___OOZsrcZcakesparkZvm_u2828(dest_p0.p->data[colontmp_].Field1.properties.data);
			eqdestroy___OOZsrcZcakesparkZvm_u2994(dest_p0.p->data[colontmp_].Field1.methods.data);
			colontmp_ += ((NI)1);
		} LA2: ;
	}
	if (dest_p0.p && !(dest_p0.p->cap & NIM_STRLIT_FLAG)) {
 alignedDealloc(dest_p0.p, NIM_ALIGNOF(tyTuple__A9avNQiAjJiDux9bLEU4a17Q));
}
}
N_LIB_PRIVATE N_NIMCALL(void, eqsink___OOZsrcZcakesparkZc95api_u548)(tySequence__Cv7TuhXmGIkCLGuWTSaHow* dest_p0, tySequence__Cv7TuhXmGIkCLGuWTSaHow src_p1) {
	if ((*dest_p0).p != src_p1.p) {	eqdestroy___OOZsrcZcakesparkZc95api_u539((*dest_p0));
	}
(*dest_p0).len = src_p1.len; (*dest_p0).p = src_p1.p;
}
N_LIB_PRIVATE N_NIMCALL(void, applyLimits__OOZsrcZcakesparkZc95api_u44)(tyObject_CakeVMObj__34PPuLHRBi5xCED6l9cxqtg* cv_p0) {
	(*cv_p0).vm.maxCallDepth = ((NI) ((*cv_p0).limits.maxCallDepth));
	(*cv_p0).vm.maxIterations = ((NI) ((*cv_p0).limits.maxIterations));
	(*cv_p0).vm.maxTicks = ((NI) ((*cv_p0).limits.maxTicks));
	(*cv_p0).vm.maxVariables = ((NI) ((*cv_p0).limits.maxVariables));
	(*cv_p0).vm.maxMemory = ((NI) ((*cv_p0).limits.maxMemory));
}
N_LIB_EXPORT N_CDECL(tyObject_CakeVMObj__34PPuLHRBi5xCED6l9cxqtg*, cake_new)(tyObject_CakeLimits__2XYWqO8BQUN9b9cmdJrTSD7A limits_p0) {
	tyObject_CakeVMObj__34PPuLHRBi5xCED6l9cxqtg* result;
	tyObject_CompiledProgram__rw4x9birAJsXbFMKqoyp47w colontmpD_;
	void* T2_;
	tyObject_VM__Vb9aBiSMJ3JOzO9ceFKf50cw T3_;
	tySequence__p4DprHqS6CWRWYxXa8hKOQ T4_;
	tySequence__Cv7TuhXmGIkCLGuWTSaHow T5_;
NIM_BOOL oldNimErrFin1_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (tyObject_CakeVMObj__34PPuLHRBi5xCED6l9cxqtg*)0;
	nimZeroMem((void*)(&colontmpD_), sizeof(tyObject_CompiledProgram__rw4x9birAJsXbFMKqoyp47w));
	T2_ = (void*)0;
	T2_ = alloc0Impl__system_u1749(((NI)184));
	result = ((tyObject_CakeVMObj__34PPuLHRBi5xCED6l9cxqtg*) (T2_));
	compileSource__OOZsrcZcakesparkZcakespark_u6(TM__I4SZIQDGLVz9bpAuFLC4Ptg_3, (&colontmpD_));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	nimZeroMem((void*)(&T3_), sizeof(tyObject_VM__Vb9aBiSMJ3JOzO9ceFKf50cw));
	newVM__OOZsrcZcakesparkZvm_u15947((&colontmpD_), (&T3_));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	eqsink___OOZsrcZcakesparkZc95api_u720((&(*result).vm), (&T3_));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	eqsink___system_u2616((&(*result).savedState), TM__I4SZIQDGLVz9bpAuFLC4Ptg_4);
	(*result).limits = limits_p0;
	T4_.len = 0; T4_.p = NIM_NIL;
	T4_.len = 0; T4_.p = (tySequence__p4DprHqS6CWRWYxXa8hKOQ_Content*) newSeqPayload(0, sizeof(tyTuple__GsU7WpoQEf9a39amWFeK9aVIQ), NIM_ALIGNOF(tyTuple__GsU7WpoQEf9a39amWFeK9aVIQ));
	eqsink___OOZsrcZcakesparkZc95api_u378((&(*result).customFns), T4_);
	T5_.len = 0; T5_.p = NIM_NIL;
	T5_.len = 0; T5_.p = (tySequence__Cv7TuhXmGIkCLGuWTSaHow_Content*) newSeqPayload(0, sizeof(tyTuple__A9avNQiAjJiDux9bLEU4a17Q), NIM_ALIGNOF(tyTuple__A9avNQiAjJiDux9bLEU4a17Q));
	eqsink___OOZsrcZcakesparkZc95api_u548((&(*result).peripheralRegs), T5_);
	applyLimits__OOZsrcZcakesparkZc95api_u44(result);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	{
		LA1_:;
	}
	{
		oldNimErrFin1_ = *nimErr_; *nimErr_ = NIM_FALSE;
		eqdestroy___OOZsrcZcakesparkZcakespark_u15((&colontmpD_));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		*nimErr_ = oldNimErrFin1_;
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___OOZsrcZcakesparkZc95api_u366)(tySequence__p4DprHqS6CWRWYxXa8hKOQ* dest_p0) {
	(*dest_p0).len = 0; (*dest_p0).p = NIM_NIL;
}
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___OOZsrcZcakesparkZc95api_u536)(tySequence__Cv7TuhXmGIkCLGuWTSaHow* dest_p0) {
	(*dest_p0).len = 0; (*dest_p0).p = NIM_NIL;
}
N_LIB_EXPORT N_CDECL(void, cake_free)(tyObject_CakeVMObj__34PPuLHRBi5xCED6l9cxqtg* cv_p0) {
{	{
		if (!(cv_p0 == ((tyObject_CakeVMObj__34PPuLHRBi5xCED6l9cxqtg*) NIM_NIL))) goto LA3_;
		goto BeforeRet_;
	}
LA3_: ;
	reset__OOZsrcZcakesparkZc95api_u860((&(*cv_p0).vm));
	reset__system_u3013((&(*cv_p0).savedState));
	reset__OOZsrcZcakesparkZc95api_u877((&(*cv_p0).customFns));
	reset__OOZsrcZcakesparkZc95api_u891((&(*cv_p0).peripheralRegs));
	dealloc(((void*) (cv_p0)));
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_CLOSURE(tyObject_ValueObj__GvkVL3gYndVcF1SEP1HhDQ*, colonanonymous___OOZsrcZcakesparkZc95api_u50)(tyObject_VM__Vb9aBiSMJ3JOzO9ceFKf50cw* vm_p0, tySequence__FZ9ca77725E4Q3UZTxnRAkA args_p1, void* ClE_0) {
	tyObject_ValueObj__GvkVL3gYndVcF1SEP1HhDQ* result;
	tyObject_Env_c_apidotnim_makeBuiltinWrapper___ra9cnzikOxz1Zeu1Kb1UkNg* colonenvP__1;
	tySequence__FZ9ca77725E4Q3UZTxnRAkA argv_1;
	NI T7_;
	NI T12_;
NIM_BOOL oldNimErrFin1_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = NIM_NIL;
	colonenvP__1 = (tyObject_Env_c_apidotnim_makeBuiltinWrapper___ra9cnzikOxz1Zeu1Kb1UkNg*) ClE_0;
	argv_1.len = 0; argv_1.p = NIM_NIL;
	{
		NI T4_;
		T4_ = args_p1.len;
		if (!(T4_ == ((NI)0))) goto LA5_;
		result = (*colonenvP__1).cb0((*colonenvP__1).cv1, ((NI32)0), ((tyObject_ValueObj__GvkVL3gYndVcF1SEP1HhDQ**) NIM_NIL));
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		eqdestroy___OOZsrcZcakesparkZvalue_u86(argv_1);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		goto BeforeRet_;
	}
LA5_: ;
	T7_ = args_p1.len;
	argv_1 = newSeq__OOZsrcZcakesparkZvalue_u304((T7_));
	{
		NI i_1;
		NI colontmp_;
		NI T9_;
		NI i_2;
		i_1 = (NI)0;
		colontmp_ = (NI)0;
		T9_ = args_p1.len;
		colontmp_ = T9_;
		i_2 = ((NI)0);
		{
			while (1) {
				if (!(i_2 < colontmp_)) goto LA11;
				i_1 = i_2;
				eqcopy___OOZsrcZcakesparkZvalue_u153(&argv_1.p->data[i_1], args_p1.p->data[i_1]);
				if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
				i_2 += ((NI)1);
			} LA11: ;
		}
	}
	T12_ = args_p1.len;
	result = (*colonenvP__1).cb0((*colonenvP__1).cv1, ((NI32) (T12_)), &argv_1.p->data[((NI)0)]);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	eqdestroy___OOZsrcZcakesparkZvalue_u86(argv_1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	goto BeforeRet_;
	{
		LA1_:;
	}
	{
		oldNimErrFin1_ = *nimErr_; *nimErr_ = NIM_FALSE;
		eqdestroy___OOZsrcZcakesparkZvalue_u86(argv_1);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		*nimErr_ = oldNimErrFin1_;
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, makeBuiltinWrapper__OOZsrcZcakesparkZc95api_u46)(tyObject_CakeVMObj__34PPuLHRBi5xCED6l9cxqtg* cv_p0, tyProc__9bbtL29aopzhWTrQe2vOYoxQ cb_p1, tyProc__QGRrQEKOEc0STyzpnx8rcQ* Result) {
	tyObject_Env_c_apidotnim_makeBuiltinWrapper___ra9cnzikOxz1Zeu1Kb1UkNg* colonenv__1;
	tyObject_Env_c_apidotnim_makeBuiltinWrapper___ra9cnzikOxz1Zeu1Kb1UkNg* T1_;
	tyObject_Env_c_apidotnim_makeBuiltinWrapper___ra9cnzikOxz1Zeu1Kb1UkNg* blitTmp_1;
	tyProc__QGRrQEKOEc0STyzpnx8rcQ T2_;
	colonenv__1 = NIM_NIL;
	T1_ = NIM_NIL;
	T1_ = (tyObject_Env_c_apidotnim_makeBuiltinWrapper___ra9cnzikOxz1Zeu1Kb1UkNg*) nimNewObj(sizeof(tyObject_Env_c_apidotnim_makeBuiltinWrapper___ra9cnzikOxz1Zeu1Kb1UkNg), NIM_ALIGNOF(tyObject_Env_c_apidotnim_makeBuiltinWrapper___ra9cnzikOxz1Zeu1Kb1UkNg));
	(*T1_).Sup.m_type = (&NTIv2__ra9cnzikOxz1Zeu1Kb1UkNg_);
	colonenv__1 = T1_;
	(*colonenv__1).cv1 = cv_p0;
	(*colonenv__1).cb0 = cb_p1;
	blitTmp_1 = colonenv__1;
	nimZeroMem((void*)(&T2_), sizeof(tyProc__QGRrQEKOEc0STyzpnx8rcQ));
	T2_.ClP_0 = colonanonymous___OOZsrcZcakesparkZc95api_u50; T2_.ClE_0 = blitTmp_1;
	(*Result).ClE_0 = T2_.ClE_0;
	(*Result).ClP_0 = T2_.ClP_0;
}
N_LIB_PRIVATE N_NIMCALL(void, reapplyRegistrations__OOZsrcZcakesparkZc95api_u262)(tyObject_CakeVMObj__34PPuLHRBi5xCED6l9cxqtg* cv_p0) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	{
		NimStringV2* n_1;
		tyProc__9bbtL29aopzhWTrQe2vOYoxQ* h_1;
		NI i_1;
		NI L_1;
		NI T2_;
		n_1 = (NimStringV2*)0;
		h_1 = (tyProc__9bbtL29aopzhWTrQe2vOYoxQ*)0;
		i_1 = ((NI)0);
		T2_ = (*cv_p0).customFns.len;
		L_1 = T2_;
		{
			while (1) {
				tyProc__QGRrQEKOEc0STyzpnx8rcQ T5_;
				if (!(i_1 < L_1)) goto LA4;
				n_1 = (&(*cv_p0).customFns.p->data[i_1].Field0);
				h_1 = (&(*cv_p0).customFns.p->data[i_1].Field1);
				nimZeroMem((void*)(&T5_), sizeof(tyProc__QGRrQEKOEc0STyzpnx8rcQ));
				makeBuiltinWrapper__OOZsrcZcakesparkZc95api_u46(cv_p0, (*h_1), (&T5_));
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				X5BX5Deq___OOZsrcZcakesparkZvm_u11899((&(*cv_p0).vm.builtins), (*n_1), T5_);
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				i_1 += ((NI)1);
			} LA4: ;
		}
	}
	{
		NimStringV2* n_2;
		tyObject_Peripheral__67pLM35FlCh2M409bcB4B5Q* per_1;
		NI i_2;
		NI L_2;
		NI T7_;
		n_2 = (NimStringV2*)0;
		per_1 = (tyObject_Peripheral__67pLM35FlCh2M409bcB4B5Q*)0;
		i_2 = ((NI)0);
		T7_ = (*cv_p0).peripheralRegs.len;
		L_2 = T7_;
		{
			while (1) {
				if (!(i_2 < L_2)) goto LA9;
				n_2 = (&(*cv_p0).peripheralRegs.p->data[i_2].Field0);
				per_1 = (&(*cv_p0).peripheralRegs.p->data[i_2].Field1);
				registerPeripheral__OOZsrcZcakesparkZvm_u11788((&(*cv_p0).vm), (*n_2), (*per_1));
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				i_2 += ((NI)1);
			} LA9: ;
		}
	}
	}BeforeRet_: ;
}
N_LIB_EXPORT N_CDECL(NI32, cake_compile)(tyObject_CakeVMObj__34PPuLHRBi5xCED6l9cxqtg* cv_p0, NCSTRING source_p1) {
	NI32 result;
	tyObject_CompiledProgram__rw4x9birAJsXbFMKqoyp47w compiled_1;
	NimStringV2 colontmpD_;
	tyObject_VM__Vb9aBiSMJ3JOzO9ceFKf50cw T2_;
NIM_BOOL oldNimErrFin1_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NI32)0;
	nimZeroMem((void*)(&compiled_1), sizeof(tyObject_CompiledProgram__rw4x9birAJsXbFMKqoyp47w));
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	colontmpD_ = cstrToNimstr(source_p1);
	compileSource__OOZsrcZcakesparkZcakespark_u6(colontmpD_, (&compiled_1));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	nimZeroMem((void*)(&T2_), sizeof(tyObject_VM__Vb9aBiSMJ3JOzO9ceFKf50cw));
	newVM__OOZsrcZcakesparkZvm_u15947((&compiled_1), (&T2_));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	eqsink___OOZsrcZcakesparkZc95api_u720((&(*cv_p0).vm), (&T2_));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	applyLimits__OOZsrcZcakesparkZc95api_u44(cv_p0);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	reapplyRegistrations__OOZsrcZcakesparkZc95api_u262(cv_p0);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	{
		if (!compiled_1.hasError) goto LA5_;
		eqsink___system_u2616((&(*cv_p0).vm.error), compiled_1.errorMsg);
		eqwasMoved___system_u2607((&compiled_1.errorMsg));
		result = ((NI32)-1);
		if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 dealloc(colontmpD_.p);
}
		eqdestroy___OOZsrcZcakesparkZcakespark_u15((&compiled_1));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		goto BeforeRet_;
	}
LA5_: ;
	result = ((NI32)0);
	if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 dealloc(colontmpD_.p);
}
	eqdestroy___OOZsrcZcakesparkZcakespark_u15((&compiled_1));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	goto BeforeRet_;
	{
		LA1_:;
	}
	{
		oldNimErrFin1_ = *nimErr_; *nimErr_ = NIM_FALSE;
		if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 dealloc(colontmpD_.p);
}
		eqdestroy___OOZsrcZcakesparkZcakespark_u15((&compiled_1));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		*nimErr_ = oldNimErrFin1_;
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_EXPORT N_CDECL(NI32, cake_tick)(tyObject_CakeVMObj__34PPuLHRBi5xCED6l9cxqtg* cv_p0) {
	NI32 result;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	{
		if (!(*cv_p0).vm.halted) goto LA3_;
		result = ((NI32)0);
		goto BeforeRet_;
	}
LA3_: ;
	{
		NIM_BOOL T7_;
		T7_ = (NIM_BOOL)0;
		T7_ = tick__OOZsrcZcakesparkZvm_u7995((&(*cv_p0).vm));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (!!(T7_)) goto LA8_;
		{
			if (!((*cv_p0).vm.error.len == 0)) goto LA12_;
			result = ((NI32)0);
			goto BeforeRet_;
		}
		goto LA10_;
LA12_: ;
		{
			result = ((NI32)-1);
			goto BeforeRet_;
		}
LA10_: ;
	}
LA8_: ;
	result = ((NI32)1);
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_EXPORT N_CDECL(NI32, cake_run)(tyObject_CakeVMObj__34PPuLHRBi5xCED6l9cxqtg* cv_p0) {
	NI32 result;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = run__OOZsrcZcakesparkZvm_u8003((&(*cv_p0).vm));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (!T3_) goto LA4_;
		{
			if (!!(((*cv_p0).vm.error.len == 0))) goto LA8_;
			result = ((NI32)-1);
			goto BeforeRet_;
		}
LA8_: ;
		result = ((NI32)0);
		goto BeforeRet_;
	}
LA4_: ;
	{
		if (!!(((*cv_p0).vm.error.len == 0))) goto LA12_;
		result = ((NI32)-1);
		goto BeforeRet_;
	}
LA12_: ;
	result = ((NI32)0);
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_EXPORT N_CDECL(void, cake_register_fn)(tyObject_CakeVMObj__34PPuLHRBi5xCED6l9cxqtg* cv_p0, NCSTRING name_p1, tyProc__9bbtL29aopzhWTrQe2vOYoxQ handler_p2) {
	NimStringV2 n_1;
	NimStringV2 colontmpD_;
	tyProc__9bbtL29aopzhWTrQe2vOYoxQ colontmpD__2;
	tyTuple__GsU7WpoQEf9a39amWFeK9aVIQ T1_;
	tyProc__QGRrQEKOEc0STyzpnx8rcQ T2_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	n_1.len = 0; n_1.p = NIM_NIL;
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	colontmpD__2 = (tyProc__9bbtL29aopzhWTrQe2vOYoxQ)0;
	n_1 = cstrToNimstr(name_p1);
	colontmpD_ = eqdup___system_u2613(n_1);
	T1_.Field0 = colontmpD_;
	colontmpD__2 = handler_p2;
	T1_.Field1 = colontmpD__2;
	add__OOZsrcZcakesparkZc95api_u921((&(*cv_p0).customFns), T1_);
	nimZeroMem((void*)(&T2_), sizeof(tyProc__QGRrQEKOEc0STyzpnx8rcQ));
	makeBuiltinWrapper__OOZsrcZcakesparkZc95api_u46(cv_p0, handler_p2, (&T2_));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	X5BX5Deq___OOZsrcZcakesparkZvm_u11899((&(*cv_p0).vm.builtins), n_1, T2_);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	if (n_1.p && !(n_1.p->cap & NIM_STRLIT_FLAG)) {
 dealloc(n_1.p);
}
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_CLOSURE(tyObject_ValueObj__GvkVL3gYndVcF1SEP1HhDQ*, colonanonymous___OOZsrcZcakesparkZc95api_u128)(tyObject_VM__Vb9aBiSMJ3JOzO9ceFKf50cw* vm_p0, void* ClE_0) {
	tyObject_ValueObj__GvkVL3gYndVcF1SEP1HhDQ* result;
	tyObject_Env_c_apidotnim_makeGetter___xsVbh0tLMBI9a5ePRycpUig* colonenvP__1;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = NIM_NIL;
	colonenvP__1 = (tyObject_Env_c_apidotnim_makeGetter___xsVbh0tLMBI9a5ePRycpUig*) ClE_0;
	result = (*colonenvP__1).cb0((*colonenvP__1).cv1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, makeGetter__OOZsrcZcakesparkZc95api_u124)(tyObject_CakeVMObj__34PPuLHRBi5xCED6l9cxqtg* cv_p0, tyProc__b6IdTe9biZNPLZku48W2hHQ cb_p1, tyProc__0okpiiXGH9b74rFj7fridcg* Result) {
	tyObject_Env_c_apidotnim_makeGetter___xsVbh0tLMBI9a5ePRycpUig* colonenv__1;
	tyObject_Env_c_apidotnim_makeGetter___xsVbh0tLMBI9a5ePRycpUig* T1_;
	tyObject_Env_c_apidotnim_makeGetter___xsVbh0tLMBI9a5ePRycpUig* blitTmp_1;
	tyProc__0okpiiXGH9b74rFj7fridcg T2_;
	colonenv__1 = NIM_NIL;
	T1_ = NIM_NIL;
	T1_ = (tyObject_Env_c_apidotnim_makeGetter___xsVbh0tLMBI9a5ePRycpUig*) nimNewObj(sizeof(tyObject_Env_c_apidotnim_makeGetter___xsVbh0tLMBI9a5ePRycpUig), NIM_ALIGNOF(tyObject_Env_c_apidotnim_makeGetter___xsVbh0tLMBI9a5ePRycpUig));
	(*T1_).Sup.m_type = (&NTIv2__xsVbh0tLMBI9a5ePRycpUig_);
	colonenv__1 = T1_;
	(*colonenv__1).cv1 = cv_p0;
	(*colonenv__1).cb0 = cb_p1;
	blitTmp_1 = colonenv__1;
	nimZeroMem((void*)(&T2_), sizeof(tyProc__0okpiiXGH9b74rFj7fridcg));
	T2_.ClP_0 = colonanonymous___OOZsrcZcakesparkZc95api_u128; T2_.ClE_0 = blitTmp_1;
	(*Result).ClE_0 = T2_.ClE_0;
	(*Result).ClP_0 = T2_.ClP_0;
}
N_LIB_PRIVATE N_CLOSURE(void, colonanonymous___OOZsrcZcakesparkZc95api_u174)(tyObject_VM__Vb9aBiSMJ3JOzO9ceFKf50cw* vm_p0, tyObject_ValueObj__GvkVL3gYndVcF1SEP1HhDQ* val_p1, void* ClE_0) {
	tyObject_Env_c_apidotnim_makeSetter___YrM9bHq9c9aIC9cq9bWjTwQKQUw* colonenvP__1;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	colonenvP__1 = (tyObject_Env_c_apidotnim_makeSetter___YrM9bHq9c9aIC9cq9bWjTwQKQUw*) ClE_0;
	(*colonenvP__1).cb0((*colonenvP__1).cv1, val_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, makeSetter__OOZsrcZcakesparkZc95api_u170)(tyObject_CakeVMObj__34PPuLHRBi5xCED6l9cxqtg* cv_p0, tyProc__EfyASrJCsslKlWVp4WQm5g cb_p1, tyProc__OCdmoTN9cKklB20TMMtdlfQ* Result) {
	tyObject_Env_c_apidotnim_makeSetter___YrM9bHq9c9aIC9cq9bWjTwQKQUw* colonenv__1;
	tyObject_Env_c_apidotnim_makeSetter___YrM9bHq9c9aIC9cq9bWjTwQKQUw* T1_;
	tyObject_Env_c_apidotnim_makeSetter___YrM9bHq9c9aIC9cq9bWjTwQKQUw* blitTmp_1;
	tyProc__OCdmoTN9cKklB20TMMtdlfQ T2_;
	colonenv__1 = NIM_NIL;
	T1_ = NIM_NIL;
	T1_ = (tyObject_Env_c_apidotnim_makeSetter___YrM9bHq9c9aIC9cq9bWjTwQKQUw*) nimNewObj(sizeof(tyObject_Env_c_apidotnim_makeSetter___YrM9bHq9c9aIC9cq9bWjTwQKQUw), NIM_ALIGNOF(tyObject_Env_c_apidotnim_makeSetter___YrM9bHq9c9aIC9cq9bWjTwQKQUw));
	(*T1_).Sup.m_type = (&NTIv2__YrM9bHq9c9aIC9cq9bWjTwQKQUw_);
	colonenv__1 = T1_;
	(*colonenv__1).cv1 = cv_p0;
	(*colonenv__1).cb0 = cb_p1;
	blitTmp_1 = colonenv__1;
	nimZeroMem((void*)(&T2_), sizeof(tyProc__OCdmoTN9cKklB20TMMtdlfQ));
	T2_.ClP_0 = colonanonymous___OOZsrcZcakesparkZc95api_u174; T2_.ClE_0 = blitTmp_1;
	(*Result).ClE_0 = T2_.ClE_0;
	(*Result).ClP_0 = T2_.ClP_0;
}
N_LIB_PRIVATE N_CLOSURE(tyObject_ValueObj__GvkVL3gYndVcF1SEP1HhDQ*, colonanonymous___OOZsrcZcakesparkZc95api_u220)(tyObject_VM__Vb9aBiSMJ3JOzO9ceFKf50cw* vm_p0, tySequence__FZ9ca77725E4Q3UZTxnRAkA args_p1, void* ClE_0) {
	tyObject_ValueObj__GvkVL3gYndVcF1SEP1HhDQ* result;
	tyObject_Env_c_apidotnim_makeMethod___P3ev4im13F5MEkE6FL5f0g* colonenvP__1;
	tySequence__FZ9ca77725E4Q3UZTxnRAkA argv_1;
	NI T7_;
	NI T12_;
NIM_BOOL oldNimErrFin1_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = NIM_NIL;
	colonenvP__1 = (tyObject_Env_c_apidotnim_makeMethod___P3ev4im13F5MEkE6FL5f0g*) ClE_0;
	argv_1.len = 0; argv_1.p = NIM_NIL;
	{
		NI T4_;
		T4_ = args_p1.len;
		if (!(T4_ == ((NI)0))) goto LA5_;
		result = (*colonenvP__1).cb0((*colonenvP__1).cv1, ((NI32)0), ((tyObject_ValueObj__GvkVL3gYndVcF1SEP1HhDQ**) NIM_NIL));
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		eqdestroy___OOZsrcZcakesparkZvalue_u86(argv_1);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		goto BeforeRet_;
	}
LA5_: ;
	T7_ = args_p1.len;
	argv_1 = newSeq__OOZsrcZcakesparkZvalue_u304((T7_));
	{
		NI i_1;
		NI colontmp_;
		NI T9_;
		NI i_2;
		i_1 = (NI)0;
		colontmp_ = (NI)0;
		T9_ = args_p1.len;
		colontmp_ = T9_;
		i_2 = ((NI)0);
		{
			while (1) {
				if (!(i_2 < colontmp_)) goto LA11;
				i_1 = i_2;
				eqcopy___OOZsrcZcakesparkZvalue_u153(&argv_1.p->data[i_1], args_p1.p->data[i_1]);
				if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
				i_2 += ((NI)1);
			} LA11: ;
		}
	}
	T12_ = args_p1.len;
	result = (*colonenvP__1).cb0((*colonenvP__1).cv1, ((NI32) (T12_)), &argv_1.p->data[((NI)0)]);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	eqdestroy___OOZsrcZcakesparkZvalue_u86(argv_1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	goto BeforeRet_;
	{
		LA1_:;
	}
	{
		oldNimErrFin1_ = *nimErr_; *nimErr_ = NIM_FALSE;
		eqdestroy___OOZsrcZcakesparkZvalue_u86(argv_1);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		*nimErr_ = oldNimErrFin1_;
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, makeMethod__OOZsrcZcakesparkZc95api_u216)(tyObject_CakeVMObj__34PPuLHRBi5xCED6l9cxqtg* cv_p0, tyProc__9bbtL29aopzhWTrQe2vOYoxQ cb_p1, tyProc__QGRrQEKOEc0STyzpnx8rcQ* Result) {
	tyObject_Env_c_apidotnim_makeMethod___P3ev4im13F5MEkE6FL5f0g* colonenv__1;
	tyObject_Env_c_apidotnim_makeMethod___P3ev4im13F5MEkE6FL5f0g* T1_;
	tyObject_Env_c_apidotnim_makeMethod___P3ev4im13F5MEkE6FL5f0g* blitTmp_1;
	tyProc__QGRrQEKOEc0STyzpnx8rcQ T2_;
	colonenv__1 = NIM_NIL;
	T1_ = NIM_NIL;
	T1_ = (tyObject_Env_c_apidotnim_makeMethod___P3ev4im13F5MEkE6FL5f0g*) nimNewObj(sizeof(tyObject_Env_c_apidotnim_makeMethod___P3ev4im13F5MEkE6FL5f0g), NIM_ALIGNOF(tyObject_Env_c_apidotnim_makeMethod___P3ev4im13F5MEkE6FL5f0g));
	(*T1_).Sup.m_type = (&NTIv2__P3ev4im13F5MEkE6FL5f0g_);
	colonenv__1 = T1_;
	(*colonenv__1).cv1 = cv_p0;
	(*colonenv__1).cb0 = cb_p1;
	blitTmp_1 = colonenv__1;
	nimZeroMem((void*)(&T2_), sizeof(tyProc__QGRrQEKOEc0STyzpnx8rcQ));
	T2_.ClP_0 = colonanonymous___OOZsrcZcakesparkZc95api_u220; T2_.ClE_0 = blitTmp_1;
	(*Result).ClE_0 = T2_.ClE_0;
	(*Result).ClP_0 = T2_.ClP_0;
}
static N_INLINE(int, nimCmpMem)(void* a_p0, void* b_p1, NI size_p2) {
	int result;
	result = memcmp(a_p0, b_p1, ((size_t) (size_p2)));
	return result;
}
static N_INLINE(NIM_BOOL, equalMem__system_u1739)(void* a_p0, void* b_p1, NI size_p2) {
	NIM_BOOL result;
	int T1_;
	T1_ = (int)0;
	T1_ = nimCmpMem(a_p0, b_p1, size_p2);
	result = (T1_ == ((NI32)0));
	return result;
}
static N_INLINE(NIM_BOOL, eqStrings)(NimStringV2 a_p0, NimStringV2 b_p1) {
	NIM_BOOL result;
	NI alen_1;
	NI blen_1;
{	result = NIM_FALSE;
	alen_1 = a_p0.len;
	blen_1 = b_p1.len;
	{
		if (!(alen_1 == blen_1)) goto LA3_;
		{
			if (!(alen_1 == ((NI)0))) goto LA7_;
			result = NIM_TRUE;
			goto BeforeRet_;
		}
LA7_: ;
		result = equalMem__system_u1739(((void*) ((&a_p0.p->data[((NI)0)]))), ((void*) ((&b_p1.p->data[((NI)0)]))), (alen_1));
		goto BeforeRet_;
	}
LA3_: ;
	}BeforeRet_: ;
	return result;
}
N_LIB_EXPORT N_CDECL(void, cake_register_peripheral)(tyObject_CakeVMObj__34PPuLHRBi5xCED6l9cxqtg* cv_p0, NCSTRING name_p1, tyObject_CakePeripheral__1N2Ijp8MEoiX9agXZduCB1A* p_p2) {
	NimStringV2 n_1;
	tyObject_Peripheral__67pLM35FlCh2M409bcB4B5Q per_1;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	n_1.len = 0; n_1.p = NIM_NIL;
	nimZeroMem((void*)(&per_1), sizeof(tyObject_Peripheral__67pLM35FlCh2M409bcB4B5Q));
	n_1 = cstrToNimstr(name_p1);
	per_1.properties = initTable__OOZsrcZcakesparkZvm_u10197(((NI)32));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	per_1.methods = initTable__OOZsrcZcakesparkZvm_u9892(((NI)32));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	{
		tyObject_CakePeripheralProperty__VdUD5ZgF2oQkUm4Fmm8chg* props_1;
		tyObject_CakePeripheralMethod__0bD3iqrOc9bYABKoNRo5kFQ* meths_1;
		if (!!((p_p2 == ((tyObject_CakePeripheral__1N2Ijp8MEoiX9agXZduCB1A*) NIM_NIL)))) goto LA3_;
		props_1 = ((tyObject_CakePeripheralProperty__VdUD5ZgF2oQkUm4Fmm8chg*) ((*p_p2).properties));
		{
			NI i_1;
			NI colontmp_;
			NI i_2;
			i_1 = (NI)0;
			colontmp_ = (NI)0;
			colontmp_ = ((NI) ((*p_p2).propertyCount));
			i_2 = ((NI)0);
			{
				while (1) {
					NimStringV2 colontmpD_;
					tyProc__OCdmoTN9cKklB20TMMtdlfQ colontmpD__2;
					tyProc__OCdmoTN9cKklB20TMMtdlfQ colontmpD__3;
					tyObject_CakePeripheralProperty__VdUD5ZgF2oQkUm4Fmm8chg cp_1;
					tyObject_PeripheralProperty__q9bbhPnTUeZLtBNPVecSIig T8_;
					if (!(i_2 < colontmp_)) goto LA7;
					colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
					nimZeroMem((void*)(&colontmpD__2), sizeof(tyProc__OCdmoTN9cKklB20TMMtdlfQ));
					nimZeroMem((void*)(&colontmpD__3), sizeof(tyProc__OCdmoTN9cKklB20TMMtdlfQ));
					i_1 = i_2;
					cp_1 = props_1[i_1];
					colontmpD_ = cstrToNimstr(cp_1.name);
					nimZeroMem((void*)(&T8_), sizeof(tyObject_PeripheralProperty__q9bbhPnTUeZLtBNPVecSIig));
					makeGetter__OOZsrcZcakesparkZc95api_u124(cv_p0, cp_1.getter, (&T8_.getter));
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
					{
						tyProc__OCdmoTN9cKklB20TMMtdlfQ blitTmp_1;
						if (!!((cp_1.setter == NIM_NIL))) goto LA11_;
						makeSetter__OOZsrcZcakesparkZc95api_u170(cv_p0, cp_1.setter, (&colontmpD__2));
						if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
						nimZeroMem((void*)(&blitTmp_1), sizeof(tyProc__OCdmoTN9cKklB20TMMtdlfQ));
						blitTmp_1.ClE_0 = colontmpD__2.ClE_0;
						blitTmp_1.ClP_0 = colontmpD__2.ClP_0;
						eqwasMoved___OOZsrcZcakesparkZc95api_u177((&colontmpD__2));
						T8_.setter.ClE_0 = blitTmp_1.ClE_0;
						T8_.setter.ClP_0 = blitTmp_1.ClP_0;
					}
					goto LA9_;
LA11_: ;
					{
						tyProc__OCdmoTN9cKklB20TMMtdlfQ blitTmp_2;
						colontmpD__3.ClE_0 = TM__I4SZIQDGLVz9bpAuFLC4Ptg_8.ClE_0;
						colontmpD__3.ClP_0 = TM__I4SZIQDGLVz9bpAuFLC4Ptg_8.ClP_0;
						nimZeroMem((void*)(&blitTmp_2), sizeof(tyProc__OCdmoTN9cKklB20TMMtdlfQ));
						blitTmp_2.ClE_0 = colontmpD__3.ClE_0;
						blitTmp_2.ClP_0 = colontmpD__3.ClP_0;
						eqwasMoved___OOZsrcZcakesparkZc95api_u177((&colontmpD__3));
						T8_.setter.ClE_0 = blitTmp_2.ClE_0;
						T8_.setter.ClP_0 = blitTmp_2.ClP_0;
					}
LA9_: ;
					T8_.hasSetter = !((cp_1.setter == NIM_NIL));
					X5BX5Deq___OOZsrcZcakesparkZc95api_u1076((&per_1.properties), colontmpD_, T8_);
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
					i_2 += ((NI)1);
					eqdestroy___OOZsrcZcakesparkZc95api_u180((&colontmpD__3));
					eqdestroy___OOZsrcZcakesparkZc95api_u180((&colontmpD__2));
					if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 dealloc(colontmpD_.p);
}
				} LA7: ;
			}
		}
		meths_1 = ((tyObject_CakePeripheralMethod__0bD3iqrOc9bYABKoNRo5kFQ*) ((*p_p2).methods));
		{
			NI i_3;
			NI colontmp__2;
			NI i_4;
			i_3 = (NI)0;
			colontmp__2 = (NI)0;
			colontmp__2 = ((NI) ((*p_p2).methodCount));
			i_4 = ((NI)0);
			{
				while (1) {
					NimStringV2 colontmpD__4;
					tyObject_CakePeripheralMethod__0bD3iqrOc9bYABKoNRo5kFQ cm_1;
					tyProc__QGRrQEKOEc0STyzpnx8rcQ T17_;
					if (!(i_4 < colontmp__2)) goto LA16;
					colontmpD__4.len = 0; colontmpD__4.p = NIM_NIL;
					i_3 = i_4;
					cm_1 = meths_1[i_3];
					colontmpD__4 = cstrToNimstr(cm_1.name);
					nimZeroMem((void*)(&T17_), sizeof(tyProc__QGRrQEKOEc0STyzpnx8rcQ));
					makeMethod__OOZsrcZcakesparkZc95api_u216(cv_p0, cm_1.handler, (&T17_));
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
					X5BX5Deq___OOZsrcZcakesparkZvm_u11899((&per_1.methods), colontmpD__4, T17_);
					if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
					i_4 += ((NI)1);
					if (colontmpD__4.p && !(colontmpD__4.p->cap & NIM_STRLIT_FLAG)) {
 dealloc(colontmpD__4.p);
}
				} LA16: ;
			}
		}
	}
LA3_: ;
	{
		NIM_BOOL T20_;
		NimStringV2 colontmpD__5;
		tyObject_Peripheral__67pLM35FlCh2M409bcB4B5Q colontmpD__6;
		tyTuple__A9avNQiAjJiDux9bLEU4a17Q T24_;
		T20_ = (NIM_BOOL)0;
		T20_ = !(eqStrings(n_1, TM__I4SZIQDGLVz9bpAuFLC4Ptg_11));
		if (!(T20_)) goto LA21_;
		T20_ = !(eqStrings(n_1, TM__I4SZIQDGLVz9bpAuFLC4Ptg_13));
LA21_: ;
		if (!T20_) goto LA22_;
		colontmpD__5.len = 0; colontmpD__5.p = NIM_NIL;
		nimZeroMem((void*)(&colontmpD__6), sizeof(tyObject_Peripheral__67pLM35FlCh2M409bcB4B5Q));
		colontmpD__5 = eqdup___system_u2613(n_1);
		T24_.Field0 = colontmpD__5;
		colontmpD__6 = eqdup___OOZsrcZcakesparkZvm_u10960(per_1);
		T24_.Field1 = colontmpD__6;
		add__OOZsrcZcakesparkZc95api_u2094((&(*cv_p0).peripheralRegs), (&T24_));
	}
LA22_: ;
	registerPeripheral__OOZsrcZcakesparkZvm_u11788((&(*cv_p0).vm), n_1, per_1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	eqdestroy___OOZsrcZcakesparkZvm_u10954((&per_1));
	if (n_1.p && !(n_1.p->cap & NIM_STRLIT_FLAG)) {
 dealloc(n_1.p);
}
	}BeforeRet_: ;
}
N_LIB_EXPORT N_CDECL(tyObject_ValueObj__GvkVL3gYndVcF1SEP1HhDQ*, cake_get_var)(tyObject_CakeVMObj__34PPuLHRBi5xCED6l9cxqtg* cv_p0, NCSTRING name_p1) {
	tyObject_ValueObj__GvkVL3gYndVcF1SEP1HhDQ* result;
	NimStringV2 colontmpD_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = NIM_NIL;
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	colontmpD_ = cstrToNimstr(name_p1);
	result = getVar__OOZsrcZcakesparkZvm_u426((&(*cv_p0).vm), colontmpD_);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	{
		LA1_:;
	}
	{
		if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 dealloc(colontmpD_.p);
}
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_EXPORT N_CDECL(void, cake_set_var)(tyObject_CakeVMObj__34PPuLHRBi5xCED6l9cxqtg* cv_p0, NCSTRING name_p1, tyObject_ValueObj__GvkVL3gYndVcF1SEP1HhDQ* val_p2) {
	NimStringV2 colontmpD_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	colontmpD_ = cstrToNimstr(name_p1);
	setVar__OOZsrcZcakesparkZvm_u900((&(*cv_p0).vm), colontmpD_, val_p2);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 dealloc(colontmpD_.p);
}
	}BeforeRet_: ;
}
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringV2 s_p0) {
	NCSTRING result;
	{
		if (!(s_p0.len == ((NI)0))) goto LA3_;
		result = "";
	}
	goto LA1_;
LA3_: ;
	{
		result = ((NCSTRING) ((*s_p0.p).data));
	}
LA1_: ;
	return result;
}
N_LIB_EXPORT N_CDECL(NCSTRING, cake_get_output)(tyObject_CakeVMObj__34PPuLHRBi5xCED6l9cxqtg* cv_p0) {
	NCSTRING result;
	result = nimToCStringConv((*cv_p0).vm.outputBuffer);
	return result;
}
N_LIB_EXPORT N_CDECL(NCSTRING, cake_get_error)(tyObject_CakeVMObj__34PPuLHRBi5xCED6l9cxqtg* cv_p0) {
	NCSTRING result;
	result = nimToCStringConv((*cv_p0).vm.error);
	return result;
}
static N_INLINE(void, eqdestroy___system_u281)(NimStringV2 x_p0) {
}
N_LIB_EXPORT N_CDECL(NCSTRING, cake_save_state)(tyObject_CakeVMObj__34PPuLHRBi5xCED6l9cxqtg* cv_p0) {
	NCSTRING result;
	NimStringV2 T1_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NCSTRING)0;
	T1_.len = 0; T1_.p = NIM_NIL;
	T1_ = saveState__OOZsrcZcakesparkZvm_u8880((&(*cv_p0).vm));
	if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___system_u281(T1_); goto BeforeRet_;}
	eqsink___system_u2616((&(*cv_p0).savedState), T1_);
	result = nimToCStringConv((*cv_p0).savedState);
	}BeforeRet_: ;
	return result;
}
N_LIB_EXPORT N_CDECL(NI32, cake_load_state)(tyObject_CakeVMObj__34PPuLHRBi5xCED6l9cxqtg* cv_p0, NCSTRING json_p1) {
	NI32 result;
	NimStringV2 colontmpD_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	result = (NI32)0;
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	{
		NIM_BOOL T4_;
		colontmpD_ = cstrToNimstr(json_p1);
		T4_ = (NIM_BOOL)0;
		T4_ = loadState__OOZsrcZcakesparkZvm_u9746((&(*cv_p0).vm), colontmpD_);
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		if (!!(T4_)) goto LA5_;
		result = ((NI32)-1);
		if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 dealloc(colontmpD_.p);
}
		goto BeforeRet_;
	}
LA5_: ;
	reapplyRegistrations__OOZsrcZcakesparkZc95api_u262(cv_p0);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	result = ((NI32)0);
	if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 dealloc(colontmpD_.p);
}
	goto BeforeRet_;
	{
		LA1_:;
	}
	{
		if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 dealloc(colontmpD_.p);
}
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
