#!/usr/bin/env python3
# Bake the user's Downloads PNG icon set into ui/icons.c as RAW-PNG lv_image_dsc_t
# (LVGL's LODEPNG decoder decodes them at runtime). Keeps the kf_ic_* symbol names
# that ui/icons.h declares and ui/launcher.c references, so it's a drop-in.
import os, struct, sys

DL  = "/mnt/c/Users/Matas/Downloads"
OUT = "/home/legitbox/kefyros-pico/ui/icons.c"

# kf_ic_<symbol>  ->  Downloads PNG file
MAP = {
    "calc":       "calculator.png",
    "files":      "files.png",
    "wifi":       "wifi.png",
    "settings":   "settings.png",
    "appearance": "wallpaper.png",
    "editor":     "editor.png",
    "resistor":   "resistor.png",   # electronics tile
    "terminal":   "terminal.png",   # declared in icons.h (unused) — define anyway
    "web":        "netsurf.png",
}

def png_wh(b):
    # IHDR width/height are big-endian u32 at byte 16 / 20
    if b[:8] != b"\x89PNG\r\n\x1a\n":
        raise ValueError("not a PNG")
    w = struct.unpack(">I", b[16:20])[0]
    h = struct.unpack(">I", b[20:24])[0]
    return w, h

def emit_array(name, data):
    out = ["static const uint8_t %s[] = {" % name]
    row = []
    for i, byte in enumerate(data):
        row.append("0x%02x," % byte)
        if len(row) == 16:
            out.append("\t" + "".join(row)); row = []
    if row:
        out.append("\t" + "".join(row))
    out.append("};")
    return "\n".join(out)

blocks = ["// ui/icons.c — generated by tools/bake_icons.py. Do not edit.",
          "// App icons baked from the user's Downloads PNG set (RAW PNG, LODEPNG-decoded).",
          '#include "lvgl/lvgl.h"', ""]

for sym, fn in MAP.items():
    path = os.path.join(DL, fn)
    if not os.path.exists(path):
        sys.stderr.write("MISSING %s -> %s (skipped)\n" % (sym, path)); continue
    data = open(path, "rb").read()
    w, h = png_wh(data)
    arr = "kf_ic_%s_png" % sym
    blocks.append(emit_array(arr, data))
    blocks.append("const lv_image_dsc_t kf_ic_%s = {" % sym)
    blocks.append("\t.header.magic = LV_IMAGE_HEADER_MAGIC,")
    blocks.append("\t.header.cf = LV_COLOR_FORMAT_RAW,")
    blocks.append("\t.header.w = %d, .header.h = %d," % (w, h))
    blocks.append("\t.data = %s," % arr)
    blocks.append("\t.data_size = sizeof(%s)," % arr)
    blocks.append("};")
    blocks.append("")
    sys.stderr.write("baked kf_ic_%-10s <- %-16s %dx%d %d bytes\n" % (sym, fn, w, h, len(data)))

open(OUT, "w").write("\n".join(blocks))
sys.stderr.write("wrote %s\n" % OUT)
