// ui/fonts.h — IBM Plex Mono UI fonts (generated by lv_font_conv, in ui/*.c).
#ifndef KF_FONTS_H
#define KF_FONTS_H
#include "lvgl/lvgl.h"
LV_FONT_DECLARE(lv_font_plex_mono_13);   /* primary UI font */
LV_FONT_DECLARE(lv_font_plex_mono_20);   /* large — calc readout */
#endif
